### ISSUE TITLE
brew fails to install gcc49 for El Capitan

### ISSUE THREAD

**Issue by CarlosCD** [Homebrew/homebrew-versions#1010]
==> Installing homebrew/versions/gcc49
    ==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.9.3/gcc-4.9.3.tar.bz2
    ==> Downloading from http://gnu.mirror.vexxhost.com/gcc/gcc-4.9.3/gcc-4.9.3.tar.bz2
    ######################################################################## 100.0%
    ==> Downloading https://gcc.gnu.org/bugzilla/attachment.cgi?id=35773
    ######################################################################## 100.0%
    ==> Patching
    patching file gcc/config/darwin.c
    Hunk #1 succeeded at 1232 (offset -27 lines).
    ==> ../configure --build=x86_64-apple-darwin15.0.0 --prefix=/usr/local/Cellar/gcc49/4.9.3 --libdir=/usr/local/Cellar/gcc49/4.9.3/lib/gcc/4.9 --enable-langua
    ==> make bootstrap
    Last 15 lines from /Users/CarlosCD/Library/Logs/Homebrew/gcc49/02.make:
    build/genrecog ../../gcc/config/i386/i386.md \
    	  insn-conditions.md > tmp-recog.c
    /bin/sh ../../gcc/../move-if-change tmp-recog.c insn-recog.c
    echo timestamp > s-recog
    /private/tmp/gcc4920151107-19170-76xhm7/gcc-4.9.3/build/./prev-gcc/xg++ -B/private/tmp/gcc4920151107-19170-76xhm7/gcc-4.9.3/build/./prev-gcc/ -B/usr/local/Cellar/gcc49/4.9.3/x86_64-apple-darwin15.0.0/bin/ -nostdinc++ -B/private/tmp/gcc4920151107-19170-76xhm7/gcc-4.9.3/build/prev-x86_64-apple-darwin15.0.0/libstdc++-v3/src/.libs -B/private/tmp/gcc4920151107-19170-76xhm7/gcc-4.9.3/build/prev-x86_64-apple-darwin15.0.0/libstdc++-v3/libsupc++/.libs  -I/private/tmp/gcc4920151107-19170-76xhm7/gcc-4.9.3/build/prev-x86_64-apple-darwin15.0.0/libstdc++-v3/include/x86_64-apple-darwin15.0.0  -I/private/tmp/gcc4920151107-19170-76xhm7/gcc-4.9.3/build/prev-x86_64-apple-darwin15.0.0/libstdc++-v3/include  -I/private/tmp/gcc4920151107-19170-76xhm7/gcc-4.9.3/libstdc++-v3/libsupc++ -L/private/tmp/gcc4920151107-19170-76xhm7/gcc-4.9.3/build/prev-x86_64-apple-darwin15.0.0/libstdc++-v3/src/.libs -L/private/tmp/gcc4920151107-19170-76xhm7/gcc-4.9.3/build/prev-x86_64-apple-darwin15.0.0/libstdc++-v3/libsupc++/.libs -c   -g -O2  -gtoggle -DIN_GCC    -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -DGENERATOR_FILE -I. -Ibuild -I../../gcc -I../../gcc/build -I../../gcc/../include  -I../../gcc/../libcpp/include  \
    		-o build/gcov-iov.o ../../gcc/gcov-iov.c
    /bin/sh ../../gcc/../move-if-change tmp-output.c insn-output.c
    echo timestamp > s-output
    clang: error: no such file or directory: '/var/folders/rl/2d82t7hs3zn9bl4gb3rs4bdw0000gn/T//ccAC52Db.s'
    clang: error: no input files
    make[3]: *** [build/gcov-iov.o] Error 1
    rm gcc.pod
    make[2]: *** [all-stage2-gcc] Error 2
    make[1]: *** [stage2-bubble] Error 2
    make: *** [bootstrap] Error 2
    couldn't understand kern.osversion `15.0.0'

**Comment by CarlosCD** [comment]
Some other details:

    OS: OS X 10.11.1 - El Capitan
    xcodebuild -version
      Xcode 7.1
      Build version 7B91b
    gcc --version
      Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
      Apple LLVM version 7.0.0 (clang-700.1.76)
      Target: x86_64-apple-darwin15.0.0
      Thread model: posix
    make --version
      GNU Make 3.81
      Copyright (C) 2006  Free Software Foundation, Inc.
      ...

Default Ruby used to run `brew install gcc49`, using RVM:

    ruby -v
      ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
    rvm version
      rvm 1.26.11 (latest) by ...

System Ruby:

    rvm use system
    ruby -v
      ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]

**Comment by CarlosCD** [comment]
In case this can be useful to someone, I had no problems installing gcc48, which seems to have an "El Capital" specific bottle (`gcc48-4.8.4.el_capitan.bottle.2.tar.gz`).

My reason to get gcc 4.9 was actually to install ruby 1.8.7 using RVM, which has gcc49 as a requirement, so finally I decided to set the C compiler to gcc 4.8, and that worked well for me:

    which gcc-4.8
      /usr/local/bin/gcc-4.8
    CC=/usr/local/bin/gcc-4.8 rvm install 1.8.7
      ...
      Warning: found user selected compiler '/usr/local/bin/gcc-4.8', this will suppress RVM auto detection mechanisms.
      ...
      Install of ruby-1.8.7-head - #complete
      ...
    ruby -v
      ruby 1.8.7 (2014-01-28 patchlevel 376) [i686-darwin15.0.0]

**Comment by DomT4** [comment]
Can you do a full `brew gist-logs gcc49`? Cheers.

**Comment by CarlosCD** [comment]
Sorry, but it looks like the log has been removed. This is what I see:

    $ brew gist-logs gcc49
      Error: No logs.
    $

I tried to install it again right now, to see if I can get a log to show you, but now it worked without any problems at all... using homebrew-specific binaries, instead of using the gnu source I've got yesterday:

    brew install gcc49
      ==> Installing gcc49 from homebrew/homebrew-versions
      ==> Downloading https://homebrew.bintray.com/bottles-versions/gcc49-4.9.3.el_capitan.bottle.1.tar.gz
      ######################################################################## 100.0%
      ==> Pouring gcc49-4.9.3.el_capitan.bottle.1.tar.gz
      🍺  /usr/local/Cellar/gcc49/4.9.3: 1138 files, 165M

So it looks like we can close this issue. Thanks!

**Comment by DomT4** [comment]
Yeah, I added the new bottles last night. Let us know if you run into anything else!

**Comment by lcx** [comment]
Having the same issue as it's trying to compile. Any way I can force it to use the existing bottle?
