### ISSUE TITLE
Failed installing GCC49 using GCC44

### ISSUE THREAD

**Issue by ianpark** [Homebrew/homebrew-versions#1024]
Hi,

While I was installing NodeJS using LinuxBrew,  I ran into the compilation error about C++11 features in V8 engine. My GCC version is 4.4 and I have to stick with it due to my other C++ projects. I couldn't find the way to set -std=c++0x flag to the compilation option. So I decided to install gcc49 using Linuxbrew expecting not breaking the rest of my system and using it just for homebrew installation. 

So I did:
$ brew tap homebrew/versions
$ brew install gcc49

However it didn't go smooth. Actually failed with some strange error. Please have a look:

[ian@scg-sierra nodejs]$ brew install gcc49
==> Installing gcc49 from homebrew/homebrew-versions
==> Installing dependencies for homebrew/versions/gcc49: gmp4, mpfr2, libmpc08, isl011, cloog018
==> Installing homebrew/versions/gcc49 dependency: gmp4
==> Downloading http://ftpmirror.gnu.org/gmp/gmp-4.3.2.tar.bz2
==> Downloading from http://gnu.mirror.iweb.com/gmp/gmp-4.3.2.tar.bz2
######################################################################## 100.0%
==> Patching
patching file gmp-h.in
==> ./configure --prefix=/home/ian/.linuxbrew/Cellar/gmp4/4.3.2 --enable-cxx --build=x86_64-apple-darwin
==> make
Last 15 lines from /home/ian/.cache/Homebrew/Logs/gmp4/02.make:
/home/ian/.linuxbrew/bin/gcc-4.4 -std=gnu99 -Os -w -pipe -march=core2 -m64 -nostdlib -Wl,-r -o .libs/libgmp.la-415.o scanf/.libs/scanf.o .libs/libgmp.la-414.o
/home/ian/.linuxbrew/bin/gcc-4.4 -std=gnu99 -Os -w -pipe -march=core2 -m64 -nostdlib -Wl,-r -o .libs/libgmp.la-416.o scanf/.libs/sscanf.o .libs/libgmp.la-415.o
/home/ian/.linuxbrew/bin/gcc-4.4 -std=gnu99 -Os -w -pipe -march=core2 -m64 -nostdlib -Wl,-r -o .libs/libgmp.la-417.o scanf/.libs/sscanffuns.o .libs/libgmp.la-416.o
/home/ian/.linuxbrew/bin/gcc-4.4 -std=gnu99 -Os -w -pipe -march=core2 -m64 -nostdlib -Wl,-r -o .libs/libgmp.la-418.o scanf/.libs/vfscanf.o .libs/libgmp.la-417.o
/home/ian/.linuxbrew/bin/gcc-4.4 -std=gnu99 -Os -w -pipe -march=core2 -m64 -nostdlib -Wl,-r -o .libs/libgmp.la-419.o scanf/.libs/vscanf.o .libs/libgmp.la-418.o
/home/ian/.linuxbrew/bin/gcc-4.4 -std=gnu99 -Os -w -pipe -march=core2 -m64 -nostdlib -Wl,-r -o .libs/libgmp.la-420.o scanf/.libs/vsscanf.o .libs/libgmp.la-419.o
/home/ian/.linuxbrew/bin/gcc-4.4 -std=gnu99 -shared .libs/libgmp.la-420.o  -L/home/ian/.linuxbrew/lib  -march=core2 -m64 -Wl,-rpath -Wl,/home/ian/.linuxbrew/lib -Wl,-soname -Wl,libgmp.3.dylib -o .libs/libgmp.3.5.2.dylib
/usr/bin/ld: .libs/libgmp.la-420.o: relocation R_X86_64_32 against `__gmp_sscanf_funs' can not be used when making a shared object; recompile with -fPIC
.libs/libgmp.la-420.o: could not read symbols: Bad value
collect2: ld returned 1 exit status
make[2]: *** [libgmp.la] Error 1
make[2]: Leaving directory `/tmp/gmp420151116-42274-1894zl0/gmp-4.3.2'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/gmp420151116-42274-1894zl0/gmp-4.3.2'
make: *** [all] Error 2

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-versions/issues

**Comment by kaayy** [comment]
I tried commenting out --build=x86_64-apple-darwin setting in args in homebrew/versions/gmp4.rb and succeeded in compiling gmp4. Similar is mpfr2.

Looks like gmp4.rb is written for osx not linux.

**Comment by mikemcquaid** [comment]
@kaayy In Homebrew everything is written for OS X and not Linux.

**Comment by rafaeltiveron** [comment]
I am with the same problem. Even --build=x86_64-apple-darwin is there, the problem still persists.
