### ISSUE TITLE
gcc45 fails on OSX 10.11 : warning about symbol versioning/shared libgcc, and: "configure: error: unsupported system, cannot find sizeof (omp_lock_t)"

### ISSUE THREAD

**Issue by TheBloke** [Homebrew/homebrew-versions#1038]
I have a freshly installed 10.11.1 system.  I have installed latest XCode (7.1.1), brew, and quite a few brew packages that have all worked fine.  (When I first reported the issue I did not have XCode CLTs installed; I have now installed these and repeated the build, but this makes no difference.)

I'm now trying to install ```homebrew/versions/gcc45```, but unfortunately this is failing.

**Commands executed:**
```shell
brew update
brew tap homebrew/versions
brew install gcc45
```

**Problem :**

Configure fails with *configure: error: unsupported system, cannot find sizeof (omp_lock_t)*, as well as a warning about symbol versioning/shared libgcc.

Gist logs: https://gist.github.com/anonymous/89dcebd576454a48ce79

Terminal output below:

```shell
tomj@marvin:~$ brew doctor
Your system is ready to brew.

tomj@marvin:~$ brew install gcc45
==> Installing gcc45 from homebrew/homebrew-versions
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.5.4/gcc-4.5.4.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gcc45-4.5.4.tar.bz2
==> Downloading http://www.mirrorservice.org/sites/rsync.macports.org/release/ports/lang/gcc45/files/ppc_fde_encoding.diff
Already downloaded: /Library/Caches/Homebrew/gcc45--patch-49e335d085567467155ea6512ffa959a18eab0ef.diff
==> Downloading http://www.mirrorservice.org/sites/rsync.macports.org/release/ports/lang/gcc45/files/macosx-version-min.patch
Already downloaded: /Library/Caches/Homebrew/gcc45--patch-79a3314759a33059cd6e3a078fdb3f5ee957d2e6.patch
==> Patching
patching file libffi/src/powerpc/darwin.S
patching file libffi/src/powerpc/darwin_closure.S
patching file gcc/config/darwin-c.c
patching file gcc/config/darwin-driver.c
==> ../configure --build=x86_64-apple-darwin15.0.0 --prefix=/usr/local/Cellar/gcc45/4.5.4 --enable-languages=c,c++,objc,obj-c++ --program-suffix=-4.5 --with-gmp=/usr/local/opt/gmp
==> make bootstrap
Last 15 lines from /Users/tomj/Library/Logs/Homebrew/gcc45/02.make:
checking for ld used by /private/tmp/gcc4520151121-71330-1dkbn1x/gcc-4.5.4/build/./gcc/xgcc -B/private/tmp/gcc4520151121-71330-1dkbn1x/gcc-4.5.4/build/./gcc/ -B/usr/local/Cellar/gcc45/4.5.4/x86_64-apple-darwin15.0.0/bin/ -B/usr/local/Cellar/gcc45/4.5.4/x86_64-apple-darwin15.0.0/lib/ -isystem /usr/local/Cellar/gcc45/4.5.4/x86_64-apple-darwin15.0.0/include -isystem /usr/local/Cellar/gcc45/4.5.4/x86_64-apple-darwin15.0.0/sys-include  -m32... (cached) /private/tmp/gcc4520151121-71330-1dkbn1x/gcc-4.5.4/build/./gcc/collect-ld
checking if the linker (/private/tmp/gcc4520151121-71330-1dkbn1x/gcc-4.5.4/build/./gcc/collect-ld) is GNU ld... (cached) no
checking for shared libgcc... yes
configure: WARNING: === You have requested some kind of symbol versioning, but
configure: WARNING: === either you are not using a supported linker, or you are
configure: WARNING: === not building a shared libgcc_s (which is required).
configure: WARNING: === Symbol versioning will be disabled.
checking whether the target supports .symver directive... no
configure: versioning on shared library symbols is no
checking whether the target supports __sync_*_compare_and_swap... yes
configure: updating cache ./config.cache
configure: error: unsupported system, cannot find sizeof (omp_lock_t)
make[2]: *** [configure-stage1-target-libgomp] Error 1
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-versions/issues
```

**Comment by TheBloke** [comment]
One further update: as I was able to install gcc-4.9 OK, I thought I would see if that makes a difference for gcc-4.5 install.

So I did:

```brew install --cc=gcc-4.9 gcc45```

Unfortunately this fails with exactly the same error :(   It seemed to take longer to get to that point, but maybe that is my imagination (or just gcc-4.9 is slower than clang!)

From what I can understand of the output, it looks like the bootstrap GCC compile works OK, but then when it tries to compile itself with itself, that fails?

Anyway, hopefully there is some simple solution, and for now I will use gcc-4.9 where possible.

**Comment by TheBloke** [comment]
Today I actually Googled on the error, and found a description of the exact problem I'm having:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=43511

What's confusing is that issue was raised in 4.5.0 and was fixed quickly.  However, when I check the list of fixed PRs in [4.5.1](https://gcc.gnu.org/bugzilla/buglist.cgi?bug_status=RESOLVED&resolution=FIXED&target_milestone=4.5.1), [4.5.2](https://gcc.gnu.org/bugzilla/buglist.cgi?bug_status=RESOLVED&resolution=FIXED&target_milestone=4.5.2), [4.5.3](https://gcc.gnu.org/bugzilla/buglist.cgi?bug_status=RESOLVED&resolution=FIXED&target_milestone=4.5.3) and [4.5.4](https://gcc.gnu.org/bugzilla/buglist.cgi?bug_status=RESOLVED&resolution=FIXED&target_milestone=4.5.4), the PR 43511 is not listed.

So maybe it was fixed in 4.5.0 itself?  Though that PR is not listed in the 4.5.0 milesetone either.  Maybe I'm just misunderstanding the GCC PR system.

Either way, I don't understand why this bug raised and fixed in 2010 is still affecting 4.5.4 in 2015, and why it would suddenly happen to me now when presumably the gcc45 brew has existed, and worked, for a long time?  Unless there's some new situation which is able to trigger the identical bug.

Anyway, in the meantime I'm going to see if I can apply the fix mentioned in the PR 43511 to see if that does anything.  I can't do that right now as I need to go out, but will report back later as soon as I've had a chance.

**Comment by TheBloke** [comment]
One more update: the trac.macports.org URLs are now working again.  I  will edit my OP to remove that issue.

The other error remains the same.

I would be super grateful if someone could look at this, I'm really quite stuck at the moment.  I have to have gcc-4.5 for my project - I have tried and failed to use versions 4.9 and 5.2.  

My only option seems to be to use Macports, and I really don't like Macports!

**Comment by mikemcquaid** [comment]
I'm afraid that this may just flat out not work on 10.11 without patching. Is there a reason you need GCC 4.5 specifically? Thanks!

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
