### ISSUE TITLE
Trying to get G++ 4.8 on Snow Leopard

### ISSUE THREAD

**Issue by sentient06** [Homebrew/homebrew-versions#1049]
I will just drop it here...

    Tyr:~ $ brew install gcc48
    ==> Installing gcc48 from homebrew/homebrew-versions
    ==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.8.4/gcc-4.8.4.tar.bz2
    Already downloaded: /Library/Caches/Homebrew/gcc48-4.8.4.tar.bz2
    ==> ../configure --build=x86_64-apple-darwin10.8.0 --prefix=/usr/local/Cellar/gc
    ==> make bootstrap
    Last 15 lines from /Volumes/Data/10.6/Users/gian/Library/Logs/Homebrew/gcc48/02.make:
    true "AR_FLAGS=rc" "CC_FOR_BUILD=clang" "CFLAGS=-g -O2  -m32" "CXXFLAGS=-g -O2  -m32" "CFLAGS_FOR_BUILD=-g -O2" "CFLAGS_FOR_TARGET=-g -O2" "INSTALL=/usr/bin/install -c" "INSTALL_DATA=/usr/bin/install -c -m 644" "INSTALL_PROGRAM=/usr/bin/install -c" "INSTALL_SCRIPT=/usr/bin/install -c" "JC1FLAGS=" "LDFLAGS=-m32" "LIBCFLAGS=-g -O2  -m32" "LIBCFLAGS_FOR_TARGET=-g -O2" "MAKE=/usr/bin/make" "MAKEINFO=makeinfo --split-size=5000000 --split-size=5000000  " "PICFLAG=" "PICFLAG_FOR_TARGET=" "SHELL=/bin/sh" "RUNTESTFLAGS=" "exec_prefix=/usr/local/Cellar/gcc48/4.8.4" "infodir=/usr/local/Cellar/gcc48/4.8.4/share/info" "libdir=/usr/local/Cellar/gcc48/4.8.4/lib/gcc/4.8" "prefix=/usr/local/Cellar/gcc48/4.8.4" "includedir=/usr/local/Cellar/gcc48/4.8.4/include" "AR=ar" "AS=/private/tmp/gcc4820151129-326-1loboe/gcc-4.8.4/build/./gcc/as" "LD=/private/tmp/gcc4820151129-326-1loboe/gcc-4.8.4/build/./gcc/collect-ld" "LIBCFLAGS=-g -O2  -m32" "NM=/private/tmp/gcc4820151129-326-1loboe/gcc-4.8.4/build/./gcc/nm" "PICFLAG=" "RANLIB=ranlib" "DESTDIR=" DO=all multi-do # /usr/bin/make
    /usr/bin/make "DESTDIR=" "RPATH_ENVVAR=DYLD_LIBRARY_PATH" "TARGET_SUBDIR=x86_64-apple-darwin10.8.0" "bindir=/usr/local/Cellar/gcc48/4.8.4/bin" "datadir=/usr/local/Cellar/gcc48/4.8.4/share" "exec_prefix=/usr/local/Cellar/gcc48/4.8.4" "includedir=/usr/local/Cellar/gcc48/4.8.4/include" "datarootdir=/usr/local/Cellar/gcc48/4.8.4/share" "docdir=/usr/local/Cellar/gcc48/4.8.4/share/doc/" "infodir=/usr/local/Cellar/gcc48/4.8.4/share/info" "pdfdir=/usr/local/Cellar/gcc48/4.8.4/share/doc/" "htmldir=/usr/local/Cellar/gcc48/4.8.4/share/doc/" "libdir=/usr/local/Cellar/gcc48/4.8.4/lib/gcc/4.8" "libexecdir=/usr/local/Cellar/gcc48/4.8.4/libexec" "lispdir=" "localstatedir=/usr/local/Cellar/gcc48/4.8.4/var" "mandir=/usr/local/Cellar/gcc48/4.8.4/share/man" "oldincludedir=/usr/include" "prefix=/usr/local/Cellar/gcc48/4.8.4" "sbindir=/usr/local/Cellar/gcc48/4.8.4/sbin" "sharedstatedir=/usr/local/Cellar/gcc48/4.8.4/com" "sysconfdir=/usr/local/Cellar/gcc48/4.8.4/etc" "tooldir=/usr/local/Cellar/gcc48/4.8.4/x86_64-apple-darwin10.8.0" "build_tooldir=/usr/local/Cellar/gcc48/4.8.4/x86_64-apple-darwin10.8.0" "target_alias=x86_64-apple-darwin10.8.0" "AWK=awk" "BISON=bison" "CC_FOR_BUILD=clang" "CFLAGS_FOR_BUILD=-g -O2" "CXX_FOR_BUILD=clang++" "EXPECT=expect" "FLEX=flex" "INSTALL=/usr/bin/install -c" "INSTALL_DATA=/usr/bin/install -c -m 644" "INSTALL_PROGRAM=/usr/bin/install -c" "INSTALL_SCRIPT=/usr/bin/install -c" "LDFLAGS_FOR_BUILD=" "LEX=flex" "M4=gm4" "MAKE=/usr/bin/make" "RUNTEST=runtest" "RUNTESTFLAGS=" "SED=/usr/local/Library/ENV/4.3/sed" "SHELL=/bin/sh" "YACC=bison -y" "`echo 'ADAFLAGS=' | sed -e s'/[^=][^=]*=$/XFOO=/'`" "ADA_CFLAGS=" "AR_FLAGS=rc" "`echo 'BOOT_ADAFLAGS=-gnatpg' | sed -e s'/[^=][^=]*=$/XFOO=/'`" "BOOT_CFLAGS=-g -O2 -mdynamic-no-pic" "BOOT_LDFLAGS=" "CFLAGS=-g -O2" "CXXFLAGS=-g -O2" "LDFLAGS=" "LIBCFLAGS=-g -O2" "LIBCXXFLAGS=-g -O2 -fno-implicit-templates" "STAGE1_CHECKING=--enable-checking=yes" "STAGE1_LANGUAGES=c,c++,lto" "GNATBIND=no" "GNATMAKE=no" "AR_FOR_TARGET=ar" "AS_FOR_TARGET=as" "CC_FOR_TARGET=/private/tmp/gcc4820151129-326-1loboe/gcc-4.8.4/build/./gcc/xgcc -B/private/tmp/gcc4820151129-326-1loboe/gcc-4.8.4/build/./gcc/" "CFLAGS_FOR_TARGET=-g -O2" "CPPFLAGS_FOR_TARGET=" "CXXFLAGS_FOR_TARGET=-g -O2" "DLLTOOL_FOR_TARGET=dlltool" "FLAGS_FOR_TARGET=-B/usr/local/Cellar/gcc48/4.8.4/x86_64-apple-darwin10.8.0/bin/ -B/usr/local/Cellar/gcc48/4.8.4/x86_64-apple-darwin10.8.0/lib/ -isystem /usr/local/Cellar/gcc48/4.8.4/x86_64-apple-darwin10.8.0/include -isystem /usr/local/Cellar/gcc48/4.8.4/x86_64-apple-darwin10.8.0/sys-include" "GCJ_FOR_TARGET=" "GFORTRAN_FOR_TARGET=" "GOC_FOR_TARGET=" "GOCFLAGS_FOR_TARGET=-O2 -g" "LD_FOR_TARGET=/usr/bin/ld" "LIPO_FOR_TARGET=lipo" "LDFLAGS_FOR_TARGET=" "LIBCFLAGS_FOR_TARGET=-g -O2" "LIBCXXFLAGS_FOR_TARGET=-g -O2 -fno-implicit-templates" "NM_FOR_TARGET=nm" "OBJDUMP_FOR_TARGET=objdump" "RANLIB_FOR_TARGET=ranlib" "READELF_FOR_TARGET=readelf" "STRIP_FOR_TARGET=strip" "WINDRES_FOR_TARGET=windres" "WINDMC_FOR_TARGET=windmc" "BUILD_CONFIG=bootstrap-debug" "`echo 'LANGUAGES=' | sed -e s'/[^=][^=]*=$/XFOO=/'`" "LEAN=false" "STAGE1_CFLAGS=-g" "STAGE1_CXXFLAGS=-g" "STAGE1_TFLAGS=" "STAGE2_CFLAGS=-g -O2 -mdynamic-no-pic -gtoggle" "STAGE2_CXXFLAGS=-g -O2 -mdynamic-no-pic -gtoggle" "STAGE2_TFLAGS=" "STAGE3_CFLAGS=-g -O2 -mdynamic-no-pic" "STAGE3_CXXFLAGS=-g -O2 -mdynamic-no-pic" "STAGE3_TFLAGS=" "STAGE4_CFLAGS=-g -O2 -mdynamic-no-pic" "STAGE4_CXXFLAGS=-g -O2 -mdynamic-no-pic" "STAGE4_TFLAGS=" "STAGEprofile_CFLAGS=-g -O2 -mdynamic-no-pic -gtoggle -fprofile-generate" "STAGEprofile_CXXFLAGS=-g -O2 -mdynamic-no-pic -gtoggle -fprofile-generate" "STAGEprofile_TFLAGS=" "STAGEfeedback_CFLAGS=-g -O2 -mdynamic-no-pic -fprofile-use" "STAGEfeedback_CXXFLAGS=-g -O2 -mdynamic-no-pic -fprofile-use" "STAGEfeedback_TFLAGS=" "CXX_FOR_TARGET= $r/./gcc/xg++ -B$r/./gcc/ -nostdinc++ `if test -f $r/x86_64-apple-darwin10.8.0/libstdc++-v3/scripts/testsuite_flags; then /bin/sh $r/x86_64-apple-darwin10.8.0/libstdc++-v3/scripts/testsuite_flags --build-includes; else echo -funconfigured-libstdc++-v3 ; fi` -L$r/x86_64-apple-darwin10.8.0/libstdc++-v3/src -L$r/x86_64-apple-darwin10.8.0/libstdc++-v3/src/.libs" "TFLAGS=" "CONFIG_SHELL=/bin/sh" "MAKEINFO=makeinfo --split-size=5000000 --split-size=5000000"  compare
    rm -f stage_current
    Comparing stages 2 and 3
    warning: gcc/cc1-checksum.o differs
    warning: gcc/cc1obj-checksum.o differs
    warning: gcc/cc1objplus-checksum.o differs
    warning: gcc/cc1plus-checksum.o differs
    Bootstrap comparison failure!
    gcc/omega.o differs
    gcc/reg-stack.o differs
    gcc/reload.o differs
    make[2]: *** [compare] Error 1
    make[1]: *** [stage3-bubble] Error 2
    make: *** [bootstrap] Error 2
    
    READ THIS: https://git.io/brew-troubleshooting
    If reporting this issue please do so at (not Homebrew/homebrew):
      https://github.com/homebrew/homebrew-versions/issues

**Comment by mistydemeo** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Can you read this and provide the requested diagnostics? Thanks!

**Comment by sentient06** [comment]
gian@Tyr:~ $ brew update
    Already up-to-date.
    gian@Tyr:~ $ brew doctor
    Your system is ready to brew.
    gian@Tyr:~ $ ls -alp /usr/local
    total 104
    drwxrwxr-x  20 root  admin    680 30 Nov 19:23 ./
    drwxr-xr-x@ 14 root  wheel    476 11 Apr  2015 ../
    drwxr-xr-x  14 gian  admin    476 30 Nov 21:49 .git/
    -rw-r--r--   1 gian  admin    462 26 Nov 19:14 .gitignore
    -rw-r--r--   1 gian  admin   1331 30 Nov 19:23 .travis.yml
    -rw-r--r--   1 gian  admin    291 26 Nov 19:14 .yardopts
    -rw-r--r--   1 gian  admin   3161 26 Nov 19:14 CODEOFCONDUCT.md
    -rw-r--r--   1 gian  admin   1217 26 Nov 19:14 CONTRIBUTING.md
    drwxr-xr-x  29 gian  admin    986 30 Nov 21:31 Cellar/
    drwxr-xr-x   3 gian  admin    102 11 Apr  2015 Frameworks/
    -rw-r--r--   1 gian  admin   1241 11 Apr  2015 LICENSE.txt
    drwxr-xr-x  11 gian  admin    374 26 Nov 20:36 Library/
    -rw-r--r--   1 gian  admin   2246 26 Nov 19:14 README.md
    -rw-r--r--   1 gian  admin  23867 26 Nov 19:14 SUPPORTERS.md
    drwxr-xr-x  94 gian  admin   3196 29 Nov 14:04 bin/
    drwxr-xr-x   4 gian  admin    136 11 Apr  2015 etc/
    drwxr-xr-x  23 gian  admin    782 29 Nov 14:04 include/
    drwxr-xr-x  61 gian  admin   2074 29 Nov 14:04 lib/
    drwxr-xr-x  29 gian  admin    986 29 Nov 14:09 opt/
    drwxr-xr-x  14 gian  admin    476 29 Nov 14:04 share/
    gian@Tyr:~ $ which gcc
    /usr/bin/gcc
    gian@Tyr:~ $ which g++
    /usr/bin/g++
    gian@Tyr:~ $ gcc --version
i686-apple-darwin10-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.1.00)
    Copyright (C) 2007 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    
    gian@Tyr:~ $ g++ version
    i686-apple-darwin10-llvm-g++-4.2: version: No such file or directory
    i686-apple-darwin10-llvm-g++-4.2: no input files
    gian@Tyr:~ $
    gian@Tyr:~ $

Also, I use 64-bit libraries. I don't know how relevant that might be.

**Comment by mistydemeo** [comment]
Can you please run `brew gist-logs gcc48`?

**Comment by sentient06** [comment]
Sure. Running... it's taking a while.

**Comment by sentient06** [comment]
https://gist.github.com/94520b32e3a37aaf1c0b

**Comment by mistydemeo** [comment]
It looks like it's trying to build using Xcode 4.2's clang. What happens if you do `brew install gcc48 --cc=gcc-4.2`?

**Comment by sentient06** [comment]
Running it. Time for a tea. xD

**Comment by sentient06** [comment]
It was actually pretty fast.

    gian@Tyr:~ $ brew install gcc48 --cc=gcc-4.2
    ==> Installing gcc48 from homebrew/homebrew-versions
    ==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.8.4/gcc-4.8.4.tar.bz2
    Already downloaded: /Library/Caches/Homebrew/gcc48-4.8.4.tar.bz2
    ==> ../configure --build=x86_64-apple-darwin10.8.0 --prefix=/usr/local/Cellar/gc
    Last 15 lines from /Volumes/Data/10.6/Users/gian/Library/Logs/Homebrew/gcc48/01.configure:
    checking whether ln works... yes
    checking whether ln -s works... yes
    checking for a sed that does not truncate output... /usr/local/Library/ENV/4.3/sed
    checking for gawk... no
    checking for mawk... no
    checking for nawk... no
    checking for awk... awk
    checking for libatomic support... yes
    checking for libitm support... yes
    checking for libsanitizer support... yes
    checking for gcc... gcc-4.2
    checking for C compiler default output file name...
    configure: error: in `/private/tmp/gcc4820151130-84291-1v3iieg/gcc-4.8.4/build':
    configure: error: C compiler cannot create executables
    See `config.log' for more details.
    
    READ THIS: https://git.io/brew-troubleshooting
    If reporting this issue please do so at (not Homebrew/homebrew):
    https://github.com/homebrew/homebrew-versions/issues
    
    gian@Tyr:~ $

**Comment by mistydemeo** [comment]
Can I get a new set of logs from `brew gist-logs` please?

**Comment by sentient06** [comment]
Yes, running it.

**Comment by sentient06** [comment]
https://gist.github.com/6248a9689894886c5f42

**Comment by mistydemeo** [comment]
Looks like it didn't grab the `config.log`. Do you mind running `brew install gcc48 --cc=gcc-4.2 -d`, dropping into a shell, and locating that file? If you upload it to gist.github.com I'll take a look.

**Comment by sentient06** [comment]
Okie, I'm on it!

**Comment by sentient06** [comment]
https://gist.github.com/sentient06/a95d869b03d9916f6658

**Comment by mistydemeo** [comment]
Yes, thank you!

`gcc-4.2` printed this message:

```
Xcode and/or the CLT appear to be misconfigured. Try one or both of the following:
  xcodebuild -license
  sudo xcode-select -switch /path/to/Xcode.app
```

Can you try those two steps and see if that helps? This happened because Homebrew's `gcc-4.2` shim failed to launch the actual compiler. Xcode 4.2 did include GCC 4.2, so it should be able to work.

**Comment by mistydemeo** [comment]
Given you're on Xcode 4.2, you probably want to try `sudo xcode-select -switch /Developer`, unless your Xcode developer dir is in another location.

**Comment by sentient06** [comment]
gian@Tyr:~ $ xcodebuild -license
    xcodebuild: error: invalid option '-license'
Trying second cmd..

**Comment by sentient06** [comment]
Alright, I did `sudo xcode-select -switch /Developer` and yes, my XCode is in that path.

Then I tried again:

    gian@Tyr:~ $ xcode-select -print-path
    /Developer
    gian@Tyr:~ $ brew install gcc48
    ==> Installing gcc48 from homebrew/homebrew-versions
    ==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.8.4/gcc-4.8.4.tar.bz2
    Already downloaded: /Library/Caches/Homebrew/gcc48-4.8.4.tar.bz2
    ==> ../configure --build=x86_64-apple-darwin10.8.0 --prefix=/usr/local/Cellar/gc
    ==> make bootstrap
    Last 15 lines from /Volumes/Data/10.6/Users/gian/Library/Logs/Homebrew/gcc48/02.make:
    true "AR_FLAGS=rc" "CC_FOR_BUILD=clang" "CFLAGS=-g -O2  -m32" "CXXFLAGS=-g -O2  -m32" "CFLAGS_FOR_BUILD=-g -O2" "CFLAGS_FOR_TARGET=-g -O2" "INSTALL=/usr/bin/install -c" "INSTALL_DATA=/usr/bin/install -c -m 644" "INSTALL_PROGRAM=/usr/bin/install -c" "INSTALL_SCRIPT=/usr/bin/install -c" "JC1FLAGS=" "LDFLAGS=-m32" "LIBCFLAGS=-g -O2  -m32" "LIBCFLAGS_FOR_TARGET=-g -O2" "MAKE=/usr/bin/make" "MAKEINFO=makeinfo --split-size=5000000 --split-size=5000000  " "PICFLAG=" "PICFLAG_FOR_TARGET=" "SHELL=/bin/sh" "RUNTESTFLAGS=" "exec_prefix=/usr/local/Cellar/gcc48/4.8.4" "infodir=/usr/local/Cellar/gcc48/4.8.4/share/info" "libdir=/usr/local/Cellar/gcc48/4.8.4/lib/gcc/4.8" "prefix=/usr/local/Cellar/gcc48/4.8.4" "includedir=/usr/local/Cellar/gcc48/4.8.4/include" "AR=ar" "AS=/private/tmp/gcc4820151130-86542-1va7p20/gcc-4.8.4/build/./gcc/as" "LD=/private/tmp/gcc4820151130-86542-1va7p20/gcc-4.8.4/build/./gcc/collect-ld" "LIBCFLAGS=-g -O2  -m32" "NM=/private/tmp/gcc4820151130-86542-1va7p20/gcc-4.8.4/build/./gcc/nm" "PICFLAG=" "RANLIB=ranlib" "DESTDIR=" DO=all multi-do # /usr/bin/make
    /usr/bin/make "DESTDIR=" "RPATH_ENVVAR=DYLD_LIBRARY_PATH" "TARGET_SUBDIR=x86_64-apple-darwin10.8.0" "bindir=/usr/local/Cellar/gcc48/4.8.4/bin" "datadir=/usr/local/Cellar/gcc48/4.8.4/share" "exec_prefix=/usr/local/Cellar/gcc48/4.8.4" "includedir=/usr/local/Cellar/gcc48/4.8.4/include" "datarootdir=/usr/local/Cellar/gcc48/4.8.4/share" "docdir=/usr/local/Cellar/gcc48/4.8.4/share/doc/" "infodir=/usr/local/Cellar/gcc48/4.8.4/share/info" "pdfdir=/usr/local/Cellar/gcc48/4.8.4/share/doc/" "htmldir=/usr/local/Cellar/gcc48/4.8.4/share/doc/" "libdir=/usr/local/Cellar/gcc48/4.8.4/lib/gcc/4.8" "libexecdir=/usr/local/Cellar/gcc48/4.8.4/libexec" "lispdir=" "localstatedir=/usr/local/Cellar/gcc48/4.8.4/var" "mandir=/usr/local/Cellar/gcc48/4.8.4/share/man" "oldincludedir=/usr/include" "prefix=/usr/local/Cellar/gcc48/4.8.4" "sbindir=/usr/local/Cellar/gcc48/4.8.4/sbin" "sharedstatedir=/usr/local/Cellar/gcc48/4.8.4/com" "sysconfdir=/usr/local/Cellar/gcc48/4.8.4/etc" "tooldir=/usr/local/Cellar/gcc48/4.8.4/x86_64-apple-darwin10.8.0" "build_tooldir=/usr/local/Cellar/gcc48/4.8.4/x86_64-apple-darwin10.8.0" "target_alias=x86_64-apple-darwin10.8.0" "AWK=awk" "BISON=bison" "CC_FOR_BUILD=clang" "CFLAGS_FOR_BUILD=-g -O2" "CXX_FOR_BUILD=clang++" "EXPECT=expect" "FLEX=flex" "INSTALL=/usr/bin/install -c" "INSTALL_DATA=/usr/bin/install -c -m 644" "INSTALL_PROGRAM=/usr/bin/install -c" "INSTALL_SCRIPT=/usr/bin/install -c" "LDFLAGS_FOR_BUILD=" "LEX=flex" "M4=gm4" "MAKE=/usr/bin/make" "RUNTEST=runtest" "RUNTESTFLAGS=" "SED=/usr/local/Library/ENV/4.3/sed" "SHELL=/bin/sh" "YACC=bison -y" "`echo 'ADAFLAGS=' | sed -e s'/[^=][^=]*=$/XFOO=/'`" "ADA_CFLAGS=" "AR_FLAGS=rc" "`echo 'BOOT_ADAFLAGS=-gnatpg' | sed -e s'/[^=][^=]*=$/XFOO=/'`" "BOOT_CFLAGS=-g -O2 -mdynamic-no-pic" "BOOT_LDFLAGS=" "CFLAGS=-g -O2" "CXXFLAGS=-g -O2" "LDFLAGS=" "LIBCFLAGS=-g -O2" "LIBCXXFLAGS=-g -O2 -fno-implicit-templates" "STAGE1_CHECKING=--enable-checking=yes" "STAGE1_LANGUAGES=c,c++,lto" "GNATBIND=no" "GNATMAKE=no" "AR_FOR_TARGET=ar" "AS_FOR_TARGET=as" "CC_FOR_TARGET=/private/tmp/gcc4820151130-86542-1va7p20/gcc-4.8.4/build/./gcc/xgcc -B/private/tmp/gcc4820151130-86542-1va7p20/gcc-4.8.4/build/./gcc/" "CFLAGS_FOR_TARGET=-g -O2" "CPPFLAGS_FOR_TARGET=" "CXXFLAGS_FOR_TARGET=-g -O2" "DLLTOOL_FOR_TARGET=dlltool" "FLAGS_FOR_TARGET=-B/usr/local/Cellar/gcc48/4.8.4/x86_64-apple-darwin10.8.0/bin/ -B/usr/local/Cellar/gcc48/4.8.4/x86_64-apple-darwin10.8.0/lib/ -isystem /usr/local/Cellar/gcc48/4.8.4/x86_64-apple-darwin10.8.0/include -isystem /usr/local/Cellar/gcc48/4.8.4/x86_64-apple-darwin10.8.0/sys-include" "GCJ_FOR_TARGET=" "GFORTRAN_FOR_TARGET=" "GOC_FOR_TARGET=" "GOCFLAGS_FOR_TARGET=-O2 -g" "LD_FOR_TARGET=/usr/bin/ld" "LIPO_FOR_TARGET=lipo" "LDFLAGS_FOR_TARGET=" "LIBCFLAGS_FOR_TARGET=-g -O2" "LIBCXXFLAGS_FOR_TARGET=-g -O2 -fno-implicit-templates" "NM_FOR_TARGET=nm" "OBJDUMP_FOR_TARGET=objdump" "RANLIB_FOR_TARGET=ranlib" "READELF_FOR_TARGET=readelf" "STRIP_FOR_TARGET=strip" "WINDRES_FOR_TARGET=windres" "WINDMC_FOR_TARGET=windmc" "BUILD_CONFIG=bootstrap-debug" "`echo 'LANGUAGES=' | sed -e s'/[^=][^=]*=$/XFOO=/'`" "LEAN=false" "STAGE1_CFLAGS=-g" "STAGE1_CXXFLAGS=-g" "STAGE1_TFLAGS=" "STAGE2_CFLAGS=-g -O2 -mdynamic-no-pic -gtoggle" "STAGE2_CXXFLAGS=-g -O2 -mdynamic-no-pic -gtoggle" "STAGE2_TFLAGS=" "STAGE3_CFLAGS=-g -O2 -mdynamic-no-pic" "STAGE3_CXXFLAGS=-g -O2 -mdynamic-no-pic" "STAGE3_TFLAGS=" "STAGE4_CFLAGS=-g -O2 -mdynamic-no-pic" "STAGE4_CXXFLAGS=-g -O2 -mdynamic-no-pic" "STAGE4_TFLAGS=" "STAGEprofile_CFLAGS=-g -O2 -mdynamic-no-pic -gtoggle -fprofile-generate" "STAGEprofile_CXXFLAGS=-g -O2 -mdynamic-no-pic -gtoggle -fprofile-generate" "STAGEprofile_TFLAGS=" "STAGEfeedback_CFLAGS=-g -O2 -mdynamic-no-pic -fprofile-use" "STAGEfeedback_CXXFLAGS=-g -O2 -mdynamic-no-pic -fprofile-use" "STAGEfeedback_TFLAGS=" "CXX_FOR_TARGET= $r/./gcc/xg++ -B$r/./gcc/ -nostdinc++ `if test -f $r/x86_64-apple-darwin10.8.0/libstdc++-v3/scripts/testsuite_flags; then /bin/sh $r/x86_64-apple-darwin10.8.0/libstdc++-v3/scripts/testsuite_flags --build-includes; else echo -funconfigured-libstdc++-v3 ; fi` -L$r/x86_64-apple-darwin10.8.0/libstdc++-v3/src -L$r/x86_64-apple-darwin10.8.0/libstdc++-v3/src/.libs" "TFLAGS=" "CONFIG_SHELL=/bin/sh" "MAKEINFO=makeinfo --split-size=5000000 --split-size=5000000"  compare
    rm -f stage_current
    Comparing stages 2 and 3
    warning: gcc/cc1-checksum.o differs
    warning: gcc/cc1obj-checksum.o differs
    warning: gcc/cc1objplus-checksum.o differs
    warning: gcc/cc1plus-checksum.o differs
    Bootstrap comparison failure!
    gcc/omega.o differs
    gcc/reg-stack.o differs
    gcc/reload.o differs
    make[2]: *** [compare] Error 1
    make[1]: *** [stage3-bubble] Error 2
    make: *** [bootstrap] Error 2
    
    READ THIS: https://git.io/brew-troubleshooting
    If reporting this issue please do so at (not Homebrew/homebrew):
      https://github.com/homebrew/homebrew-versions/issues
    
    gian@Tyr:~ $

![Oh, come on!](http://memeguy.com/photos/thumbs/mrw-my-pc-parts-arrive-in-my-hometown-friday-but-wont-be-delivered-till-monday-157009.gif)

**Comment by mistydemeo** [comment]
Sorry, when you reinstall can you do that with `brew install gcc48 --cc=gcc-4.2`?

What happens if you do `gcc-4.2 --version`? What is the output of `which gcc-4.2`?

**Comment by sentient06** [comment]
`gcc-4.2` is not available, only plain `gcc`:

    Last login: Mon Nov 30 23:13:48 on ttys001
    gian@Tyr:~ $ gcc-4.2 --version
    -bash: gcc-4.2: command not found
    gian@Tyr:~ $ which gcc-4.2
    gian@Tyr:~ $ gcc --version
    i686-apple-darwin10-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.1.00)
    Copyright (C) 2007 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    
    gian@Tyr:~ $ which gcc
    /usr/bin/gcc
    gian@Tyr:~ $

Is it supposed to be gcc-4.2?

**Comment by mistydemeo** [comment]
Your `gcc` is Apple's `llvm-gcc`, rather than the "real" `gcc-4.2`. I misread your `brew --config`; it does appear you're missing `gcc-4.2`, which I had forgotten was not available in Xcode 4.2.

Unfortunately we don't support Xcode 4.2 on Snow Leopard very well. It wasn't a publicly-available release, so the Homebrew devs don't have access to it. As well, since it has only llvm-gcc and not gcc-4.2, not everything builds quite as well. You have a couple options here:

* Try `brew install gcc48 --cc=llvm-gcc`, which may work.
* Remove Xcode 4.2 and install Xcode 3.2.6.

**Comment by sentient06** [comment]
I have XCode 3.2.6. It lives in a different dir: `/XCode3`. =D

**Comment by sentient06** [comment]
So, what if I do...

    gian@Tyr:~ $ sudo xcode-select -switch /XCode3/
    Password:
    gian@Tyr:~ $ xcode-select -print-path
    /XCode3
    gian@Tyr:~ $ which gcc
    /usr/bin/gcc
    gian@Tyr:~ $ gcc --version
    i686-apple-darwin10-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.1.00)
    Copyright (C) 2007 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    gian@Tyr:~ $

That supposedly work.. right?

**Comment by sentient06** [comment]
Well.. gcc is the same, it seems..

**Comment by mistydemeo** [comment]
That changes your Xcode path, but not the compilers in `/usr/bin`. Before OS X 10.9, the "Command Line Tools" package from Xcode installed its compilers right into `/usr/bin`, so your Xcode 4.2 install dropped its versions of the tools in there instead of Xcode 3.2.6's.

**Comment by mistydemeo** [comment]
It *may* work after doing the `xcode-select`; you can try `brew install gcc48 --cc=gcc-4.2` to see!

**Comment by sentient06** [comment]
I checked my XCode 3, it works fine and I can choose my compiler!

So I checked the `bin` dir and got this:

    gian@Tyr:bin $ pwd
    /XCode3/usr/bin
    gian@Tyr:bin $ ./cpp-4.2 --version
    i686-apple-darwin10-cpp-4.2.1 (GCC) 4.2.1 (Apple Inc. build 5666) (dot 3)
    Copyright (C) 2007 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    
    gian@Tyr:bin $

**Comment by sentient06** [comment]
Is it possible to force homebrew to use another binary?

**Comment by sentient06** [comment]
I am trying to use `brew install gcc48 --cc=gcc-4.2` again with the `xcode-select` pointing to XCode 3. I foresee it will take a while, so I'll check the results tomorrow (almost 0h in the old world now). Thank you for the help!

**Comment by sentient06** [comment]
It seems it worked!

    gian@Tyr:~ $ brew install gcc48 --cc=gcc-4.2
    ==> Installing gcc48 from homebrew/homebrew-versions
    ==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.8.4/gcc-4.8.4.tar.bz2
    Already downloaded: /Library/Caches/Homebrew/gcc48-4.8.4.tar.bz2
    ==> ../configure --build=x86_64-apple-darwin10.8.0 --prefix=/usr/local/Cellar/gcc48/4.8.4 --libdir=/usr/loca
    ==> make bootstrap
    ==> make install
    /usr/local/Cellar/gcc48/4.8.4: 1027 files, 142M, built in 19.8 minutes
    gian@Tyr:~ $ which gcc
    /usr/bin/gcc
    gian@Tyr:~ $ which gcc-4.8
    /usr/local/bin/gcc-4.8
    gian@Tyr:~ $ gcc-4.8 --version
    gcc-4.8 (Homebrew gcc48 4.8.4) 4.8.4
    Copyright (C) 2013 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    
    gian@Tyr:~ $

Thank you for everything! All the best!

**Comment by DomT4** [comment]
Closing per the resolution above. Aren't compilers *fun*?
