### ISSUE TITLE
brew install llvm36 fails: <stdin>:1:10: fatal error: 'cxxabi.h' file not found

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/homebrew-versions#1052]
after brew update, I did 'brew install llvm36' it fails:
==> Installing llvm36 from homebrew/homebrew-versions
==> Downloading http://llvm.org/releases/3.6.2/llvm-3.6.2.src.tar.xz
Already downloaded: /Library/Caches/Homebrew/llvm36-3.6.2.tar.xz
==> Patching
patching file Makefile.rules
Hunk #1 succeeded at 598 (offset -1 lines).
==> Downloading http://llvm.org/releases/3.6.2/cfe-3.6.2.src.tar.xz
Already downloaded: /Library/Caches/Homebrew/llvm36--clang-3.6.2.tar.xz
==> Downloading http://llvm.org/releases/3.6.2/libcxx-3.6.2.src.tar.xz
Already downloaded: /Library/Caches/Homebrew/llvm36--libcxx-3.6.2.tar.xz
==> Downloading http://llvm.org/releases/3.6.2/polly-3.6.2.src.tar.xz
Already downloaded: /Library/Caches/Homebrew/llvm36--polly-3.6.2.tar.xz
==> Downloading http://llvm.org/releases/3.6.2/clang-tools-extra-3.6.2.src.tar.xz
Already downloaded: /Library/Caches/Homebrew/llvm36--clang-tools-extra-3.6.2.tar.xz
==> Downloading http://isl.gforge.inria.fr/isl-0.14.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/llvm36--isl-0.14.1.tar.gz
==> ./configure --disable-silent-rules --prefix=/Users/timothee/homebrew/Cellar/llvm36/3.6.2/lib/llvm-3.6/libexec/isl --with-gmp=system --with-gmp-prefix=/Users/timothee/homebrew/o
==> make
==> make install
==> ./configure --prefix=/Users/timothee/homebrew/Cellar/llvm36/3.6.2/lib/llvm-3.6 --enable-optimized --disable-bindings --with-gmp=/Users/timothee/homebrew/opt/gmp --with-isl=/Use
==> make VERBOSE=1
==> make VERBOSE=1 install
==> make -C /private/tmp/llvm3620151130-9796-10exzf2/llvm-3.6.2.src/projects/libcxx install CC=/Users/timothee/homebrew/Cellar/llvm36/3.6.2/lib/llvm-3.6/bin/clang CXX=/Users/timoth
Last 15 lines from /Users/timothee/Library/Logs/Homebrew/llvm36/07.make:

cd lib && ./buildit
<stdin>:1:10: fatal error: 'cxxabi.h' file not found
#include <cxxabi.h>
         ^
1 error generated.
+ for FILE in '../src/*.cpp'
+ /Users/timothee/homebrew/Cellar/llvm36/3.6.2/lib/llvm-3.6/bin/clang++ -c -g -Os -arch i386 -arch x86_64 -nostdinc++ -std=c++11 -fstrict-aliasing -Wall -Wextra -Wshadow -Wconversion -Wpadded -Wstrict-aliasing=2 -Wstrict-overflow=4 -I../include ../src/algorithm.cpp
In file included from ../src/algorithm.cpp:10:
In file included from ../include/algorithm:623:
../include/__config:23:10: fatal error: 'unistd.h' file not found
#include <unistd.h>
         ^
1 error generated.
make: *** [install] Error 1

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by timotheecour** [comment]
installing command line tools osx 10.11 for xcode 7.2 beta 2 and then rerunning ''brew install llvm36' now worked!
[would be nice to have the scripts check for this though]
