### ISSUE TITLE
bash-completions2 no longer completing ssh hosts from known_hosts

### ISSUE THREAD

**Issue by jarshwah** [Homebrew/homebrew-versions#1063]
Since I removed bash-completions and installed bash-completions2, it seems I can no longer auto complete hostnames from my `~/.ssh/known_hosts` file. If I manually source the ssh completion script though it works fine. I'm unsure if there are other completions that are not working fine or not.

The ssh completer (without being manually source) still completes hostnames from my ssh config file, and all the regular commands and switches.

This is from my bash_profile:

```
# install brew bash_completions
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    source $(brew --prefix)/etc/bash_completion
fi
if [ -f $(brew --prefix)/Library/Contributions/brew_bash_completion.sh ]; then
    source $(brew --prefix)/Library/Contributions/brew_bash_completion.sh
fi
if [ -f $(brew --prefix)/share/bash-completion/bash_completion ]; then
    source $(brew --prefix)/share/bash-completion/bash_completion
fi
```

I've tried commenting out the first two sources of completions, and no improvement.

Versions:

```
smeatonj /usr/local/share/bash-completion/completions (master) [$]
$ ls -la ssh
lrwxr-xr-x 1 smeatonj admin 76 Dec  4 12:02 ssh -> ../../../Cellar/bash-completion2/2.1_2/share/bash-completion/completions/ssh

$ brew --version
0.9.5 (git revision 12f42a; last commit 2015-12-06)

$ bash --version
GNU bash, version 4.3.42(1)-release (x86_64-apple-darwin14.5.0)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ which bash
/usr/local/bin/bash

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your XQuartz (2.7.4) is outdated
Please install XQuartz 2.7.8:
  https://xquartz.macosforge.org

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: You have a curlrc file
If you have trouble downloading packages with Homebrew, then maybe this
is the problem? If the following command doesn't work, then try removing
your curlrc:
  curl https://github.com

**Comment by ssbarnea** [comment]
I faced the same problem and I am wondering how that I ended up installing the `bash-completions2` instead of the `bash-completions` in the first place? 

I tried to find some info online but failed to spot the differences.

**Comment by UniqMartin** [comment]
> Does this means that this version should be removed?

No. It really depends on whether you're using the Bash version provided by OS X (Bash 3.2.x) in which case you should be using `bash-completion` or whether you've installed Bash 4 (e.g. via the `bash` formula), in which case you should be using `homebrew/versions/bash-completion2` (this formula).

**Comment by jarshwah** [comment]
For what it's worth I discovered that an alias I had (it might have been named ssh) was interfering with the completion. Removing that alias sorted the issue.
