### ISSUE TITLE
play12 SHA changed

### ISSUE THREAD

**Issue by cletusw** [Homebrew/homebrew-versions#1067]
It looks like the SHA256 for play12 changed from [`4fc610e2db0993fee3daf01527ba5ca57a9ad970c429733415ee59b55064b322`](https://github.com/Homebrew/homebrew-versions/blob/93700f36c48c5b256b5abc991160636f62ba52d1/play12.rb#L4) to `bdf4422b235553c36161ba85512ad17a25b5f5974179b28caccccdc82e9dfc22`. I have no idea why, but it's preventing `brew install play12` from working.
```
$ brew upgrade play12
==> Upgrading 1 outdated package, with result:
homebrew/versions/play12 1.2.7.2
==> Upgrading homebrew/versions/play12
==> Downloading http://downloads.typesafe.com/play/1.2.7.2/play-1.2.7.2.zip
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 4fc610e2db0993fee3daf01527ba5ca57a9ad970c429733415ee59b55064b322
Actual: bdf4422b235553c36161ba85512ad17a25b5f5974179b28caccccdc82e9dfc22
Archive: /Library/Caches/Homebrew/play12-1.2.7.2.zip
To retry an incomplete download, remove the file above.
```

**Comment by cletusw** [comment]
I'm on OS X 10.11.1 El Capitan

**Comment by dunn** [comment]
I see the same thing.  Would you mind asking the developers if they're aware of this change?

**Comment by uareurapid** [comment]
I have this too, what a pain

**Comment by dunn** [comment]
We're not going to update the SHA until we know it's not a malicious change.  If you can ask upstream about it that'd be great!

**Comment by uareurapid** [comment]
I think is due to version changes, if someone is interested i´ve found a working workaround
Just edit the file.
do:
brew edit play12

and replace the line
sha256 "4fc610e2db0993fee3daf01527ba5ca57a9ad970c429733415ee59b55064b322" 
by
sha256 "bdf4422b235553c36161ba85512ad17a25b5f5974179b28caccccdc82e9dfc22"

hope it helps

**Comment by mikemcquaid** [comment]
@uareurapid Or, they may have been hacked and if you install that you'll install malicious software. That's why we want to check.
