### ISSUE TITLE
gcc45 fails to build on Mac OS X 10.11.2

### ISSUE THREAD

**Issue by ahyattdev** [Homebrew/homebrew-versions#1093]
gcc45 fails to build on Mac OS X 10.11.2

configure: error: unsupported system, cannot find sizeof (omp_lock_t)
make[2]: *** [configure-stage1-target-libgomp] Error 1
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2

https://gist.github.com/ahyattdev/19cc744fb9f9d17362f6

**Comment by dunn** [comment]
> configure: error: unsupported system

That suggests it's simply too old to build on El Capitan.  If you want to ask the GCC developers if they'll consider releasing an updated 4.5.x that'd be great, but I'm afraid there's probably nothing we can do otherwise.

**Comment by ahyattdev** [comment]
Thank you for clarifying.

**Comment by pronvit** [comment]
I know it's too late but maybe it will help someone else.
Download Xcode6 and use `xcode-select -s` to switch to it. Also, if it's a clean installation of 10.11 (not upgrade), you'll need to do `cd /usr/local/lib && ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib`. Then you gcc45 will install successfully.
