### ISSUE TITLE
Rollback gtk+

### ISSUE THREAD

**Issue by johncraigfreeman** [Homebrew/homebrew-versions#1095]
Hello, the latest version of gtk+ 2.24.28 brakes the build for VisualSfM. Older versions seem to no longer be available. Is there some way to rollback gtk+ to 2.24.27 or earlier, which supports X11?

**Comment by mikemcquaid** [comment]
No, sorry. Please consider [creating your own tap](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md) instead and putting an old version of GTK there. Thanks!

**Comment by johncraigfreeman** [comment]
Thanks Mike, I would be happy to do this. The instructions for creating my own tap seem pretty straight forward, but I would not know how to go about changing the formula of the current version of gtk+ to support X11 backend in the first place. Could you send step-by-step instructions?

**Comment by DomT4** [comment]
Could `git checkout` Homebrew to the commit before the X11 support removal, copy as much of the GTK+ dependency tree as you require, move them over to the tap and then update your versions there to match the current.

**Comment by johncraigfreeman** [comment]
Thanks DomT4, how do I git checkout Homebrew to the commit before the X11 support removal?

**Comment by DomT4** [comment]
```
cd $(brew --prefix)
git checkout bb3fe5f2de87f76bc0a3f3480635c8fd0d68cec3
```
Copy as much as you need to, and then:
```
cd $(brew --prefix)
git checkout master
```

**Comment by johncraigfreeman** [comment]
fatal: reference is not a tree: bb3fe5f2de87f76bc0a3f3480635c8fd0d68cec3

**Comment by DomT4** [comment]
Hmm. Does `.git/shallow` exist inside your Homebrew prefix?

**Comment by mikemcquaid** [comment]
@johncraigfreeman You need to `cd /usr/local/Library/Taps/homebrew/homebrew-versions` first.
