### ISSUE TITLE
subversion16 incompatible with 10.11

### ISSUE THREAD

**Issue by FunTimeCoding** [Homebrew/homebrew-versions#1123]
It says its not compatible because OS X does not provide openssl files anymore. Wouldn't it be possible to use the brew openssl instead?

**Comment by DomT4** [comment]
No, It doesn't work against newer OpenSSL versions sadly. For this reason the Subversion formulae in this repo are likely going to be deprecated in the coming cleanup of the Versions tap.

**Comment by FunTimeCoding** [comment]
I see. Thanks.
