### ISSUE TITLE
mysql56 won't start on Mac OS X

### ISSUE THREAD

**Issue by vitaly-krugl** [Homebrew/homebrew-versions#1137]
Mac OS X El Capitan version 10.11.2

After installing mysql56, attempts to start it result in failure. See transcript below.

Additional info: I used to have a brew-installed mysql 5.6.23 that was installed prior to upgrading to El Capitan, and continued to work fine after El Capitan upgrade. While investigating an issue that was reproducible on mysql 5.7, I installed the latest mysql via brew, which was mysql 5.7.10. After this, I wanted to go back to mysql 5.6 and discovered mysql56 here in homebrew-versions. I uninstalled mysql 5.7.10 first, then installed mysql56 However, as you can see in the transcript below, I am unable to start mysql56 after installing it:

```bash
$ brew install mysql56
==> Installing mysql56 from homebrew/versions
==> Downloading https://homebrew.bintray.com/bottles-versions/mysql56-5.6.27.el_capitan.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/mysql56-5.6.27.el_capitan.bottle.tar.gz
==> Pouring mysql56-5.6.27.el_capitan.bottle.tar.gz
==> Caveats
A "/etc/my.cnf" from another install may interfere with a Homebrew-built
server starting up correctly.

To connect:
    mysql -uroot

To have launchd start homebrew/versions/mysql56 at login:
  ln -sfv /usr/local/opt/mysql56/*.plist ~/Library/LaunchAgents
Then to load homebrew/versions/mysql56 now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mysql56.plist
Or, if you don't want/need launchctl, you can just run:
  /usr/local/opt/mysql56/bin/mysql.server start
==> Summary
🍺  /usr/local/Cellar/mysql56/5.6.27: 9,883 files, 313.3M
vkruglikov@vkruglikovsmbp2:~/nta/numenta-apps/htm.it (fix-timestamp-default)$ 
vkruglikov@vkruglikovsmbp2:~/nta/numenta-apps/htm.it (fix-timestamp-default)$ 
vkruglikov@vkruglikovsmbp2:~/nta/numenta-apps/htm.it (fix-timestamp-default)$ 
vkruglikov@vkruglikovsmbp2:~/nta/numenta-apps/htm.it (fix-timestamp-default)$ 
vkruglikov@vkruglikovsmbp2:~/nta/numenta-apps/htm.it (fix-timestamp-default)$ launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mysql56.plist
/Users/vkruglikov/Library/LaunchAgents/homebrew.mxcl.mysql56.plist: No such file or directory
vkruglikov@vkruglikovsmbp2:~/nta/numenta-apps/htm.it (fix-timestamp-default)$ 
vkruglikov@vkruglikovsmbp2:~/nta/numenta-apps/htm.it (fix-timestamp-default)$ 
vkruglikov@vkruglikovsmbp2:~/nta/numenta-apps/htm.it (fix-timestamp-default)$ /usr/local/opt/mysql56/bin/mysql.server start
Starting MySQL
. ERROR! The server quit without updating PID file (/usr/local/var/mysql/vkruglikovsmbp2.corp.numenta.com.pid).
```

**Comment by mikemcquaid** [comment]
Run `mysqld` directly. I suspect your database was upgraded and you'll need to downgrade it manually.

**Comment by vitaly-krugl** [comment]
Thank you, @mikemcquaid, I think this was indeed the cause. Closing.

**Comment by travisdetert** [comment]
Honest question, the default install seems incredibly broken: why is this?  when it was the default install it worked perfectly.  What changes so drastically that it just stops working?  Either the permission on /usr/local/var/mysql, or it just won't start.  I'm not quite understanding what causes each release to have these issues?  Mysql57 is also not working.  I've completely removed brew, /usr/local/... and completely rebuilt the OS just be sure it wasn't me.  What gives?
