### ISSUE TITLE
Cassandra shell in cassandra22 formula failing to run queries

### ISSUE THREAD

**Issue by rgladwell** [Homebrew/homebrew-versions#1140]
The Python Cassandra shell in cassandra22 formula is failing with the following error message:

`'list' object has no attribute 'has_more_pages'`

This could be something to do with Python versions but Googling the above error message isn't 

Steps to reproduce:

 1. Run `brew install cassandra22`
 2. Run `cassandra` - wait for the server to start
 3. Run `cqlsh`
 4. Execute `use system;`
 5. Execute `select * from peers;`

Expected result: should successfully query table and return empty set or result set.

Actual result: error message `'list' object has no attribute 'has_more_pages'`

**Comment by DomT4** [comment]
Seems like a re-run of https://github.com/Homebrew/homebrew-versions/issues/1131. It was fixed but the revision not bumped, so try `brew update && brew reinstall cassandra22`.

**Comment by rgladwell** [comment]
@DomT4 Yes, that worked, cheers.
