### ISSUE TITLE
dirmngr isn’t working in GnuPG 2.1.11

### ISSUE THREAD

**Issue by jonnybarnes** [Homebrew/homebrew-versions#1143]
It may well be a config error on my side, but since updating to GnuPG 2.1.11 I get the following error:

```
$ gpg-connect-agent --dirmngr 'keyserver --hosttable' /bye
gpg-connect-agent: no running Dirmngr - starting '/usr/local/Cellar/gnupg21/2.1.11/bin/dirmngr'
gpg-connect-agent: waiting for the dirmngr to come up ... (5s)
gpg-connect-agent: connection to the dirmngr established
S # hosttable (idx, ipv6, ipv4, dead, name, time):
OK
$ gpg2 --refresh-keys
gpg: refreshing 8 keys from hkp://subset.pool.sks-keyservers.net
gpg: keyserver refresh failed: End of file
```

**Comment by mikemcquaid** [comment]
Can you reproduce this in the newest GnuPG or the same version built from source outside Homebrew? Thanks!

**Comment by jonnybarnes** [comment]
I first tried with `brew reinstall gngup21 --build-froms-ource` but the `make check` step failed!, gpgtar.test

Trying to build from source directly now.

**Comment by jonnybarnes** [comment]
All tests pass when I self-compile

**Comment by jonnybarnes** [comment]
Attemtping with brew again and the tests have passed *shrugs*

**Comment by jonnybarnes** [comment]
And dirmngr seems top be working again!

**Comment by DomT4** [comment]
The `gpgtar` issue seems to be known:

> Quoting Daniel Kahn Gillmor (2016-01-28 16:45:22)
> I've packaged gnupg 2.1.11 for debian and uploaded it to debian
> unstable.  however, i'm seeing intermittent failures in the gpgtar test
> suite.  Particularly, in tests/openpgp/gpgtar.test.  These are not
> reliable failures -- they just happen sometimes, frustratingly enough.

> I have also seen it fail every now and then.  I'll look into that.

> Justus
