### ISSUE TITLE
RVM: openssl098 missing (can't install ruby 1.8.7.p334)

### ISSUE THREAD

**Issue by bobweston** [Homebrew/homebrew-versions#1150]
I can't seem to compile ruby 1.8.7-p334 (using rvm). I'm getting errors saying that it is missing openssl098.

Before you ask, we have a few legacy applications that nee bare-bones maintenance. I still need to build this version of ruby.

I notice that openssl098 was removed Monday of last week. Was this intentional?

**Comment by DomT4** [comment]
Yes. Please read the [commit message](https://github.com/Homebrew/homebrew-versions/commit/4e169f22cc48e61e2ed6e2f80a5414fe281db335).

At last check Ruby 1.8.7 will compile and run against a modern OpenSSL; any specific reason you want it to build against the problematic unsupported 0.9.8 branch?

**Comment by mistydemeo** [comment]
It doesn't look like @bobweston particularly cares, but rvm is trying to build it against that specific OpenSSL.

Our ruby187 formula uses the current OpenSSL release, which works fine without patching. (In fact, the OpenSSL patches used by the ruby182 and ruby186 formulae come from 1.8.7!) Maybe the real answer is a PR to rvm to use a different openssl release for 1.8.7?

**Comment by DomT4** [comment]
Was just about to leave an Issue on the RVM GitHub repo. We've been warning this formulae would be removed after January 2016 for 6 months now.

**Comment by DomT4** [comment]
Filed https://github.com/rvm/rvm/issues/3618.

It looks like they're building against MacPorts' standard OpenSSL which would be 1.0.2f, so I'm not entirely sure why they're using the older 0.9.8 branch specifically for us.

**Comment by bobweston** [comment]
yeah. I was just hoping for a way to get this running via rvm. (we're big fans of brew, so I don't think there's going to be a lot of folks wanting to use macports)

**Comment by DomT4** [comment]
I had no idea RVM used us so heavily, to be honest. A fair handful of issues on the tracker relating to us glancing through.

As far as I can see there's no reason to be building against the 0.9.8 branch specifically so hopefully we can get this ironed out quickly and restore full `brew` support for RVM.

**Comment by bobweston** [comment]
Thanks folks. I really appreciate it.
-Bob

**Comment by rys** [comment]
@bobweston @DomT4 I've merged a fix for this into RVM head. Run `rvm get head` to update your RVM to get it now. I'm not sure when our next stable release it, for it to show up in that branch. Sorry we neglected this, we don't do enough testing with Ruby 1.8 now on OS X (or any platform really).

**Comment by bobweston** [comment]
Hi Rys,

I completely understand. I need it for a handful of legacy applications. I really appreciate your quick response. Both homebrew-versions and rvm are great projects!

**Comment by DomT4** [comment]
Tentatively closing given the upstream fix and only a couple more people coming to find this Issue since. Will reopen temporarily though if more people come looking for an answer.

Thank you again for letting us know about this @bobweston and the quick fix upstream @rys.
