### ISSUE TITLE
Request for a go15 version

### ISSUE THREAD

**Issue by brianmario** [Homebrew/homebrew-versions#1152]
Hello there!

I have an application that has two dependencies using different versions of golang, one of which is 1.5.3. If we could get that added here that would make life much easier as I could specifically target that version instead of just `brew install go`.

Ideally we'd have a 1.6 version in here as well once it's released this month some time, but I can add another request for that once the time comes ;)

I'd go ahead and open a pull doing this myself but I'm unsure how to build the bottles and get those uploaded wherever they're supposed to go...

**Comment by dunn** [comment]
The bottling is handled by our CI bot, so don't worry about that!  Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md for the rest and let us know if you have further questions.

**Comment by DomT4** [comment]
To be honest a point release doesn't really meet our temporarily-revised eligibility requirements for Versions; I'm not sure on the long-term popularity or viability of people wanting only 1.5.3 rather than 1.5.2 or 1.5.4 and if we accept one we'll end up accepting the others as well.

In regards to 1.6 that'll likely be added to the main `go` formula as a `devel` block, I suspect.

**Comment by brianmario** [comment]
> To be honest a point release doesn't really meet our temporarily-revised eligibility requirements for Versions

Sorry I didn't mean to imply I needed 1.5.3 _specifically_. I just need 1.5. 1.5.3 just happens to [contain a security patch](https://groups.google.com/forum/#!topic/golang-announce/MEATuOi_ei4) that I'm sure most users would want. But if I were to install `go15` I'd just expect that to be some recent point release of the 1.5 series - hopefully the most recent.

**Comment by DomT4** [comment]
I see. A `go15` formula that tracks the branch rather than the point release would be acceptable. Don't necessarily count on people to keep it updated though in the same way the core is; Versions has been pretty neglected which is why we're in the process of making some changes here.

**Comment by mikemcquaid** [comment]
We chatted about this internally and decided that for this case this isn't needed. Thanks for the help @DomT4!

**Comment by DomT4** [comment]
Didn't realise OP was one of GitHub's people; would have dinged you sooner :wink:. Thanks for the update.
