### ISSUE TITLE
Process for updating JRuby versions with new patch releases

### ISSUE THREAD

**Issue by booc0mtaco** [Homebrew/homebrew-versions#1155]
Hey there,

I saw there were new patch releases for JRuby 9.0 and 1.7 (.5 and .24 respectively). My first thought was to add in new scripts for each one, bringing the total to 5 versions. However, I read about your strategies to keep versions at +/- 2 versions, etc. So I got to thinking, would I want to remove, and replace jruby9000 with 9050 and jruby1721 with 1724? or add new ones?

Also, I'm not sure if anyone else actually uses these formulae. Any usage statistics? 

Guidance is appreciated!

**Comment by MikeMcQuaid** [comment]
> So I got to thinking, would I want to remove, and replace jruby9000 with 9050 and jruby1721 with 1724? or add new ones?

Sounds about right!
