### ISSUE TITLE
Mysql 5.6 bottle nor mysql sources are available online

### ISSUE THREAD

**Issue by brutuscat** [Homebrew/homebrew-versions#1160]
The current brewed mysql 5.6 version is mysql-5.6.27 which has not been left online by Oracle (at least not at the specified URL...)

This breaks the formulae and it is not possible to install it when using osx el capitan.

**Comment by DomT4** [comment]
Please see the discussion in #1153. I'd love a PR.

**Comment by brutuscat** [comment]
@DomT4 is there any way to have some sort of a test suite? I could happily follow the instructions to submit a PR and change the file locations and the checksums, but I will be unable to support changes outside of my own workstation platform (el capitan). How do you guys, brewers, do this for the homebrew project?

**Comment by DomT4** [comment]
There's a CI (Jenkins) which checks every PR for all three platforms we officially support (Mavericks through to El Cap). It also handles bottle updates automatically, so all that needs changing should be the URL/SHA256 unless there's other breakage.

**Comment by wellebee** [comment]
Addressed in PR #1163.

**Comment by DomT4** [comment]
Fixed via https://github.com/Homebrew/homebrew-versions/commit/bf5f642f2e909541c137c16f3586c7f25054ef4e.
