### ISSUE TITLE
cvsps2 url is down

### ISSUE THREAD

**Issue by tgragnato** [Homebrew/homebrew-versions#1174]
[Currently git-cvsimport is broken 'cause of cvsps3 incompatibility.](git cvsimport password)
An easy workaround with homebrew should be
```
brew tap homebrew/versions
brew install cvsps2
brew unlink cvsps
brew link --overwrite cvsps2
```
The URL currently provided by the formula is down
> _**Download failed: http://www.cobite.com/cvsps/cvsps-2.1.tar.gz**_

I really don't know an alternative location.
Can someone provide one?

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-versions/commit/5c9a9a7a6ebcb89275ceb65575c45d91b99e1f76

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-versions/commit/5c9a9a7a6ebcb89275ceb65575c45d91b99e1f76

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-versions/commit/5c9a9a7a6ebcb89275ceb65575c45d91b99e1f76

**Comment by kenorb** [comment]
Related: https://github.com/Frizlab/homebrew-Perso/commit/4034741de2626617a7336bffa137dd948e026463
