### ISSUE TITLE
maven31 fails to install: fails to parse grpid 

### ISSUE THREAD

**Issue by kirenotneb** [Homebrew/homebrew-versions#1208]
It appears it is extracted with <username>:wheel as its owner:group yet Cellar looks like be <username>:admin for its owner:group. Not sure if this is the error.

$ brew install -v maven31
==> Installing maven31 from homebrew/versions
==> Downloading https://www.apache.org/dyn/closer.cgi?path=maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz
Already downloaded: /Library/Caches/Homebrew/maven31-3.1.1.tar.gz
==> Verifying maven31-3.1.1.tar.gz checksum
Error: no implicit conversion of String into Integer
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/extend/fileutils.rb:30:in `getgrgid'
/usr/local/Library/Homebrew/extend/fileutils.rb:30:in `rescue in mktemp'
/usr/local/Library/Homebrew/extend/fileutils.rb:27:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:1540:in `stage'
/usr/local/Library/Homebrew/formula.rb:926:in `brew'
/usr/local/Library/Homebrew/build.rb:108:in `install'
/usr/local/Library/Homebrew/build.rb:177:in `<main>'

$ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 20c2cbd98a728a0363e707640ef6bddae1248a19
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fc8992aa8f400421356cb4a0d6829423d5d485cc
Core tap last commit: 11 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit ivybridge
OS X: 10.11.4-x86_64
Xcode: 7.3
CLT: N/A
Clang: 7.3 build 703
X11: N/A
System Ruby: 2.0.0-p648
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_77, 1.7.0_80, 1.6.0_65-b14-468

**Comment by DomT4** [comment]
@ilovezfs Any thoughts here? You wrote the block of code it's complaining about :smile:. We've not seen this reported elsewhere to my recollection so possible this is something unique about OP's setup.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/brew/pull/31 will prevent the getgrgid crash but the real question is why the EPERM.

@kirenotneb did you set the environment variable HOMEBREW_TEMP by any chance?

**Comment by kirenotneb** [comment]
@ilovezfs No idea what happened but I just tried once more and it was a successful install. I installed a number of other brew packages (java 8, 7 and 6) prior to this on in the same session so there _might_ have been something that tweaked the environment variable, but it wasn't something I intentionally did. Moving on.

**Comment by ilovezfs** [comment]
@kirenotneb OK, thanks for following up. If you are able to reproduce it, please let us know because that's a spot in the code it shouldn't be possible to reach under any circumstance.
