### ISSUE TITLE
llvm38 has strange compiler identification

### ISSUE THREAD

**Issue by h-2** [Homebrew/homebrew-versions#1209]
I am using homebew-versions via travis ci mac builds and I can'T make llvm38 work, because cmake can't identify the compiler name. Usually it says:
```
-- The CXX compiler identification is Clang 3.9.0
```
but for the homebrew version it says:
```
-- The CXX compiler identification is unknown
```
(this in turn results in many clang specific things not being set and the build failing).

Do you override the compiler name somewhere?

Thanks for your help!

**Comment by mikemcquaid** [comment]
We don't really support using the LLVM formulae as compilers; there's various edge-cases. That said, if you figure it out we'd definitely accept a pull request.
