### ISSUE TITLE
gcc 6 

### ISSUE THREAD

**Issue by LittleBun** [Homebrew/homebrew-versions#1211]
Everytime I compile a program with double type, error occurs. Such as this program:
 #include <stdio.h>
  int main() {
      double x;
      printf("%f\n", x);
  }

Here is the compile error output:
_/var/folders/87/smx9vb092hlfz9sjbfpr0b4h0000gn/T//ccGKA17A.s:14:suffix or operands invalid for `movq'_

**Comment by DomT4** [comment]
This is probably something that needs reporting upstream, unless it happens exclusively with the Homebrew version of `gcc-6`.

**Comment by mikemcquaid** [comment]
Also: sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by DomT4** [comment]
Closing as dead.
