### ISSUE TITLE
llvm36 wont install from bottle

### ISSUE THREAD

**Issue by waj** [Homebrew/homebrew-versions#1212]
When I try to install `llvm36` it compiles everything from scratch. However `llvm35`, `llvm37` and `llvm38` all would install from bottles when installing with default options. Why is that? Is there anything wrong in my environment?

**Comment by DomT4** [comment]
I presume you're running El Capitan?

**Comment by DomT4** [comment]
Presuming resolved via https://github.com/Homebrew/homebrew-versions/commit/48532e642c3b0ecf88d9dbdca0d4b0867b9c2f57.
