### ISSUE TITLE
postgis21 is missing

### ISSUE THREAD

**Issue by jmagnusson** [Homebrew/homebrew-versions#1214]
Now that 2.2 is out it would be awesome with a 2.1 version here.

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
