### ISSUE TITLE
ffmpeg28

### ISSUE THREAD

**Issue by boecko** [Homebrew/homebrew-versions#1237]
ffmpeg 2.8.6 is needed, when you try to build vlc from the source.

https://raw.githubusercontent.com/boecko/homebrew-tap/master/ffmpeg28.rb

This is basically the from 
https://github.com/Homebrew/homebrew-core/commit/504546a79b9b71b28900432d290954e75d620719#diff-8f4deb87ce96b9c5efe97be3288bb406

customized to ffmpeg28 with a conflict to ffmpeg

**Comment by boecko** [comment]
i'll make a pull request ..

**Comment by DomT4** [comment]
Closing in favour of the PR.
