### ISSUE TITLE
Possible to get Node 4.3.2?

### ISSUE THREAD

**Issue by jthomerson** [Homebrew/homebrew-versions#1266]
AWS Lambda has two specific versions of node.js that they support: v0.10.36, and v4.3.2 (see http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html). Would it be possible to have a formula locked to version 4.3.2 so that developers can install that specific version via brew?

**Comment by mikemcquaid** [comment]
You could submit a formula for Node 0.4.x and we have one for Node 0.10.x. We don't believe in pinning to patch releases for security reasons.
