### ISSUE TITLE
Add Kafka 0.8.2.2 formula

### ISSUE THREAD

**Issue by vegaed** [Homebrew/homebrew-versions#1267]
It would be nice to get the latest 0.8.x formula before it was switched over to by 0.9.x

**Comment by MikeMcQuaid** [comment]
@vegaed We don't do formula requests. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!
