### ISSUE TITLE
maven30 formula has gone

### ISSUE THREAD

**Issue by phaustov** [Homebrew/homebrew-versions#1287]
brew install maven30

Error: No available formula with the name "maven30" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

**Comment by MikeMcQuaid** [comment]
See https://github.com/Homebrew/homebrew-versions#acceptable-formulae

**Comment by set321go** [comment]
For those of you who actually need this (because enterprise!) This is the commit that removed it. https://github.com/Homebrew/homebrew-versions/commit/e102cc897ae1330b021c10f128197546b29ac543

**Comment by set321go** [comment]
I created a tap that contains maven30 for those poor souls who have to use antique maven. 

https://github.com/set321go/homebrew-enterprise

**Comment by MikeMcQuaid** [comment]
Thanks @set321go!
