### ISSUE TITLE
Old version of GDB?

### ISSUE THREAD

**Issue by franklinyu** [Homebrew/homebrew-versions#1288]
I would like to create a pull request for GDB 7.7, but it violates the rule

> Versions formulae *must not* exceed +/-2 major/minor (not patch) versions from the current stable release.

Since current version is 7.11. The reason is that GDB after 7.8 does not work on OS X, as stated in Homebrew/homebrew-dupes#483. Is it possible to break this rule just for GDB?

**Comment by MikeMcQuaid** [comment]
I'd rather we kept consistent here. Please consider [creating your own tap](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap) instead. Thanks!
