### ISSUE TITLE
please add elasticsearch2.3  in addition to 2.2

### ISSUE THREAD

**Issue by wbolster** [Homebrew/homebrew-versions#1302]
see title :)

**Comment by jasontedor** [comment]
Elasticsearch 2.3.3 is already available via the core formulae; does that help?

**Comment by tdsmith** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this? [This document](https://git.io/vo2xc) should give you a head start and we'd be more than happy to walk you through it if you have any questions.

Another way you could use Homebrew to install this software is to [maintain your own tap](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md). The linked document has some advice; please let us know if you have any questions and we'll be happy to help you set things up.

**Comment by jasontedor** [comment]
I'm confused, sorry. [Elasticsearch version 2.3.3 is already available in homebrew-core](https://github.com/Homebrew/homebrew-core/blob/598734e815f93904b235951a0607101927c709d8/Formula/elasticsearch.rb#L4) and [Elasticsearch version 2.2.2 is already available in homebrew-versions](https://github.com/Homebrew/homebrew-versions/blob/f8c59174f8d9f550a68cdc86b0062737786ae0b5/elasticsearch22.rb#L4).

**Comment by wbolster** [comment]
yes, thanks. didn't notice before. sorry for the noise and confusion.
