### ISSUE TITLE
glfw3 3.2 fails to install on OS X 10.11

### ISSUE THREAD

**Issue by Marqin** [Homebrew/homebrew-versions#1318]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._
### Bug reports:

I've tried to upgrade glfw3 via `brew upgrade` and it fails with

```
CMake Error at src/CMakeLists.txt:56 (set_target_properties):
set_target_properties called with incorrect number of arguments.
```

Full logs: https://gist.github.com/Marqin/9c8fa2982496071a16e6c1b258042675

**Comment by ilovezfs** [comment]
What's the output of
```
brew outdated
```

**Comment by Marqin** [comment]
`homebrew/versions/glfw3 (3.1.2 < 3.2)` and nothing more

2016-07-21 17:15 GMT+02:00 ilovezfs <notifications@github.com>:

**Comment by ilovezfs** [comment]
And
```
cat /usr/local/Cellar/glfw3/3.1.2/INSTALL_RECEIPT.json
HOMEBREW_DEVELOPER=1 brew linkage glfw3
```

**Comment by Marqin** [comment]
First:
{"used_options":["--without-shared-library"],"unused_options":["--universal","--with-examples","--with-tests"],"built_as_bottle":false,"poured_from_bottle":false,"time":1446984368,"HEAD":"73bb07d65dd5c56b88c51325992c50955e759e00","stdlib":null,"compiler":"clang","source":{"path":"/usr/local/Library/Taps/homebrew/homebrew-versions/glfw3.rb","tap":"homebrew/homebrew-versions","spec":"stable"}}

second - nothing

2016-07-21 17:23 GMT+02:00 ilovezfs <notifications@github.com>:

**Comment by ilovezfs** [comment]
```
brew uninstall glfw3
brew install glfw3
```

**Comment by Marqin** [comment]
That poured it from bottle, without errors.

2016-07-21 17:37 GMT+02:00 ilovezfs <notifications@github.com>:

**Comment by ilovezfs** [comment]
@Marqin OK, do you mind trying
```
brew uninstall glfw3
brew install -dvs glfw3
```

**Comment by Marqin** [comment]
Hmm, also no problems.

2016-07-21 17:50 GMT+02:00 ilovezfs <notifications@github.com>:

**Comment by Marqin** [comment]
but:
brew install glfw3 --without-shared-library
stillgives the error I posted in first post

2016-07-21 19:04 GMT+02:00 Hubert Jarosz <hubert.jarosz@gmail.com>:

**Comment by BrianWestlake** [comment]
I'm having the same problem, OSX 10.11.6, 
brew install glfw3 
works fine, but 
brew install glfw3 --without-shared-library
gives the error:
CMake Error at src/CMakeLists.txt:56 (set_target_properties):
  set_target_properties called with incorrect number of arguments.

**Comment by ilovezfs** [comment]
The problem is being caused by Homebrew, not upstream.

This fixes it: #1319.

```
brew pull  https://github.com/Homebrew/homebrew-versions/pull/1319
```

if you'd like to test it.

**Comment by JamEngulfer** [comment]
When I run that command, I'm getting this error:

`==> Applying patch
Applying: glfw3: fix static build
fatal: sha1 information is lacking or useless (glfw3.rb).
error: could not build fake ancestor
Patch failed at 0001 glfw3: fix static build
The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Error: Patch failed to apply: aborted.`

**Comment by MikeMcQuaid** [comment]
This formula was migrated to Homebrew/homebrew-core. Please open issues there if you're still having problems.
