### ISSUE TITLE
littlecms2 - SHA256 Mismatch

### ISSUE THREAD

**Issue by eclipsed-ninja** [Homebrew/homebrew-versions#1321]
==> Installing dependencies for wine: little-cms2, jasper, libicns, makedepend, openssl, sane-backends, libtasn1, gmp, nettle, gnutls
==> Installing wine dependency: little-cms2
==> Downloading https://downloads.sourceforge.net/project/lcms/lcms/2.8/lcms2-2.8.tar.gz
==> Downloading from http://ncu.dl.sourceforge.net/project/lcms/lcms/2.8/lcms2-2.8.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 8e27f5207204e41c6e7f5aa3c1b92cd89f54b839464b7df4cd0d93b07b16333a
Actual: 66d02b229d2ea9474e62c2b6cd6720fde946155cd1d0d2bffdab829790a0fb22

Brew has been updated, and doctor has no warnings / errors.

**Comment by ilovezfs** [comment]
Not relevant to the checksum, but ... isn't this formula in homebrew/core? https://github.com/Homebrew/homebrew-core/blob/master/Formula/little-cms2.rb

**Comment by ilovezfs** [comment]
Ah I see what happened. Upstream uploaded a .tar file by mistake the first time, but corrected it by uploading an actual .tar.gz file this second time. The checksums of all the files inside the archives are the same.

**Comment by eclipsed-ninja** [comment]
Yeah, and sorry about creating this issue here.
I landed it here via google, and didn't check if it was the right repo, Sorry about that.

I verified via SHA1 / MD5 and checksums matched so I manually edited the rb file and made it work for now, till an update is pushed.

**Comment by ilovezfs** [comment]
@eclipsed-ninja No problem. Thanks for letting us know!

**Comment by ilovezfs** [comment]
I've mentioned to upstream that we noticed this happened https://github.com/mm2/Little-CMS/issues/88

**Comment by ilovezfs** [comment]
@eclipsed-ninja OK it's now fixed in https://github.com/Homebrew/homebrew-core/commit/ba00a4be7291f1eae67ef7db25508f33a0fc4f79.
