### ISSUE TITLE
lua53 --with-default-names doesn't adjust luarocks and luarocks-admin

### ISSUE THREAD

**Issue by telemachus** [Homebrew/homebrew-versions#1324]
When installing lua53 with the `with-detault-names` option, `luarocks` and `luarocks-admin` still come out as `luarocks-5.3` and `luarocks-admin-5.3`. I would have expected all the executables to lose the `-5.3` suffix.

I tried to patch this myself, but all I managed to do was cause the formula to (silently) not build `luarocks` or `luarocks-admin` at all.

Any thoughts? Thanks.

Edit: the following works. I kept trying to use string interpolation, but that doesn't seem to work with `bin.install_symlink`.

        if build.with? "default-names"
          bin.install_symlink libexec/"bin/luarocks"
          bin.install_symlink libexec/"bin/luarocks-admin"
        else
          bin.install_symlink libexec/"bin/luarocks-5.3"
          bin.install_symlink libexec/"bin/luarocks-admin-5.3"
        end

Does a patch with this fix make sense to people?

**Comment by MikeMcQuaid** [comment]
> Does a patch with this fix make sense to people?

Yes.

**Comment by telemachus** [comment]
@MikeMcQuaid Cool. Done https://github.com/Homebrew/homebrew-versions/pull/1337
