### ISSUE TITLE
set basedir/ldata in mysql_install_db for mysql56/mysql55

### ISSUE THREAD

**Issue by rouge8** [Homebrew/homebrew-versions#1336]
### Bug reports:

https://github.com/Homebrew/legacy-homebrew/pull/30345 had a patch to set `basedir`/`ldata` in `mysql_install_db` to fix this error with `mysql_install_db`:

```console
$ mysql_install_db
FATAL ERROR: Could not find ./bin/my_print_defaults

If you compiled from source, you need to run 'make install' to
copy the software into the correct location ready for operation.

If you are using a binary release, you must either be at the top
level of the extracted archive, or pass the --basedir option
pointing to that location.
```

I tried applying that fix to mysql56, but [mysql 5.6.8 changes from the shell script to a Perl script](https://dev.mysql.com/doc/refman/5.6/en/mysql-install-db.html).

**Comment by MikeMcQuaid** [comment]
We'll accept a pull request for this but as it's a non-fatal error we won't work on a patch here. Thanks for the report, though.
