### ISSUE TITLE
rubies consider building with suffix and dropping keg-only

### ISSUE THREAD

**Issue by hashar** [Homebrew/homebrew-versions#1357]
The rubies are keg-only and installed without a suffix. So one ends up with:

```
 /usr/local/Cellar/ruby22/2.2.5/bin/ruby
```

And a warning about the formula being keg-only preventing symbolic link for `ruby` to be put in `/usr/local/bin/ruby`.

When one has several rubies, each will typically be build with `--with-suffix` and end up with:

```
  /usr/local/Cellar/ruby22/2.2.5/bin/ruby22
```

The binaries still have to be manually linked under /usr/local/bin.

May I suggest the rubies to default to `--with-suffix` and get them linked in /usr/local/bin ?  This way one can just `brew install ruby21 ruby22` and have the related binaries available from the default `PATH` straight away.

Gist log in case that is of any interest https://gist.github.com/anonymous/c5c3ec91ccf2d1e852c94ea3ab614d50

**Comment by hashar** [comment]
Note the workaround is:
```
brew install ruby21 --with-suffix
brew link --force ruby21
brew install ruby22 --with-suffix
brew link --force ruby22
```

Let you then use the specific rubies via:
```
$ which gem21
/usr/local/bin/gem21
$ which gem22
/usr/local/bin/gem22
...
```

**Comment by MikeMcQuaid** [comment]
This seems like a very good idea 👍 Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by MikeMcQuaid** [comment]
We'll accept a PR for this either here or after they've been migrated to Homebrew/homebrew-core.

**Comment by hashar** [comment]
Hello @MikeMcQuaid sorry I have not followed up on this issue since you commented on it end of August. Eventually closing the issue as tricked me in crafting a patch to suffix all rubies by default :}

https://github.com/Homebrew/homebrew-versions/pull/1509

There is a nasty hack to conditionally mark a ruby version as keg only when the Mac OS X version ships the same ruby version by default (eg Sierra has 2.0.0, so ruby20.rb should be keg_only when build without a prefix).
