### ISSUE TITLE
Would MPICH/OpenMPI forcing latest stable GCC (instead of Clang) be an acceptable formula?

### ISSUE THREAD

**Issue by zbeekman** [Homebrew/homebrew-versions#1361]
### Context

I contribute to a Project that *can* use MPICH/OpenMPI with Clang, but this is less than ideal. The project is [OpenCoarrays](https://github.com) and it is [the GCC officially supported backend](https://gcc.gnu.org/wiki/CoarrayLib) implementation for Fortran 2008 Coarrays (a PGAS language, akin to say UPC).

Due to it's tight integration with GCC, we've noticed a few unexpected issues when using Clang based MPI to compile the backend library which is written in C. For our in-house CI and testing services, I manually build out MPICH and OpenMPI bottles forcing the latest GCC (6.1 currently) to be used as the C compiler. I then upload these (using Github issues as a personal CDN) so that we don't have to rebuild MPICH and OpenMPI on travis-ci which will cause the job to fail by  timing out or creating too much output. This in turn allows GCC to be used as the compiler for MPI programs instead of Clang, so we can build and test OpenCoarrays against GCC as intended rather than a mix of Clang and GFortran.

However, whenever the MPICH or OpenMPI formulae are updated, [this causes our CI to barf](https://travis-ci.org/sourceryinstitute/opencoarrays/jobs/156714281#L192-L194) because now my custom bottle is outdated.

### Request

Would homebrew versions be willing to support versions of MPICH and OpenMPI that forced builds to use GCC as the C compiler? I'd be happy to submit a pull request. This way, the bottles we need can be distributed through homebrew's usual mechanism (bintray) and I won't have to mess about build custom bottles, all I'll need to do is update the formula in versions when the  formula is updated in core.

Thoughts?

**Comment by MikeMcQuaid** [comment]
> Would homebrew versions be willing to support versions of MPICH and OpenMPI that forced builds to use GCC as the C compiler?

Unfortunately not. We consider things that don't work well with Clang to not be ported to OS X. We do want to [handle version upgrades better](https://github.com/Homebrew/brew/issues/620).

**Comment by zbeekman** [comment]
@MikeMcQuaid I don't have time to parse the linked issue about version upgrades in detail, at the moment... but it would certainly be nice if formulae specified via a custom bottle does not get rejected due to being "out of date"

e.g. `brew install my_package-2.1_1.yosemite.bottle.1.tar.gz` ==> 

```
Error: Bottle version mismatch
Bottle: my_package-2.1_1.yosemite.bottle.1.tar.gz (2.1_1)
Formula: my_package (2.1_2)
```

**Comment by MikeMcQuaid** [comment]
@zbeekman That's an accepted proposal pending an implementation: https://github.com/Homebrew/brew-evolution/blob/master/003-install-bottles-of-arbitrary-versions.md

**Comment by zbeekman** [comment]
Great news!

**Comment by ilovezfs** [comment]
if someone implements it ...
