### ISSUE TITLE
LLVM 3.9.0

### ISSUE THREAD

**Issue by frewsxcv** [Homebrew/homebrew-versions#1365]
Like [llvm38.rb](https://github.com/Homebrew/homebrew-versions/blob/master/llvm38.rb), but for [LLVM 3.9.0](http://llvm.org/releases/3.9.0/).

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by frewsxcv** [comment]
I very hastily attempted: https://gist.github.com/frewsxcv/0d0563c1d636242edb0a44fba32b8d18

Turns out I'm not too familiar with the LLVM build process (they switched to CMake) and don't have too much time right now to investigate the specifics.

**Comment by MikeMcQuaid** [comment]
> Turns out I'm not too familiar with the LLVM build process (they switched to CMake) and don't have too much time right now to investigate the specifics.

@frewsxcv Ok, no problem. We'll wait until someone does have the time to submit a PR (even if half-working and we can help get it over the finish line).

**Comment by dberlin** [comment]
FWIW: the homebrew core formula for llvm now properly uses cmake, so you should be able to use "how it does the build" from that.

**Comment by georgemarrows** [comment]
@dberlin yes, looks like just updating the URLs and checksums there may be enough. I'll try to put together a PR.
