### ISSUE TITLE
Invalid Formula issues trying to brew install homebrew/versions/ansible19

### ISSUE THREAD

**Issue by matthewmrichter** [Homebrew/homebrew-versions#1383]
- [x] Ran `brew update` and retried your prior step?
Yes.
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
Yes.
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
N/A

MRICHTER-MAC-2:ansible mrichter$ brew install homebrew/versions/ansible19
==> Tapping homebrew/versions
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-versions'...
remote: Counting objects: 224, done.
remote: Compressing objects: 100% (213/213), done.
remote: Total 224 (delta 19), reused 52 (delta 10), pack-reused 0
Receiving objects: 100% (224/224), 268.31 KiB | 0 bytes/s, done.
Resolving deltas: 100% (19/19), done.
Checking connectivity... done.
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-versions/postgresql93.rb
undefined method `rebuild' for #<BottleSpecification:0x007fe91427f6a0>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-versions/postgresql94.rb
undefined method `rebuild' for #<BottleSpecification:0x007fe91428a848>
Error: Cannot tap homebrew/versions: invalid syntax in tap!
MRICHTER-MAC-2:ansible mrichter$ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 06fe347de97975dc01e726f87bf07a56a6fb713e
Last commit: 4 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8d273962a14aba712e9258c639fdc05749b41239
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.7.4 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_45
OS X: 10.11.6-x86_64
Xcode: N/A
CLT: 7.3.1.0.1.1461711523
X11: N/A

**Comment by DomT4** [comment]
```
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 06fe347de97975dc01e726f87bf07a56a6fb713e
Last commit: 4 weeks ago
```

That's your problem. Try:
```bash
cd /usr/local && git fetch && git reset --hard origin/master
```

**Comment by matthewmrichter** [comment]
That worked.. thank you very much for the help!
