### ISSUE TITLE
add llvm39

### ISSUE THREAD

**Issue by Marqin** [Homebrew/homebrew-versions#1388]
LLVM 3.9 Was realesed. 

It's [problematic](https://github.com/Homebrew/homebrew-core/pull/4579) to update normal `llvm` package to 3.9, but it should be easy to just deploy it as `llvm39` package.

**Comment by MikeMcQuaid** [comment]
There's several linked pull requests so closing this. For future reference: please create a pull request rather than a request.

**Comment by Marqin** [comment]
@MikeMcQuaid I'm not proficient enough in LLVM to know how to configure new version properly. And given LLVM is big project, than much could have changed.
