### ISSUE TITLE
gnupg21 fails to install on macOS Sierra

### ISSUE THREAD

**Issue by stouset** [Homebrew/homebrew-versions#1392]
### Bug reports:

`brew install gnupg21`

```
==> make check
Last 15 lines from /Users/stephen/Library/Logs/Homebrew/gnupg21/03.make:
FAIL: tofu.test
PASS: gpgtar.test
PASS: use-exact-key.test
PASS: default-key.test
    > D74C5F22 C40FDECF ECABF51D <
PASS: export.test
PASS: finish.test
=======================================
1 of 36 tests failed
Please report to https://bugs.gnupg.org
=======================================
make[3]: *** [check-TESTS] Error 1
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
```

**Comment by tdsmith** [comment]
Can repro. Log: https://gist.github.com/6e109de9e765ed32a52eae81626e330e

Error is:
```
Wrong default trust.  Got: `e', expected `m'
FAIL: tofu.test
```

tofu.test.log: https://gist.github.com/68471697c6561d0ea3d8580af959612e

I noticed output is being parsed by awk in tofu.test; adding `depends_on "gawk"` didn't resolve the issue.

**Comment by tdsmith** [comment]
Oh. The test is bad: https://bugs.gnupg.org/gnupg/issue2393

> the keys in tests/openpgp/tofu-keys.asc all expire on 2016-09-17, less than
three months away.

> This means that tofu.test will fail with:

>   Wrong default trust.  Got: `e`, expected `m`

Fix: https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=commit;h=e584d6468a2e72cd01e55f46104f9f96b56c0b66

**Comment by ilovezfs** [comment]
it'll work now
