### ISSUE TITLE
Unable to Install mongodb26 from homebrew/versions

### ISSUE THREAD

**Issue by chiragvels** [Homebrew/homebrew-versions#1405]
# Please follow the general troubleshooting steps first:
- [ ] Ran `brew update` and retried your prior step?
  Yes, brew update gives output as Already up-to-date.
  And ran above step without luck
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
  brew doctor has nothing reported.
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
  No permission error, it was error of version not supporting.

_You can erase any parts of this template not applicable to your Issue._
### Bug reports:

Trying to install following command on macOS Sierra(10.12) 
brew install homebrew/versions/mongodb26

Gives me error SCons Error: option --osx-version-min: invalid choice: '10.12' (choose from '10.6', '10.7', '10.8', '10.9', '10.10', '10.11')

**Comment by MikeMcQuaid** [comment]
This version is probably not support on 10.12 and unfortunately I doubt it will be updated by upstream to be so.

**Comment by chiragvels** [comment]
ok,
Any patch that I can apply?

Thanks,

**Comment by MikeMcQuaid** [comment]
@chiragvels You'd need to create one.

**Comment by AntiFish03** [comment]
@chiragvels, the compatibility update is included in #1411

**Comment by chiragvels** [comment]
@AntiFish03 Thanks for the patch,
I will update soon.

Thanks,

**Comment by AntiFish03** [comment]
@chiragvels the patch has been merged.

**Comment by MikeMcQuaid** [comment]
This formula was removed.
