### ISSUE TITLE
imagemagick-ruby186 build failed on 10.11.6

### ISSUE THREAD

**Issue by jpurple** [Homebrew/homebrew-versions#1407]
# Please follow the general troubleshooting steps first:

I HAVE DONE THESE.
- [ x] Ran `brew update` and retried your prior step?
- [x ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [NA ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports:

```
Error produced when using brew to install:
Last 15 lines from /Users/REDACTED/Library/Logs/Homebrew/imagemagick-ruby186/02.make:
magick/blob.c:2682:13: error: no member named 'pos' in 'struct __sFILE'
          c=gzgetc(image->blob->file);
            ^~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/zlib.h:1699:43: note: expanded from macro 'gzgetc'
          ((g)->have ? ((g)->have--, (g)->pos++, *((g)->next)++) : gzgetc(g))
                                     ~~~  ^
magick/blob.c:2682:13: error: no member named 'next' in 'struct __sFILE'
          c=gzgetc(image->blob->file);
            ^~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/zlib.h:1699:57: note: expanded from macro 'gzgetc'
          ((g)->have ? ((g)->have--, (g)->pos++, *((g)->next)++) : gzgetc(g))
                                                   ~~~  ^
8 errors generated.
make[1]: *** [magick/magick_libMagickCore_la-blob.lo] Error 1
make: *** [install] Error 2
```

HERE IS GIST LOG LINK:
https://gist.github.com/56bb228ef3bf15e4e29dd2b51f7434f9

**Comment by gottfrois** [comment]
Any update on this one please?

**Comment by MikeMcQuaid** [comment]
@gottfrois If there were, we'd have posted it. It's likely this is plain broken on 10.11 and above and will likely be removed.

**Comment by MikeMcQuaid** [comment]
When I migrate this formula to Homebrew/core I will either fix it or delete it. If you use it I recommend trying to submit a pull-request here to fix it before I remove it. Thanks!
