### ISSUE TITLE
Interest in a Vim 7.4.x formula?

### ISSUE THREAD

**Issue by jondavidjohn** [Homebrew/homebrew-versions#1421]
I'd be willing to put a formula together (copypasta the previous 7.4 formulas from core) if you think it would fit the guidelines of what this tap is intended to support.

Thanks!

**Comment by MikeMcQuaid** [comment]
@jondavidjohn Out of interest: is 8.0 not backwards compatible or something? Just trying to understand the use-case. Thanks!

**Comment by jondavidjohn** [comment]
@MikeMcQuaid Sure! I believe some plugins are having compatibility issues.  My personal config has some rough spots when using 8.0. I had a previous install laying around so I was able to switch back, but the motivator here is to ensure I could install 7.4.x at least while plugins field their first wave of compatibility issues for 8.x.

**Comment by jondavidjohn** [comment]
For reference here is my specific issue preventing me from moving to 8.0

https://github.com/thoughtbot/vim-rspec/issues/120

**Comment by MikeMcQuaid** [comment]
Seems reasonable to include then, yep.
