### ISSUE TITLE
varnish 4.1.3 doesn't download: ValueError: unknown locale: UTF-8

### ISSUE THREAD

**Issue by NikitaKharkov** [Homebrew/homebrew-versions#1422]
brew install homebrew/versions/varnish4

https://gist.github.com/228ea5a191eb963492f4d4d4ca0be525

> Last 15 lines from /Users/admin/Library/Logs/Homebrew/varnish4/02.make:
>     import docutils.io
>   File "/usr/local/lib/python2.7/site-packages/docutils/io.py", line 18, in <module>
>     from docutils.utils.error_reporting import locale_encoding, ErrorString, ErrorOutput
>   File "/usr/local/lib/python2.7/site-packages/docutils/utils/error_reporting.py", line 47, in <module>
>     locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 562, in getlocale
> make[1]: **\* [varnishtop.1] Error 1
>     return _parse_localename(localename)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
>     raise ValueError, 'unknown locale: %s' % localename
> ValueError: unknown locale: UTF-8
> make[1]: **\* [varnishncsa.1] Error 1
> make[1]: **\* [vmod_directors.3] Error 1
> make[1]: **\* [vmod_std.3] Error 1
> make: **\* [install-recursive] Error 1

I think the important information here is **ValueError: unknown locale: UTF-8**

Actually there is nothing more to add.

**Comment by MikeMcQuaid** [comment]
Please try to resolve your many `brew doctor` warnings and try again.

**Comment by NikitaKharkov** [comment]
Guys, I read all details before writing to you. So I had this errors at least twice, maybe more after I did all yours recommendations.
I just inform you about this problem.
I think if you try it yourself you got the same error.

**Comment by MikeMcQuaid** [comment]
> I think if you try it yourself you got the same error.

I do not get the same error. What does `locale` output for you?

**Comment by NikitaKharkov** [comment]
I'm sorry, I was lazy to go Google and find answer for this question. This hint was helped me:[fixed  problem url](https://coderwall.com/p/-k_93g/mac-os-x-valueerror-unknown-locale-utf-8-in-python). Once I add: you have to reboot system if want do this by global bashrc. And I think these sets must be in global bashrc.

**Comment by MikeMcQuaid** [comment]
Glad you got this fixed!
