### ISSUE TITLE
question about the naming of llvm versions

### ISSUE THREAD

**Issue by UnixJunkie** [Homebrew/homebrew-versions#1429]
Hello,
Why are llvm versions named XY instead of XYZ ?
For example: llvm34 packages llvm 3.4.2
llvm35 -> 3.5.1
llvm36 -> 3.6.2
llvm37 -> 3.7.1
llvm38 -> 3.8.1

How can we add llvm 3.8.0 then if we need it?
3.8.0 is the clang-3.8 version on Ubuntu, it would be nice to have the exact same version in brew as well.
Also, for clang-3.5 they ship 3.5.2.
Other versions are OK, they match in brew and ubuntu.

**Comment by MikeMcQuaid** [comment]
Homebrew versions (and, eventually, homebrew core) support pinning on major/minor but not patch/security versions. If you need to match the exact version you should create your own tap.

**Comment by UnixJunkie** [comment]
Wouldn't it be possible to have aliases between formulae?
For example llvm362 would be just pointing to llvm36 and be an "empty" formula.

**Comment by MikeMcQuaid** [comment]
It's possible but we won't be supporting it here.
