### ISSUE TITLE
404 when installing mysql56

### ISSUE THREAD

**Issue by hoboman313** [Homebrew/homebrew-versions#1430]
brew install mysql56
==> Installing mysql56 from homebrew/versions
==> Downloading https://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.6.32.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "mysql56"
Download failed: https://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.6.32.tar.gz

It appears that navigating to anything on https://cdn.mysql.com/ always returns 404 now. :(

**Comment by MikeMcQuaid** [comment]
Looks like it needs a bump to 5.6.34. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by hoboman313** [comment]
Should be fixed now in my pull request.

**Comment by tucq88** [comment]
please merge this T_T

**Comment by dunn** [comment]
It's not ready to merge: https://github.library.ucsb.edu/ADRL/alexandria/pull/212

**Comment by dunn** [comment]
It's not ready to merge: https://github.com/Homebrew/homebrew-versions/pull/1431#issuecomment-257065644

**Comment by hoboman313** [comment]
It had been merged
