### ISSUE TITLE
How do I "uninstall" homebrew-versions?

### ISSUE THREAD

**Issue by iosdev-republicofapps** [Homebrew/homebrew-versions#1497]
I did `brew tap homebrew/versions` but it doesn't have the versions of node that I want (4.3.2 to match AWS Lambda).  So I want to get rid of homebrew/versions to install homebrew formulae "the old way" from the regular formulae not in homebrew-versions.  How do "untap" homebrew-versions to remove it completely and restore homebrew to the state it was in before I tapped homebrew/versions?

Thanks!

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if reporting a build issue include the link from:

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by MikeMcQuaid** [comment]
`brew untap homebrew/versions`

**Comment by MikeMcQuaid** [comment]
Also, please check `man brew` in future, thanks.
