### ISSUE TITLE
Installing homebrew/versions/unison240 failed on Sierra 10.12.2

### ISSUE THREAD

**Issue by otandka** [Homebrew/homebrew-versions#1505]
- [ ] Ran `brew update` and retried your prior step?
       Ran twice, no new updates.
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
       The issues listed appear harmless.  Output included in gist.

### Bug reports:

Failed to install homebrew/versions/unison240 on MacBookPro running macOS Sierra v10.12.2.

The error from ocamlopt suggests an compatibility problem with system libraries.
```
ocamlopt: system.ml ---> system.cmx
ocamlopt -I lwt -I ubase -I system -I system/generic -I lwt/generic -ccopt -mmacosx-version-min=10.5 -c /private/tmp/unison240-20170102-7206-1szed4p/unison-2.40.128/system.ml
File "/private/tmp/unison240-20170102-7206-1szed4p/unison-2.40.128/system.ml", line 1:
Error: The implementation /private/tmp/unison240-20170102-7206-1szed4p/unison-2.40.128/system.ml
       does not match the interface system.cmi:
       Values do not match:
         val symlink : ?to_dir:bool -> string -> string -> unit
       is not included in
         val symlink : string -> fspath -> unit
make: *** [system.cmx] Error 2
```
https://gist.github.com/0b4cade27ff4507a7fa6dab56bede3ab

**Comment by MikeMcQuaid** [comment]
When I migrate this formula to Homebrew/core I will either fix it or delete it. If you use it I recommend trying to submit a pull-request here to fix it before I remove it. Thanks!
