### ISSUE TITLE
gnupg21 2.1.17 needs DNS patches to work on macOS

### ISSUE THREAD

**Issue by philpennock** [Homebrew/homebrew-versions#1511]
GnuPG 2.1.17 introduces shiny new DNS resolver logic, custom, which is still settling down.  At the moment, the code breaks on macOS.  This appears as dirmngr being unable to resolve DNS, so keys can't be retrieved.

Be sure to `gpgconf --kill dirmngr` to kill any daemon left over from older versions.

So far there are at least two patches needed for working DNS on macOS (I wrote one of them, Werner Koch the other); they're on the gnupg-devel mailing-list.  I've put PGP-signed versions of them up at https://people.spodhuis.org/phil.pennock/software/patches/gnupg/2.1.17/

I'm running locally with these two patches and so far, things are working much better.

**Comment by ilovezfs** [comment]
I suggest you encourage upstream to put out a new release as we don't really make it a habit to apply patches to security software downstream.
