### ISSUE TITLE
gnupg21 2.1.17 DNS won't work

### ISSUE THREAD

**Issue by ghostbar** [Homebrew/homebrew-versions#1517]
This was already noted in #1511 and was closed.

I'm not asking for a patch, just to leave this open since it's helpful to know you're not crazy but there's actually something wrong with the package.

Because of this, things like retrieving keys from servers won't work and will give errors like:

```
$ gpg2 --refresh-keys
gpg: refreshing 13 keys from hkps://hkps.pool.sks-keyservers.net
gpg: keyserver refresh failed: No keyserver available
```

**Comment by ilovezfs** [comment]
This should be fixed now that we've shipped 2.1.18.
