### ISSUE TITLE
Bring back `brew versions`

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew-versions#1520]
The vast majority of Homebrew software does not bother to manage entries in homebrew-versions. For example, librdkafka has no homebrew-versions entry. For software like this, Homebrew users would really appreciate a convenient way to specify a git tag, branch, commit, or other reference when installing software, so that various software component versions align.

Please bring back `brew versions` to the main Homebrew program.

**Comment by MikeMcQuaid** [comment]
You can use `git` itself for this. We won't be bringing back `brew versions` because there's no way to fix older versions and fixes are required regularly so it adds hugely to our support burden and we're unable to fix it.
