### ISSUE TITLE
Request: librdkafka 0.8 - HEAD

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew-versions#1521]
Could someone please offer homebrew-versions entries for librdkafka, such as from v0.8 to v0.9.4 (HEAD), so that Mac users can more easily work with Kafka libs with very specific librdkafka version requirements?

**Comment by MikeMcQuaid** [comment]
We don't generally do formula requests so you'll need to submit the PR (to homebrew/core) yourself. If you can detail why you need the specific version then I can let you know if it's likely to be accepted.
