### ISSUE TITLE
gnupg 2.1.18 doesn't work with card reader

### ISSUE THREAD

**Issue by mturquette** [Homebrew/homebrew-versions#1525]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

After running brew update and brew upgrade, my OpenPGP card reader stopped working. After freaking out, crying and then putting on my big boy pants I tried many solutions specific to gpg to fix the issue. Finally after more crying and changing my pants I rolled back to 2.1.16 and the card reader works again. I did not try 2.1.17 out of paranoia.

Here is the error using 2.1.18:

```
gpg2 --card-status
gpg: selecting openpgp failed: Operation not supported by device
gpg: OpenPGP card not available: Operation not supported by device
```

`brew gist-logs <formula>`
`Error: No logs.`

**Comment by ilovezfs** [comment]
See discussion and workaround here: https://github.com/Homebrew/homebrew-versions/commit/bece3fdbb732bcf646589c051f2f882e2bbf0875#commitcomment-20910891

**Comment by ilovezfs** [comment]
Closing this since it's an upstream bug.

**Comment by ilovezfs** [comment]
This is now fixed if you `brew update` and `brew upgrade`
