### ISSUE TITLE
MySQL Disabling "secure-file-priv"

### ISSUE THREAD

**Issue by tomrossi7** [Homebrew/homebrew-versions#1552]
I had to reinstall MySQL 5.6 (mysql@5.6 formula) and this is the first time I've seen this issue. Basically, the new install appears to be enabling the --secure-file-priv option and I can't find where to disable it.

"**The MySQL server is running with the --secure-file-priv option so it cannot execute this statement**"

Where does Brew set this option?

**Comment by MikeMcQuaid** [comment]
This isn't something we configure specifically so I'm afraid we can't help here.

**Comment by tomrossi7** [comment]
@MikeMcQuaid do you know who maintains the formula? I can't find it?

**Comment by MikeMcQuaid** [comment]
It's in homebrew/core as mysql@5.6. Please read the README in future, thanks.

**Comment by tomrossi7** [comment]
@MikeMcQuaid I'm confused? I thought you said to do it under homebrew-core? Can you just tell me where to go to get help with mysql@5.6 formula?

**Comment by MikeMcQuaid** [comment]
We can't help here as in in Homebrew because this isn't an option we pass specifically. If you can figure it out yourself we may consider accepting a pull request to fix this but it's not something we plan on working on, sorry.

**Comment by black-snow** [comment]
@tomrossi7 have you found a solution? I tried editing the launchagent plist but that didn't do the trick

**Comment by tomrossi7** [comment]
@black-snow thank you, thank you, thank you!!
