### ISSUE TITLE
llvm35 fails to build

### ISSUE THREAD

**Issue by JetForMe** [Homebrew/homebrew-versions#520]
$ brew install --HEAD --enable-targets=all llvm35
==> Cloning http://llvm.org/git/llvm.git
Updating /Library/Caches/Homebrew/llvm35--git
==> Cloning http://llvm.org/git/polly.git
Updating /Library/Caches/Homebrew/llvm35--polly--git
==> Checking out branch release_35
==> Downloading http://isl.gforge.inria.fr/isl-0.13.tar.bz2
Already downloaded: /Library/Caches/Homebrew/llvm35--isl-0.13.tar.bz2
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/llvm35/HEAD/lib/llvm-3.5/libexec/isl --with-gmp=system --with-gmp-prefix=/usr/local/opt/gmp
==> make
==> make install
==> Downloading http://repo.or.cz/w/cloog.git/snapshot/22643c94eba7b010ae4401c347289f4f52b9cd2b.tar.gz
Already downloaded: /Library/Caches/Homebrew/llvm35--cloog-HEAD.tar.gz
==> ./autogen.sh
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/llvm35/HEAD/lib/llvm-3.5/libexec/cloog --with-gmp-prefix=/usr/local/opt/gmp --with-isl-prefix=/usr/local/Cellar/llvm35/HEAD/lib/llvm-3.5/libexec/isl
==> make
==> make install
==> ./configure --prefix=/usr/local/Cellar/llvm35/HEAD/lib/llvm-3.5 --enable-optimized --disable-bindings --with-gmp=/usr/local/opt/gmp --with-isl=/usr/local/Cellar/llvm35/HEAD/lib/llvm-3.5/libexec/isl --with-cloog=/usr/lo
==> make VERBOSE=1
make[3]: *** [/private/tmp/llvm35-eBFsQH/tools/polly/lib/Release+Asserts/Exchange/JSONExporter.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all] Error 1
make[1]: *** [polly/.makeall] Error 2
make: *** [all] Error 1

READ THIS: https://github.com/Homebrew/homebrew/wiki/troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-versions/issues

Brew doctor after the above:

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:

    /usr/local/CrossPack-AVR/bin/libusb-config

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:

    llvm35
Error: Failed to import: arm-llvm
invalid attribute: version
Error: Failed to import: llvm
No such file or directory

**Comment by hlin117** [comment]
Could it be related to the fact that llvm3.5 currently doesn't support the `-fsanitize=address` flag / AddressSanitizer?

Source: http://stackoverflow.com/questions/16130191/clang-address-sanitizer-on-osx

(You could also try compiling a project that uses clang with the `-faddress=sanitizer` flag. It won't work.)

As for myself, I tried
`brew install --HEAD llvm35 --with-asan --with-clang --with-libcxx`
and this produced the same result.

https://gist.github.com/anonymous/412a08afcf3c0284a5c3

**Comment by aktau** [comment]
I'm getting some different errors, OSX Yosemite, llvm 3.5.1. Here's the gist: https://gist.github.com/aktau/f69ed372347b58395c90

**Comment by insideloop** [comment]
The compilation fails at the same place as aktau on 10.10.2. It there any way to get a new clang with address sanitizer on OSX ?

**Comment by DomT4** [comment]
It may be useful for people encountering errors to drop the failures to the [LLVM Bug mailing list](http://lists.cs.uiuc.edu/mailman/listinfo/llvmbugs). LLVM is a complicated codebase to work with, and they're more likely to have a better idea what the breakage is. We build LLVM36 nigh identically to LLV35, so it'd be interesting to see if the exact failure is reproducible using LLVM36, the most recent release, as well.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
