### ISSUE TITLE
subversion17 issues in 10.10

### ISSUE THREAD

**Issue by MFAnderson** [Homebrew/homebrew-versions#565]
Installation of subversion17 with --java --universal passes without any failures, but attempting to use Subversion through Eclipse fails with "sqlite compiled for 3.8.7.1 but running with 3.8.5". The error is unsurprising as the sqlite formula is for 3.8.7.1 but is keg-only while the system sqlite is 3.8.5.

**Comment by DomT4** [comment]
Is this still an issue now the ` sqlite ` version in Homebrew/homebrew is newer than OS X Yosemite's native version? Theoretically, It should have been using Homebrew's ` sqlite ` regardless because that would have been first in the ` $PATH `, before the sqlite in ` /usr/bin `.

**Comment by DomT4** [comment]
Closing per silence. Feel free to ping me here if it's still an issue.
