### ISSUE TITLE
maven30 failed to build on 10.10.1

### ISSUE THREAD

**Issue by jonkemp** [Homebrew/homebrew-versions#596]
```bash
$ HOMEBREW_MAKE_JOBS=1 brew install -v maven30 2>&1
==> Installing maven30 from homebrew/homebrew-versions
==> Downloading http://www.apache.org/dyn/closer.cgi?path=maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz
Already downloaded: /Library/Caches/Homebrew/maven30-3.0.5.tar.gz
==> Verifying maven30-3.0.5.tar.gz checksum
mktemp: mkdtemp failed on /tmp/maven30-Vlyg5l: Permission denied
Error: Failed to create sandbox

$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: ea507c6b3aae1c4687ef600d7ff175e91c70b179
Last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit haswell
OS X: 10.10.1-x86_64
Xcode: 6.1.1
CLT: 6.1.1.0.1.1416017670
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
```

maven31 fails to build also with the same errors.

**Comment by jacknagel** [comment]
Not sure how to help, sorry :/ Homebrew needs a functional `mktemp`.

**Comment by vaskaloidis** [comment]
I figured out the problem. You need to set the permissions to /tmp or /tmp/private (on a mac) - in my case the /private/tmp file was somehow deleted!

I documented my fix here: http://kaloidistech.com/wordpress/?p=101

**Comment by dragon788** [comment]
There is also a HOMEBREW_TEMP environment variable you can set to a custom directory which I believe may work around the issue, if it doesn't work just by setting that variable to something like `~/.tmp` you can try running `mkdir ~/.tmp; chmod +t ~/.tmp` and that should fix it for sure.
