### ISSUE TITLE
Subversion16 patch failing on brew install

### ISSUE THREAD

**Issue by dele454** [Homebrew/homebrew-versions#635]
I am trying to install subversion16 formula but keep getting this error:

curl: (7) Failed connect to trac.macports.org:443; Operation timed out
Error: Failed to download resource "subversion16--patch"
Download failed: https://trac.macports.org/export/73004/trunk/dports/devel/subversion-javahlbindings/files/patch-configure.diff

**Comment by jacknagel** [comment]
Looks like a temporary network issue.

**Comment by dele454** [comment]
Ok thanks!
