### ISSUE TITLE
Tomcat7 v7.0.57 not found

### ISSUE THREAD

**Issue by Andersos** [Homebrew/homebrew-versions#648]
``` bash
brew update
Already up-to-date.
brew doctor
Your system is ready to brew.
brew install tomcat7
==> Installing tomcat7 from homebrew/homebrew-versions
==> Downloading http://www.apache.org/dyn/closer.cgi?path=tomcat/tomcat-7/v7.0.57/bin/apache-tomcat-7.0.57.tar.gz
==> Best Mirror http://apache.uib.no/tomcat/tomcat-7/v7.0.57/bin/apache-tomcat-7.0.57.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "tomcat7"
Download failed: http://apache.uib.no/tomcat/tomcat-7/v7.0.57/bin/apache-tomcat-7.0.57.tar.gz
```

I went to the site and checked but they only had version 7.0.59. Maybe we can update?

**Comment by jackwanders** [comment]
bump for this issue, every mirror of 7.0.57 404s:
http://www.apache.org/dyn/closer.cgi?path=tomcat/tomcat-7/v7.0.57/bin/apache-tomcat-7.0.57.tar.gz

**Comment by Andersos** [comment]
There are already like 5 pull request for this https://github.com/Homebrew/homebrew-versions/pull/658, https://github.com/Homebrew/homebrew-versions/pull/649, https://github.com/Homebrew/homebrew-versions/pull/657, https://github.com/Homebrew/homebrew-versions/pull/646 and https://github.com/Homebrew/homebrew-versions/pull/642.

It made me question the maintainers in https://github.com/Homebrew/homebrew-versions/issues/659 since it is starting to be a little ridiculous. 

Luckily you can use ```brew edit tomcat7``` or ```brew pull https://github.com/Homebrew/homebrew-versions/pull/657``` to fix this locally as a workaround.

**Comment by DomT4** [comment]
This will be taken care of shortly.
