### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by Andersos** [Homebrew/homebrew-versions#659]
Who is maintaining this repo?

**Comment by DomT4** [comment]
Homebrew/Homebrew's maintainers. It has fallen behind the list of priorities a little, due to the sheer amount of work it takes to look after older versions of software, but they'll get around to it soon I'm sure.

**Comment by Andersos** [comment]
If they have a lot to do maybe they can accept new maintainers? It should be possible to take in some of the pull requests that have been there for some time https://github.com/Homebrew/homebrew-versions/pulls?q=is%3Aopen+is%3Apr

**Comment by DomT4** [comment]
There are 6 core maintainers, and two who tend to deal with Versions PRs, Jack and Mike. I'm sure they've considered whether it's worthwhile snagging someone to handle the Homebrew/Versions repo, but it's kind of a complicated repo to handle, there's a lot of old, outdated code that needs modernising, and that takes considerable time and effort. I appreciate PRs have been standing for a while.

**Comment by Andersos** [comment]
I didn't really understand your last comment "I appreciate PRs have been standing for a while."

I understand that there are complicated parts of this repo but it should be possible to pull in new "old" versions like https://github.com/Homebrew/homebrew-versions/pull/642 introduces.

**Comment by DomT4** [comment]
> I didn't really understand your last comment "I appreciate PRs have been standing for a while."

As in "I know PRs have been standing for a while, and obviously that's not ideal for people, but please bear with the maintainers who have their hands full and are aware of the situation here". You can @ Mike or Jack into the conversation if you wish for their direct perspective, I don't speak for them, nor can I read their minds, I just wanted to highlight the amount of work it takes to maintain this particular repo and how that can potentially have delaying effects. It isn't a dead repo.

**Comment by Andersos** [comment]
I managed to fix my problem with the brew edit command. Mike and Jack are probably doing a really good job. I just didn't see anyone working on the pull requests and could not find anything useful for that in the readme. If they really have a lot to do then maybe they should consider taking in more people to help. Anyway, thanks for the chat @DomT4 =)

**Comment by DomT4** [comment]
Yeah, you can make local changes. You can also do things like ` brew pull https://github.com/Homebrew/homebrew-versions/pull/657 ` which patches the formula for you as if the PR had been merged.

Apologies if my tone was abrasive. Blame my being British and our national collective grumpiness :wink:.

**Comment by Andersos** [comment]
I didn't find it abrasive. Just informative =)
