### ISSUE TITLE
coq8.3 won't build

### ISSUE THREAD

**Issue by ifigueroap** [Homebrew/homebrew-versions#674]
I'm getting the following error when trying to install homebrew/versions/coq83:

```
OCAMLOPT  kernel/univ.ml
File "kernel/univ.ml", line 200, characters 0-2:
Error: This comment contains an unterminated string literal
File "kernel/univ.ml", line 200, characters 17-20:
Error: String literal begins here
make[1]: *** [kernel/univ.cmx] Error 2
rm lib/compat.ml
make: *** [world] Error 2
```

The log for the 

```
brew install -v homebrew/versions/coq83
```

commmand can be found in this gist: https://gist.github.com/ifigueroap/dd5dd9a6722bfbe63960

**Comment by DomT4** [comment]
Yeah, confirmed. Suspect ` objective-caml ` or ` camlp5 ` made some breaking API changes at some point and broke the old ` coq83 `. Thoughts welcome on this @mikemcquaid @jacknagel.

**Comment by mikemcquaid** [comment]
I guess we version whatever of the dependencies needs an older version.

**Comment by DomT4** [comment]
Fixed.
