### ISSUE TITLE
Can't brew install gmp4

### ISSUE THREAD

**Issue by huangsy13** [Homebrew/homebrew-versions#676]
==> Installing gmp4 from homebrew/homebrew-versions
==> Downloading http://ftpmirror.gnu.org/gmp/gmp-4.3.2.tar.bz2
Already downloaded: /home/huangsy13/.cache/Homebrew/gmp4-4.3.2.tar.bz2
==> Patching
patching file gmp-h.in
==> ./configure --prefix=/home/huangsy13/.linuxbrew/Cellar/gmp4/4.3.2 --enable-c
==> make
Makefile:925: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/gmp4-a4tl20/gmp-4.3.2'
Makefile:666: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jacknagel** [comment]
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
