### ISSUE TITLE
brew doctor:Failed to import: flann

### ISSUE THREAD

**Issue by zhangmin93** [Homebrew/homebrew-versions#711]
After i install opencv on brew, i run brew doctor, and i got this new errors:

Error: Failed to import: flann
undefined method `deprecated_option' for Flann:Class
Error: Failed to import: gromacs
undefined method `deprecated_option' for Gromacs:Class
Error: Failed to import: hdf5
undefined method `deprecated_option' for Hdf5:Class
Error: Failed to import: infernal
undefined method `deprecated_option' for Infernal:Class
Error: Failed to import: nauty
undefined method `deprecated_option' for Nauty:Class
Error: Failed to import: netcdf
undefined method `deprecated_option' for Netcdf:Class
Error: Failed to import: petsc
undefined method `deprecated_option' for Petsc:Class
Error: Failed to import: slepc
undefined method `deprecated_option' for Slepc:Class
Error: Failed to import: vtk
undefined method `deprecated_option' for Vtk:Class
Error: Failed to import: vtk5
undefined method `deprecated_option' for Vtk5:Class

so, how can i get rid of the new errors?

**Comment by DomT4** [comment]
Make sure you're up-to-date with ` brew update && brew upgrade `. If the error persists afterwards, please report this to [Homebrew/homebrew-science](https://github.com/Homebrew/homebrew-science) as the formulae involved in the errors above are their formulae.
