### ISSUE TITLE
under 10.9.5 fail cmd:  brew install homebrew/versions/subversion17

### ISSUE THREAD

**Issue by Speakus** [Homebrew/homebrew-versions#726]
<pre>
==> Installing subversion17 from homebrew/homebrew-versions
==> Downloading http://mirror.cogentco.com/pub/apache/subversion/subversion-1.7.
Already downloaded: /Library/Caches/Homebrew/subversion17-1.7.14.tar.bz2
==> Downloading http://serf.googlecode.com/files/serf-1.3.3.tar.bz2
Already downloaded: /Library/Caches/Homebrew/subversion17--serf-1.3.3.tar.bz2
==> /usr/local/opt/scons/bin/scons PREFIX=/usr/local/Cellar/subversion17/1.7.14_
#include <apr_pools.h>
         ^
1 error generated.
scons: *** [context.o] Error 1
scons: building terminated because of errors.
</pre>
github cut info - i add here: include arp_pools.h (in triangle brackets)

**Comment by DomT4** [comment]
Just merged a vast modernisation of the formula involved to iron out some of the old issues. Try a ` brew update && brew install subversion17 ` and let me know how you get on.

**Comment by Speakus** [comment]
ok. Now it works. Thanks
