### ISSUE TITLE
llvm33 fails to compile in Yosemite with universal flag

### ISSUE THREAD

**Issue by eflynch** [Homebrew/homebrew-versions#729]
The build worked fine with the patch fixing Makefile.rules until a certain point (see the log below). I believe the problem is similar to the issue in #453, but this time with the os version number parsing in src/projects/sample/Makefile.llvm.rules file. I do not know how to construct the patch.

/private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/autoconf/mkinstalldirs /private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/lib/sample/Release+Asserts > /dev/null
/private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/autoconf/mkinstalldirs /private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/Release+Asserts/lib > /dev/null
/bin/date > /private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/lib/sample/Release+Asserts/.dir
/bin/date > /private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/Release+Asserts/lib/.dir
llvm[4]: Compiling sample.c for Release+Asserts build
clang -I/private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/include -I/private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/include -I/private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/lib/sample  -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3  -fno-common   -mmacosx-version-min=10.1 -pedantic -Wno-long-long -Wall -W -Wno-unused-parameter -Wwrite-strings   -arch i386 -arch x86_64 -c sample.c -o /private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/lib/sample/Release+Asserts/sample.o
llvm[4]: Building Release+Asserts Archive Library libsample.a
/bin/rm -f /private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/Release+Asserts/lib/libsample.a
ar cru /private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/Release+Asserts/lib/libsample.a /private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/lib/sample/Release+Asserts/sample.o
ranlib /private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/Release+Asserts/lib/libsample.a
for dir in sample; do \
	  (/Applications/Xcode.app/Contents/Developer/usr/bin/make -C $dir all ) || exit 1; \
	done
/private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/autoconf/mkinstalldirs /private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/tools/sample/Release+Asserts > /dev/null
/private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/autoconf/mkinstalldirs /private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/Release+Asserts/bin > /dev/null
/bin/date > /private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/Release+Asserts/bin/.dir
/bin/date > /private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/tools/sample/Release+Asserts/.dir
llvm[4]: Compiling main.c for Release+Asserts build
clang -I/private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/include -I/private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/include -I/private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/tools/sample  -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3  -fno-common   -mmacosx-version-min=10.1 -pedantic -Wno-long-long -Wall -W -Wno-unused-parameter -Wwrite-strings   -arch i386 -arch x86_64 -c main.c -o /private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/tools/sample/Release+Asserts/main.o
llvm[4]: Linking Release+Asserts executable Sample (without symbols)
clang++ -I/private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/include -I/private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/include -I/private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/tools/sample  -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3  -fno-exceptions -fno-common -Woverloaded-virtual -Wcast-qual  -O3 -Wl,-rpath -Wl,@executable_path/../lib -L/private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/Release+Asserts/lib -L/private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/Release+Asserts/lib  -mmacosx-version-min=10.1  -pedantic -Wno-long-long -Wall -W -Wno-unused-parameter -Wwrite-strings   -arch i386 -arch x86_64  -o /private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/Release+Asserts/bin/Sample  /private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/tools/sample/Release+Asserts/main.o -lsample \
	   -lpthread -lffi -lm
ld: -rpath can only be used when targeting Mac OS X 10.5 or later
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [/private/tmp/llvm3320150319-8077-x2vzcs/llvm-3.3.src/projects/sample/Release+Asserts/bin/Sample] Error 1
make[3]: *** [all] Error 1
make[2]: *** [all] Error 1
make[1]: *** [all] Error 1
make: *** [all] Error 1
==> Formula
Tap: homebrew/homebrew-versions
Path: /usr/local/Library/Taps/homebrew/homebrew-versions/llvm33.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: bf9c1ae7f5f65493181df4924bc70699da5e1abf
Last commit: 57 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit haswell
OS X: 10.10.2-x86_64
Xcode: 6.2
CLT: 6.2.0.0.1.1424975374
Clang: 6.0 build 600
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby
Java: N/A
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local/opt/gmp4:/usr/local/opt/isl011:/usr/local/opt/cloog018:/usr/local/opt/libffi:/usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/isl011/lib/pkgconfig:/usr/local/opt/cloog018/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/cloog018/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by eflynch** [comment]
I ran into this problem when trying to compile the faust2 branch of FAUST which requires a universal build of llvm33 or llvm34. Anyone interested in looking into this or pointing me to how to solve it?

**Comment by DomT4** [comment]
It looks similar to the existing patch needed, as you point out. It should be fairly easy to port consequently, but well, LLVM is a *long* build process and complicated codebase which that makes testing somewhat painful. We welcome PRs to port the patch over to the other troublesome area, but otherwise I'll try and find some time where my laptop doesn't mind me melting it to try and deal with it in the nearish future.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
