### ISSUE TITLE
llvm36 fail to build in 10.10 if add --with-asan

### ISSUE THREAD

**Issue by meritozh** [Homebrew/homebrew-versions#756]
Latest Command Line Tools is installed.

Output of `brew install llvm36 --with-lldb --with-lld --with-all-targets --with-asan`:

<https://gist.github.com/anonymous/b241e76a120ecccd76c3>

    make[3]: *** [compiler-rt/.makeall] Error 2
    make[2]: *** [all] Error 1
    make[1]: *** [clang/.makeall] Error 2
    make: *** [all] Error 1

It fail to build because of option "--with-asan", if i use `brew install llvm36 --with-lldb --with-lld --with-all-targets`, it will success to build.

So where the problem is?

**Comment by alexdunn** [comment]
I am also unable to build when I add the `--with-asan` option.  I get the same error.  From the make log in @meritozh's gist:
```
dyld: Library not loaded: /usr/local/Cellar/llvm36/3.6.0/lib/llvm-3.6/lib/libLLVM-3.6.dylib
  Referenced from: /private/tmp/llvm3620150408-79252-16uf8im/llvm-3.6.0.src/Release+Asserts/bin/clang
  Reason: image not found
make/platform/clang_linux.mk:16: *** "unable to infer compiler target triple for /private/tmp/llvm3620150408-79252-16uf8im/llvm-3.6.0.src/Release+Asserts/bin/clang".  Stop.
```

Why is it looking for the LLVM dyld at that location *while* it's being built?  I wouldn't expect it to be there until afterwards when it's finished building and installing.

**Comment by paraboul** [comment]
Same issue here.

**Comment by inolen** [comment]
Did anyone have any luck with this? Just hit it myself.

**Comment by inolen** [comment]
Just worked around this by removing `CC="$(ToolDir)/clang" \` from the compiler-rt makefile.

**Comment by meritozh** [comment]
@inolen But I can't find `CC="$(ToolDir)/clang"`in the compiler-rt makefile.

**Comment by inolen** [comment]
Erm, fairly sure that's where it was. I grep'd the `/private/..` build dir while building.

**Comment by kodabb** [comment]
I was able to install it with this line
`brew install llvm36 --with-asan --with-lldb --with-lld --with-all-targets`
after patching `tools/clang/runtime/compiler-rt/Makefile` as @inolen suggested.

**Comment by meritozh** [comment]
Thanks to @inolen and @kodabb , I have succeed.
Here are what you should do in OS X:
1. `cd /Library/Caches/Homebrew`
2. `extract llvm36--clang-3.6.1.tar.xz`
3. `modify cfe-3.6.1.src/runtime/compiler-rt/Makefile as @inolen suggested`
4. `compress the modified cfe-3.6.1.src to llvm36--clang-3.6.1.tar.xz`
5. `brew install llvm36 --with-asan --with-lldb --with-lld --with-all-targets`
6. `follow the sha256 error, edit llvm36.rb`
7. `brew install llvm36 --with-asan --with-lldb --with-lld --with-all-targets`

@DomT4, you can close this issue

**Comment by paraboul** [comment]
Hey,

Thanks for the update.
Though, why closing the issue? Shouldn't be this patched in the formula?

**Comment by meritozh** [comment]
@paraboul 
Maybe overwriting `CC` can solve it. But i don't how to reach it by just modifing the llvm36.rb.
So, thanks to inolen and kodabb, i can just update those verbose steps.

Hope someone can do it.

**Comment by flaub** [comment]
I have a PR, but:

1. I only dabble in `ruby`, please pardon the mess.
1. I'm not familiar with the `homebrew` internals, if there's a better way I'll try to improve it.

That said, the patch automates the process described by @inolen, @kodabb , and @meritozh.

I've looked at upstream bugs and it doesn't look like this particular issue is there. However, it seems like there is some discussion about how to bootstrap `compiler-rt`:
https://llvm.org/bugs/show_bug.cgi?id=14109
