### ISSUE TITLE
subversion16 co Segmentation fault: 11

### ISSUE THREAD

**Issue by hayorov** [Homebrew/homebrew-versions#758]
1. brew install subversion16 && brew unlink subversion && brew link subversion16
2. svn co https://foo/prj prg
Segmentation fault: 11
Logs: https://gist.github.com/8f12eea62d313c620f35

OS X: 10.10.3-x86_64
Xcode: 6.3
CLT: 6.3.0.0.1.1428348375

brew doctor ok
brew --version
0.9.5

**Comment by DomT4** [comment]
Try the PR in #759.

**Comment by roosto** [comment]
I am still having this problem with `subversion16` on 10.10.5, and have reproduced it on multiple Macs.

I’m happy to report this as a new issue, complete with logs & diagnostic output, but I am dumb about `git` (I mean, I’m trying to use a years old version of `svn`, what do you expect from me?!). I cannot tell if this pull request has been incorporated into the main `homebrew-versions`, that I have `brew tap`’ed. I don’t want to re-report an issue that has a solution and has just not been incorporated back into the main branch.

Please advise and also please forgive my ignorance.
