### ISSUE TITLE
Build error gcc48 (brew + boxen)

### ISSUE THREAD

**Issue by edlau** [Homebrew/homebrew-versions#760]
I have a boxen setup + brew on a 10.10.3, while updating gcc

==> Upgrading gcc48
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.8.4/gcc-4.8.4.tar.bz2
Already downloaded: /opt/boxen/cache/homebrew/gcc48-4.8.4.tar.bz2
==> ../configure --build=x86_64-apple-darwin14.3.0 --prefix=/opt/boxen/homebrew/Cellar/gcc48/4.8.4 --libdir=/opt/boxen/homebrew/Cellar/gcc48/4.8.4/lib/gcc/4.8 --enable-languages=c,c++,objc,
==> make bootstrap
gcc/tree-ssa-threadupdate.o differs
gcc/valtrack.o differs
make[2]: *** [compare] Error 1
make[1]: *** [stage3-bubble] Error 2
make: *** [bootstrap] Error 2

https://gist.github.com/2eefa29c8ac2a246a032

**Comment by mistydemeo** [comment]
Please read the [troubleshooting guide](http://git.io/brew-troubleshooting) and post all of the requested diagnostics, thanks!

**Comment by edlau** [comment]
@mistydemeo - added gist https://gist.github.com/2eefa29c8ac2a246a032

**Comment by leonardoobaptistaa** [comment]
I had the same issue yesterday, this comment helped me to solve it:
https://github.com/Homebrew/homebrew/issues/38501#issuecomment-91678230

To update your boxen gcc48, you have to update the file repo/modules/gcc/files/brews/gcc48.rb and include this line:
```
"--with-build-config=bootstrap-debug",
```

after this:

```
(...)
"--enable-version-specific-runtime-libs",
"--enable-libstdcxx-time=yes",
"--enable-stage1-checking",
"--enable-checking=release",
"--enable-lto",
```

run your boxen and everything should be fine

**Comment by DomT4** [comment]
Oh. Probably need to backport the fix from Homebrew/homebrew in https://github.com/Homebrew/homebrew/pull/38596. Anyone feel up to submitting a PR to backport that line?

**Comment by leonardoobaptistaa** [comment]
Done https://github.com/Homebrew/homebrew-versions/pull/778

**Comment by DomT4** [comment]
Thanks!

**Comment by rypit** [comment]
Had this issue on a brand new early 2015 MBP

**Comment by DomT4** [comment]
Closed by https://github.com/Homebrew/homebrew-versions/commit/39bf54ee10abe192228438257c4b5fac3693a751.
