### ISSUE TITLE
Could please update the mongodb.rb formula to the version 3.0.0

### ISSUE THREAD

**Issue by warm200** [Homebrew/homebrew-versions#761]
because I can't find any brew version can support older version homebrew, I try to configure it manually ,but I am new to mongodb , it always pump out the errors.  Thank you !

**Comment by warm200** [comment]
change a little

**Comment by DomT4** [comment]
3.0.1 was merged into Homebrew/homebrew a couple days back in https://github.com/Homebrew/homebrew/pull/37888.

Are you asking for a 3.0.0 to be created here? It'd be an unusual case. We usually support branches rather than point releases.
