### ISSUE TITLE
protobuf250 failed to build on 10.10.2

### ISSUE THREAD

**Issue by mikemcquaid** [Homebrew/homebrew-versions#771]
_From @lsankar4033 on April 13, 2015 23:34_

https://gist.github.com/anonymous/9c0ebca2e6ccd63bd404

_Copied from original issue: Homebrew/homebrew#38629_

**Comment by mistydemeo** [comment]
This is a duplicate of Homebrew/homebrew#38514 - it's the CLT 6.3 header issue.
