### ISSUE TITLE
Failed to install posgis20

### ISSUE THREAD

**Issue by PixelDuck** [Homebrew/homebrew-versions#772]
Hi
I spent 4 hours trying to install posgis on a postgres 9.2 installation (done with homebrew) but 
can'f figure how to solve my issue.
I am on Yosemite and use the last version of homebrew
```
brew install -vd postgis20
...
configure: error: Cannot find json dev files in "/usr/local/opt/json-c"
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: ./configure --disable-dependency-tracking --with-projdir=/usr/local --with-jsondir=/usr/local/opt/json-c --with-pgconfig=/usr/local/Cellar/postgresql92/9.2.8_1/bin/pg_config --disable-nls

but json-c is installed properly:
xxxxxx@xxxxxx /usr/lib $ ls -all /usr/local/opt/json-c/lib/
total 352
drwxr-xr-x 6 xxxxxx admin 204B 13 Apr 16:55 ./
drwxr-xr-x 11 xxxxxx admin 374B 13 Apr 16:55 ../
-r--r--r-- 1 xxxxxx admin 76K 13 Apr 16:55 libjson-c.2.dylib
-r--r--r-- 1 xxxxxx admin 90K 13 Apr 16:55 libjson-c.a
lrwxr-xr-x 1 xxxxxx admin 17B 13 Apr 16:55 libjson-c.dylib@ -> libjson-c.2.dylib
drwxr-xr-x 3 xxxxxx admin 102B 13 Apr 16:55 pkgconfig/
```
Can someone help me?

**Comment by PixelDuck** [comment]
Hi

Just try your last version of postgis20 formula
json-c issue is fixed but now i get an issue with liblwgeom which seems in conflict with another version of the library

clang -I/usr/local/Cellar/ossp-uuid/1.6.2_1/include/ossp -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv  -bundle -multiply_defined suppress -o postgis-2.0.so postgis_module.o lwgeom_accum.o lwgeom_spheroid.o lwgeom_ogc.o lwgeom_functions_analytic.o lwgeom_inout.o lwgeom_functions_basic.o lwgeom_btree.o lwgeom_box.o lwgeom_box3d.o lwgeom_cache.o lwgeom_geos.o lwgeom_geos_prepared.o lwgeom_geos_clean.o lwgeom_geos_relatematch.o lwgeom_export.o lwgeom_in_gml.o lwgeom_in_kml.o lwgeom_in_geojson.o lwgeom_triggers.o lwgeom_dump.o lwgeom_functions_lrs.o long_xact.o lwgeom_sqlmm.o lwgeom_rtree.o lwgeom_transform.o gserialized_typmod.o gserialized_gist_2d.o gserialized_gist_nd.o geography_inout.o geography_btree.o geography_estimate.o geography_measurement.o geometry_estimate.o  -L/usr/local/Cellar/postgresql92/9.2.8_1/lib -L/usr/local/Cellar/ossp-uuid/1.6.2_1/lib  -Wl,-dead_strip_dylibs   ../liblwgeom/.libs/liblwgeom.a ../libpgcommon/libpgcommon.a  -L/usr/local/Cellar/geos/3.4.2/lib -L/usr/local/lib -lgeos_c -lproj -L/usr/local/opt/json-c/lib -ljson-c -L/usr/local/Cellar/libxml2/2.9.2/lib -lxml2 -lz -lpthread -liconv -lm  -bundle_loader /usr/local/Cellar/postgresql92/9.2.8_1/bin/postgres
Undefined symbols for architecture x86_64:
  "_json_tokener_errors", referenced from:
      _geom_from_geojson in lwgeom_in_geojson.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [postgis-2.0.so] Error 1
make: *** [all] Error 1
==> Formula
Tap: homebrew/homebrew-versions
Path: /usr/local/Library/Taps/homebrew/homebrew-versions/postgis20.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: e31bf9cfb76dfcf1774ac2ccd29c07b7fb0302b4
Last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit haswell
OS X: 10.10.3-x86_64
Xcode: N/A
CLT: 6.3.0.0.1.1428348375
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.7.0_67
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
CMAKE_PREFIX_PATH: /usr/local/opt/openssl:/usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local/opt/libxml2:/usr/local/opt/liblwgeom:/usr/local
CMAKE_INCLUDE_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/python/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/ossp-uuid/lib/pkgconfig:/usr/local/opt/proj/lib/pkgconfig:/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/freexl/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig:/usr/local/opt/json-c/lib/pkgconfig:/usr/local/opt/libspatialite/lib/pkgconfig:/usr/local/opt/gdal/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
ACLOCAL_PATH: /usr/local/opt/libxml2/share/aclocal:/usr/local/share/aclocal
PATH: /usr/local/opt/python/bin:/usr/local/Library/ENV/4.3:/usr/local/opt/autoconf/bin:/usr/local/opt/automake/bin:/usr/local/opt/libtool/bin:/usr/local/opt/gpp/bin:/usr/local/opt/openssl/bin:/usr/local/opt/ossp-uuid/bin:/usr/local/opt/postgresql92/bin:/usr/local/opt/proj/bin:/usr/local/opt/geos/bin:/usr/local/opt/libpng/bin:/usr/local/opt/jpeg/bin:/usr/local/opt/giflib/bin:/usr/local/opt/libtiff/bin:/usr/local/opt/libgeotiff/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/libxml2/bin:/usr/local/opt/gdal/bin:/usr/local/opt/python/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: postgis20 2.0.7 did not build
Logs:
     /Users/olmartin/Library/Logs/Homebrew/postgis20/01.autogen.sh
     /Users/olmartin/Library/Logs/Homebrew/postgis20/02.configure
     /Users/olmartin/Library/Logs/Homebrew/postgis20/02.configure.cc
     /Users/olmartin/Library/Logs/Homebrew/postgis20/03.make
     /Users/olmartin/Library/Logs/Homebrew/postgis20/03.make.cc
     /Users/olmartin/Library/Logs/Homebrew/postgis20/config.log

**Comment by DomT4** [comment]
Weird. I got that error last night *before* updating, but never saw it again after updating, and none of the bots hit it either. How are you building it?

**Comment by PixelDuck** [comment]
postgres9.2 is already install through home brew
i am just executing
brew -v install postgis20

**Comment by DomT4** [comment]
Try ` brew remove postgresql92 proj geos gdal && brew install postgis20 `. It'll drag back in all the deps automatically. The deps are all bottled, so removing them won't actually slow down your build by more than a few seconds.

**Comment by PixelDuck** [comment]
still the same issue:
$ brew remove postgresql92 proj geos gdal && brew install postgis20
Uninstalling /usr/local/Cellar/postgresql92/9.2.8_1... (2852 files, 37M)
Uninstalling /usr/local/Cellar/proj/4.8.0... (47 files, 5.7M)
Uninstalling /usr/local/Cellar/geos/3.4.2... (385 files, 8.4M)
Uninstalling /usr/local/Cellar/gdal/1.11.1_3... (229 files, 34M)
gdal 1.11.0 is still installed.
Remove them all with `brew uninstall --force gdal`.
==> Installing postgis20 from homebrew/homebrew-versions
==> Installing dependencies for postgis20: postgresql92, proj, geos, gdal
==> Installing postgis20 dependency: postgresql92
==> Downloading https://homebrew.bintray.com/bottles-versions/postgresql92-9.2.8_1.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/postgresql92-9.2.8_1.yosemite.bottle.tar.gz
==> Pouring postgresql92-9.2.8_1.yosemite.bottle.tar.gz
==> Caveats
initdb /usr/local/var/postgres -E utf8    # create a database
postgres -D /usr/local/var/postgres       # serve that database
PGDATA=/usr/local/var/postgres postgres   # ...alternatively

If builds of PostgreSQL 9 are failing and you have version 8.x installed,
you may need to remove the previous version first. See:
  https://github.com/mxcl/homebrew/issues/issue/2510

To migrate existing data from a previous major version (pre-9.2) of PostgreSQL, see:
  http://www.postgresql.org/docs/9.2/static/upgrading.html

Some machines may require provisioning of shared memory:
  http://www.postgresql.org/docs/9.2/static/kernel-resources.html#SYSVIPC

When installing the postgres gem, including ARCHFLAGS is recommended:
  ARCHFLAGS="-arch x86_64" gem install pg

To install gems without sudo, see the Homebrew wiki.

To have launchd start postgresql92 at login:
    ln -sfv /usr/local/opt/postgresql92/*.plist ~/Library/LaunchAgents
Then to load postgresql92 now:
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql92.plist
Or, if you don't want/need launchctl, you can just run:
    pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
==> Summary
🍺  /usr/local/Cellar/postgresql92/9.2.8_1: 2852 files, 37M
==> Installing postgis20 dependency: proj
==> Downloading https://homebrew.bintray.com/bottles/proj-4.8.0.yosemite.bottle.2.tar.gz
######################################################################## 100.0%
==> Pouring proj-4.8.0.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/proj/4.8.0: 47 files, 5.7M
==> Installing postgis20 dependency: geos
==> Downloading https://homebrew.bintray.com/bottles/geos-3.4.2.yosemite.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring geos-3.4.2.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/geos/3.4.2: 385 files, 8.5M
==> Installing postgis20 dependency: gdal
==> Downloading https://homebrew.bintray.com/bottles/gdal-1.11.1_3.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/gdal-1.11.1_3.yosemite.bottle.tar.gz
==> Pouring gdal-1.11.1_3.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/gdal/1.11.1_3: 229 files, 34M
==> Installing postgis20
==> Downloading http://download.osgeo.org/postgis/source/postgis-2.0.7.tar.gz
Already downloaded: /Library/Caches/Homebrew/postgis20-2.0.7.tar.gz
==> Patching
patching file configure.ac
==> ./autogen.sh
==> ./configure --with-projdir=/usr/local --with-jsondir=/usr/local/opt/json-c --with-pgconfig=/usr/local/Cellar/postgresql92/9.2.8_1/bin/pg_config --disable-nls
==> make
      _geom_from_geojson in lwgeom_in_geojson.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [postgis-2.0.so] Error 1
make: *** [all] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-versions/issues

**Comment by DomT4** [comment]
> gdal 1.11.0 is still installed.

This is interesting. I can't reproduce with a "clean" system. If you're not intentionally keeping old stuff around, can you do ` brew cleanup && brew prune ` and try again?

**Comment by PixelDuck** [comment]
ok i will try
Some people have this kind of issue 
and it seems that adding the code above could solve it
I am not familiar with homebrew so maybe it could make sense for you 

# Architecture isn't detected correctly on 32bit Snow Leopard without help
ENV["OBJARCH"] = MacOS.prefer_64_bit? ? "-arch x86_64" : "-arch i386"

**Comment by PixelDuck** [comment]
same issue with brew cleanup && brew prune

**Comment by DomT4** [comment]
Still can't reproduce this. Try going a little more extreme:

` brew remove postgresql92 liblwgeom libspatialite gdal json-c && brew install postgis20 `. The problem for you seems to be ` liblwgeom ` in particular, although I'm not sure why. Bottles needing bumping would usually be the suspect, but even from bottles I can't reproduce your issue locally.

**Comment by PixelDuck** [comment]
Not working
Are you on Yosemite like me?

**Comment by DomT4** [comment]
Yup. Only difference in our systems is Java version, Ruby version and I have Xcode installed. The first two definitely shouldn't be impacting anything, and I can't imagine Xcode is the solution here either. Any thoughts @mikemcquaid?

**Comment by mikemcquaid** [comment]
Could be Java version.

**Comment by DomT4** [comment]
Funky. Didn't think any of these formulae touched Java, but I've been pouring bottles rather than building from source in this case so wouldn't have noticed. Could be worth a shot.

**Comment by PixelDuck** [comment]
i am surprise too
which java version should i set? i have several installed locally

**Comment by DomT4** [comment]
` 1.8.0_45 ` is what I'm running locally.

**Comment by PixelDuck** [comment]
i have the same issue with java 1.8.0_45 :(

**Comment by DomT4** [comment]
Rats. Does the issue still persist after a ` brew update && brew upgrade `? A couple of the deps had their bottles bumped the other day. Might have helped :confounded:.

**Comment by PixelDuck** [comment]
Good news!
I finally succeed to install postgis20
This required me to uninstall json-c 0.12 and force the installation of json-c 0.11
I just edit the formula to:

#  url "https://github.com/json-c/json-c/archive/json-c-0.12-20140410.tar.gz"
#  version "0.12"
#  sha256 "99304a4a633f1ee281d6a521155a182824dd995139d5ed6ee5c93093c281092b"
  url 'https://github.com/json-c/json-c/archive/json-c-0.11-20130402.tar.gz'
  version '0.11'
  sha1 '1910e10ea57a743ec576688700df4a0cabbe64ba'

then i have installed json-c 0.11

and the compilation of postgis works

thanks a lot for your help

**Comment by DomT4** [comment]
Strange. Upstream said they'd backported the 0.12 fixes to this branch. If you hit any further problems, it's potentially worth giving upstream a nudge on the json situation. Glad all is working for you now though.

**Comment by PixelDuck** [comment]
how can i contact them?

**Comment by DomT4** [comment]
Either file a ticket or drop the users mailing list your query. Both links can be found [here](http://postgis.net/support).

**Comment by diwarrior** [comment]
1) Open your terminal then : sudo xcode-select -switch /Library/Developer/CommandLineTools

2) sudo cp /Library/Developer/CommandLineTools/usr/bin/install_name_tool /usr/bin/install_name_tool


==> You should get it work!
