### ISSUE TITLE
Installing subversion17 with python bindings fails under 10.10

### ISSUE THREAD

**Issue by sakra** [Homebrew/homebrew-versions#777]
$ brew install subversion17 --with-python
	==> Installing subversion17 from homebrew/homebrew-versions
	==> Downloading https://archive.apache.org/dist/subversion/subversion-1.7.14.tar.bz2
	Already downloaded: /Library/Caches/Homebrew/subversion17-1.7.14.tar.bz2
	==> Downloading https://serf.googlecode.com/files/serf-1.3.3.tar.bz2
	Already downloaded: /Library/Caches/Homebrew/subversion17--serf-1.3.3.tar.bz2
	==> /usr/local/opt/scons/bin/scons PREFIX=/usr/local/Cellar/subversion17/1.7.14_1/libexec/serf GSSAPI=/usr CC=/usr/bin/clang CFLAGS=-Os -w -pipe -march=native -mmacosx-version-min=10.
	==> /usr/local/opt/scons/bin/scons install
	==> ./configure --prefix=/usr/local/Cellar/subversion17/1.7.14_1 --with-zlib=/usr --with-sqlite=/usr/local/opt/sqlite --with-ssl=/usr/local/opt/openssl --with-serf=/usr/local/Cellar/s
	==> make
	==> make install
	==> make tools
	==> make install-tools
	==> make swig-py
	ld: warning: ignoring file /usr/local/opt/sqlite/lib/libsqlite3.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/opt/sqlite/lib/libsqlite3.dylib
	ld: warning: ignoring file /usr/local/Cellar/apr/1.5.1/libexec/lib/libapr-1.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/Cellar/apr/1.5.1/libexec/lib/libapr-1.dylib
	ld: in '/usr/local/opt/sqlite/lib/libsqlite3.dylib', file was built for x86_64 which is not the architecture being linked (i386): /usr/local/opt/sqlite/lib/libsqlite3.dylib for architecture i386
	clang: error: linker command failed with exit code 1 (use -v to see invocation)
	make: *** [subversion/bindings/swig/python/_core.la] Error 1

**Comment by DomT4** [comment]
` brew gist-logs subversion17 ` please.

**Comment by sakra** [comment]
https://gist.github.com/349206663792c7818616

I figured out what the problem was. Subversion 1.7 is built with the homebrew provided sqlite. When build with `--with-python` sqlite is required to be universal. Homebrew does not build sqlite as a universal binary when it is installed as a side-effect of installing Subversion 1.7.

**Comment by DomT4** [comment]
Odd. I don't think I've seen that reported before. Presumably tacking on ` brew install subversion17 --with-python --universal ` resolves the build problem?

**Comment by sakra** [comment]
I did a manual reinstall of sqlite with `brew install sqlite --universal` followed by `brew install subversion17 --universal`. That did the trick.

**Comment by DomT4** [comment]
Interesting. That's something we could always note in the formula, that installing with Python requires a universal sqlite. We do a similar notice with Java already. Have we seen this before @Homebrew/owners?

**Comment by tdsmith** [comment]
Guessing sqlite needs to be universal iff python is universal; Homebrew python isn't but system python is.

**Comment by DomT4** [comment]
Yeah, we've historically tied the Subversion formulae to Homebrew's Python. 

Perhaps we could do something like this?

```ruby
if build.with "python"
  opoo "You must build subversion17 --universal when building with Python"
end
```

**Comment by DomT4** [comment]
@tdsmith Thoughts on #779?
