### ISSUE TITLE
redis28 does NOT install redis28.conf

### ISSUE THREAD

**Issue by joelpresence** [Homebrew/homebrew-versions#787]
Thanks for creating redis28 - this allows me to test against the version of Redis used by AWS Elasticache.

However, there is a bug in redis28 - it claims that it installs the conf file as /usr/local/etc/redis28.conf however it does not.  In fact, there is no redis28.conf or redis.conf anywhere on my mac.

I have verified this twice on two different Macs both running the latest version of Yosemite (10.10.3 with all the updates).

This DOES not happen with the plain redis brew that I've installed other times.  Only with redis28.

There seems to be a bug in the install.  Can somebody please look into this?

Thanks!

See also https://github.com/Homebrew/homebrew-versions/pull/746

**Comment by DomT4** [comment]
Aye. Confirmed. This is *usually* just a simple bottle error - To test that I've opened #788. If the error reproduces, we can try more drastic things.

**Comment by DomT4** [comment]
Was a bottle error. Fixed now. ` brew reinstall redis28 ` should solve the problem. Thanks for the report!

**Comment by joelpresence** [comment]
My pleasure to report, thanks for all of your hard work.

Thanks for looking into this.

I just did a `brew reinstall redis28` and there is still *no* file `/usr/local/etc/redis28.conf`  😔

Any ideas why?

Thanks again.

**Comment by DomT4** [comment]
:scream: Are you sure? It's definitely there in the bottle, I checked all three bottles personally.

Can you do ` brew update && brew upgrade && brew reinstall redis28 && brew test --verbose redis28 `? Thanks!

**Comment by joelpresence** [comment]
OOPS, sorry, I didn't realize I had to do `brew update` first.  I just did `brew update; brew reinstall redis28` and now it's there.

Thanks for fixing this.

Good to close the issue.

**Comment by DomT4** [comment]
Phew. Great news. Glad all is working!
