### ISSUE TITLE
subversion17 can't access the repository via https

### ISSUE THREAD

**Issue by knowledgecode** [Homebrew/homebrew-versions#790]
Built the 1.7.14_1 bottle with `--with-unicode-path` option in OS X 10.10.3.
```shell
$ brew install subversion17 --with-unicode-path
```
And then tried to checkout the repository via https, but occurred error:
```shell
$ svn checkout https://example.com/foobar/
svn: E175000: Unable to connect to a repository at URL 'https://example.com/foobar/'
svn: E175000: SSL is not supported
```
I guess that the cause of this is `neon` is not built with SSL option.
```shell
$ svn --version
svn, version 1.7.14 (r1542130)
   compiled Apr 23 2015, 22:22:39

Copyright (C) 2013 The Apache Software Foundation.
This software consists of contributions made by many people; see the NOTICE
file for more information.
Subversion is open source software, see http://subversion.apache.org/

The following repository access (RA) modules are available:

* ra_neon : Module for accessing a repository via WebDAV protocol using Neon.
  - handles 'http' scheme
* ra_svn : Module for accessing a repository using the svn network protocol.
  - with Cyrus SASL authentication
  - handles 'svn' scheme
* ra_local : Module for accessing a repository on local disk.
  - handles 'file' scheme
* ra_serf : Module for accessing a repository via WebDAV protocol using serf.
  - handles 'http' scheme
  - handles 'https' scheme
```

**Comment by DomT4** [comment]
Aye. This is a known thing, sadly. Subversion17 (and 16) refuse to recognise a Neon newer than the ones they shipped with, and disabling the version check on that has led to other problems in the past, such as the whole thing throwing fatal failures at runtime and rendering the formulae involved useless, heh.

So we're tied to an old ` neon ` on that - But trying to compile that old ` neon ` with Homebrew's newer ` OpenSSL ` led to compile failure galore. I'll look into it some more, but I'm not super super hopeful on any reasonable solution here.

**Comment by DomT4** [comment]
Aye. We're not going to be able to do anything on this by the looks of it. It's looking for SSLv2 in compile, which you won't find in any OpenSSL shipped by Homebrew (Or Debian, or Ubuntu, etc) -

```
Undefined symbols for architecture x86_64:
  "_SSLv2_server_method", referenced from:
      _ne_ssl_context_create in ne_openssl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libneon.la] Error 1
make: *** [subdirs] Error 2
```

I would be uncomfortable vendoring an SSLv2 enabled OpenSSL for the older Subversions and Neons. CC @Homebrew/owners for thoughts though.

**Comment by mikemcquaid** [comment]
Yeh, feels a bit weird.

**Comment by tdsmith** [comment]
Can it use system openssl?

**Comment by DomT4** [comment]
> Can it use system openssl?

Should be possible, theoretically. Apple still ships *some* SSLv2 ciphers.

**Comment by mikemcquaid** [comment]
That seems like a good idea :+1:

**Comment by DomT4** [comment]
Do we want to hurl a ` caveat ` or anything in given the system OpenSSL situation?

**Comment by tdsmith** [comment]
If you have specific concerns you could enumerate them in a caveat (but I think probably not?).

**Comment by DomT4** [comment]
Well, I have specific concerns that it's using outdated, well-regarded-insecure ciphers which share roughly the security benefit of yelling your bank details out of an open window, but :wink:.

**Comment by tdsmith** [comment]
It probably isn't, though; that's a server configuration issue. If system OpenSSL were e.g. vulnerable to downgrade attacks maybe that's another story.

**Comment by DomT4** [comment]
System OpenSSL is going to die in terms of upstream support at the end of this year. I guess my question is, after the first major security problem is announced post December 2015 for OpenSSL, what do we do with the `subversion16` and `subversion17` formulae?

**Comment by tdsmith** [comment]
I'd spike 'em.

**Comment by DomT4** [comment]
Alright. I can live with supporting them until that point.

**Comment by knowledgecode** [comment]
Got it. Thanks! :smile:

**Comment by DomT4** [comment]
It's fixed for now. ` brew update && brew reinstall subversion17 ` should allow you to checkout SSL/TLS repos again.
