### ISSUE TITLE
gst-plugins-bad010 fails to build (vp8)

### ISSUE THREAD

**Issue by mounteerie** [Homebrew/homebrew-versions#799]
full make log: https://gist.github.com/Tuxed0/103a4e4f5c23f7845c07

> /Applications/Xcode.app/Contents/Developer/usr/bin/make -C vp8
  CC     libgstvp8_la-gstvp8dec.lo
  CC     libgstvp8_la-gstvp8enc.lo
gstvp8enc.c:848:16: error: use of undeclared identifier 'IMG_FMT_I420'; did you mean 'VPX_IMG_FMT_I420'?
  image->fmt = VPX_IMG_FMT_I420;
               ^~~~~~~~~~~~~~~~
               VPX_IMG_FMT_I420
./gstvp8utils.h:30:26: note: expanded from macro 'VPX_IMG_FMT_I420'
#define VPX_IMG_FMT_I420 IMG_FMT_I420
                         ^
/usr/local/include/vpx/./vpx_image.h:56:5: note: 'VPX_IMG_FMT_I420' declared here
    VPX_IMG_FMT_I420    = VPX_IMG_FMT_PLANAR | 2,
    ^
1 error generated.
make[3]: *** [libgstvp8_la-gstvp8enc.lo] Error 1
make[2]: *** [vp8] Error 2

**Comment by mistydemeo** [comment]
Can you provide the output of `brew gist-logs gst-plugins-bad010`, please?

**Comment by Tuxed0** [comment]
sure, here's the output: https://gist.github.com/anonymous/57419444af80705ec836

**Comment by i8degrees** [comment]
I haven't done any testing or research regarding the build issue, but by commenting out the preprocessor define for ```VPX_IMG_FMT_I420``` in ```gstvp8utils.h```, I was able to get the formula to finish building, yielding a functional mopidy build for me. 

Curiously, note that ```/usr/local/include/vpx/./vpx_image.h``` defines ```VPX_IMG_FMT_I420```, which is included in ```gstvp8utils.h```

To test that this change has no ill effect, I'm **guessing** that one would simply need to play a VP8 encoded audio file from their local mopidy library collection?

**Comment by kgs** [comment]
I have excatly the same error - where should I comment out preprocessor define? I can find source code only in tarball format in /Library/Caches/Homebrew

**Comment by i8degrees** [comment]
@kgs You should comment out the line starting with #define VPX_IMG_FMT_I420

This is me going entirely by memory. Good luck!

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
