### ISSUE TITLE
plowshare3 urls don't work

### ISSUE THREAD

**Issue by stefanschmidt** [Homebrew/homebrew-versions#803]
The snapshot url of `plowshare3` returns an error and the repository seems to be private now. It looks like the project migrated to Github (or was forked), at least that is where the [plowshare](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/plowshare.rb) formula is pointing to.

    $ curl -I https://plowshare.googlecode.com/files/plowshare3-snapshot-git20131103.89c1220.tar.gz
    HTTP/1.1 404 Not Found

    $ curl -I https://code.google.com/p/plowshare/
    HTTP/1.1 302 Found
    Location: https://www.google.com/accounts/ServiceLogin?service=code&ltmpl=phosting&continue=https%3A%2F%2Fcode.google.com%2Fp%2Fplowshare%2F

**Comment by DomT4** [comment]
Aye, It doesn't seem to exist anymore, or it's been made private.

It looks like upstream haven't carried across the `plowshare3` downloads to the new Github repo. I can't find a copy of any `plowshare3` download on Ubuntu, MacPorts or Debian - So we probably need to ask upstream to pop the download back up, or set fire to the formula. The former obviously being more desirable than the latter.

**Comment by DomT4** [comment]
Any movement upstream on this?
