### ISSUE TITLE
gnupg21 fails to build

### ISSUE THREAD

**Issue by Midar** [Homebrew/homebrew-versions#810]
With all dependencies at the current version, gnupg21 fails to build because the checks fail. This is happening with GnuPG 2.1.3, but also with 2.1.2 which was fine before. GnuPG 2.0 still seems to build fine.

**Comment by Midar** [comment]
This seems to be caused by b95f27ce9f956c56d080b6dc29ba8efb841c6690

**Comment by DomT4** [comment]
Yup. Well spotted. I've left a comment on https://github.com/Homebrew/homebrew/commit/b95f27ce9f956c56d080b6dc29ba8efb841c6690. I'll probably upstream it to GnuPG as well.

**Comment by Midar** [comment]
Please revert this, this is the worst idea ever. Disabling tests in a security product results in catastrophic results as the user things everything is working while in fact it is now. Users rely on crypto, just letting them think it works when it doesn't is extremely evil.

**Comment by DomT4** [comment]
Extremely evil? Get a grip.

1) I reported and discussed this upstream with Homebrew.
2) I read through an entire discussion thread on the GnuPG mailing lists and emailed Werner with a follow up. If you'd read the thread you'd see on certain platforms it already isn't possible to enable the tests. Are those maintainers evil as well?
3) It hasn't even been merged yet, which again, you could have fairly easily checked by looking at the commit list.

Before swinging accusations around, if you could have some basis of fact, that'd be appreciated.
