### ISSUE TITLE
brew info lua53 lists broken install options

### ISSUE THREAD

**Issue by gsteemso** [Homebrew/homebrew-versions#817]
Trying to install lua53 with either of the options “--with-completion” and “with-default-names” fails horribly. If you try to install with advanced readline support it attempts to patch the lua 5.3 source using the lua 5.2 patches, and of course fails on two of the three. If you skip that and just try to install with default names, it dies painfully when trying to process the luarocks package, complaining that the lua.h file is missing.

Prior to trying any of this I deleted my DIY’d lua 5.3 install (it was working but Homebrew wouldn’t let me “brew update” because of the conflicting “lua” formula), so there wouldn’t have been anything hanging around to interfere.

**Comment by DomT4** [comment]
> If you try to install with advanced readline support it attempts to patch the lua 5.3 source using the lua 5.2 patches, and of course fails on two of the three.

Yeah, this shouldn't have snuck into the `lua53` formula in the first place, Sorry.

> If you skip that and just try to install with default names, it dies painfully when trying to process the luarocks package, complaining that the lua.h file is missing.

Interesting. Looking into that ASAP.
