### ISSUE TITLE
The `versions` command is no longer supported.

### ISSUE THREAD

**Issue by SimonQian** [Homebrew/homebrew-versions#822]
I want to install node 0.6.0, and I use homebrew-versions.
------------------------------------------------------------------------------
$ brew tap homebrew/versions
Warning: Already tapped!
------------------------------------------------------------------------------
when I versions node, then error:
------------------------------------------------------------------------------
$ brew versions node
Error: The `versions` command is no longer supported.
You can use the homebrew-versions tap instead:
  https://github.com/Homebrew/homebrew-versions
Or use `brew log` to browse the git history.
-------------------------------------------------------------------------------

what's the matter??

**Comment by DomT4** [comment]
`brew versions` has been deprecated for a while. You just want `brew install node06` I'd presume.

`brew log` still works here - If `brew log` isn't working on your machine you need to report that to Homebrew/homebrew.

**Comment by SimonQian** [comment]
this is my setps:
1.
$ brew install node06
==> Installing node06 from homebrew/homebrew-versions
==> Downloading https://homebrew.bintray.com/bottles-versions/node06-0.6.21_1.yosemite.bottle.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/node06-0.6.21_1.yosemite.bottle.1.tar.gz
==> Pouring node06-0.6.21_1.yosemite.bottle.1.tar.gz
==> Caveats
Homebrew has NOT installed npm.

After installing, add the following path to your NODE_PATH environment
variable to have npm libraries picked up:
  /usr/local/lib/node_modules
==> Summary
🍺  /usr/local/Cellar/node06/0.6.21_1: 80 files, 7.5M

2.
$ node -v
v0.6.21-pre

3.
$ npm -v

util.js:511
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.inherits (util.js:511:43)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:115:6)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/log.js:2:16)
    at Module._compile (module.js:446:26)

------------
npm isn't work. I don't know why. 
can you help me? thanks a lot!

**Comment by DomT4** [comment]
As the formula says, for `node06` we don't install `npm` with the formula. If you have an `npm` there from a more recent Node there's no guarantee it will function as expected, desired or hoped. I don't know if upstream `npm` even support `node06` any more, to be honest.

You can try an older version of `npm`, or you could try opening an issue upstream at `npm` and asking if anything needs fixing/etc. There's not much Homebrew can do on the `npm` failure here.

**Comment by SimonQian** [comment]
oh, I see. that's brew install node06 don't install npm.
In short, thank you!
