### ISSUE TITLE
bash-completion2: New installs don't symlinks brew completion into the completions folder

### ISSUE THREAD

**Issue by elyscape** [Homebrew/homebrew-versions#834]
Commit e17d720, which adds bottles to the bash-completion2 formula, makes it so that new installs don't [set up the symlink for brew completion](https://github.com/Homebrew/homebrew-versions/blob/e17d720cf55ae76a7000fb99e0e6d3b5c32df51b/bash-completion2.rb#L55-L57).

**Comment by aw1621107** [comment]
This broke again on 10.11. Brew alias points to itself, which points to itself, which points to itself, etc...
