### ISSUE TITLE
Edited Boost 149 formula, but edits not being used on install

### ISSUE THREAD

**Issue by lauraannwilliams** [Homebrew/homebrew-versions#835]
Hi

I made a change to the boost 149 formula using brew edit boost149  to change the bjam option from layout=tagged to layout=system

However, when I install boost149, it still uses layout=tagged 

I've attached the brew gist-logs output: 
 https://gist.githubusercontent.com/anonymous/cdd28ba4b8ee62a68d45
You can see in the bjam.2 file that it is still using tagged

`
./bjam
--prefix=/usr/local/Cellar/boost149/1.49.0
--libdir=/usr/local/Cellar/boost149/1.49.0/lib
-d2
-j8
--layout=tagged
--user-config=user-config.jam
threading=multi
install
address-model=32_64
architecture=x86
pch=off
`

My edited formula and install output are here

https://gist.github.com/lauraannwilliams/6b5bc191e78db6fd616c

**Comment by jacknagel** [comment]
>My edited formula and install output are here
>
>https://gist.github.com/lauraannwilliams/6b5bc191e78db6fd616c

You need to pass `--build-from-source`; without it, you are installing the prebuilt binary. There aren't any logs generated when doing this, so it's likely your gist-logs output is from a different build that did not contain the edits you made to the formula.

**Comment by lauraannwilliams** [comment]
Thank you very much, this solved my issue. I didn't see anything about having to build from source in the 'Can I edit formulae myself?' faq. I will keep this in mind for future.
