### ISSUE TITLE
Linuxbrew-specific patches

### ISSUE THREAD

**Issue by DoomHammer** [Homebrew/homebrew-versions#841]
I have recently started using Linuxbrew, a port of Homebrew targetting Linux systems and I am absolutely in love with it. Linuxbrew repository contains formulas (I prefer this to formulae) with Linux-specific patches if appliable.

Now, beside main formula repository in homebrew/homebrew there are several Taps like homebrew-versions that contain useful software which for one reason or another cannot go into main repository.

What is the correct way to patch those formulas with Linux-specific code? Should the whole project be forked?

**Comment by sjackman** [comment]
See also https://github.com/Homebrew/homebrew-dupes/pull/463 for a relevant discussion

**Comment by DomT4** [comment]
Will defer to @Homebrew/owners, but in principle I don't have a huge problem with it. I'd like someone from Linuxbrew around more regularly if we were :+1: on accepting Linux-based fixes, primarily because I use `apt` on Debian and don't have the time to chase down Linux stuff for Versions as well.

**Comment by mikemcquaid** [comment]
It depends what the patches are needed for, really, so would need evaluated on a case-by-case basis.

**Comment by DomT4** [comment]
Cool. Closing here in that case. Feel free to submit patches/changes to formulae and we'll review them individually.

**Comment by sjackman** [comment]
Sounds good.
