### ISSUE TITLE
Sha256 mismatch installing homebrew/versions/gst-plugins-base010

### ISSUE THREAD

**Issue by scwood** [Homebrew/homebrew-versions#845]
While trying to install mopidy I get this error:

```
$ brew install mopidy
==> Installing mopidy from mopidy/homebrew-mopidy
==> Installing dependencies for mopidy/mopidy/mopidy: homebrew/versions/gst-plugins-base010, libpng, freetype, fontconfig, pixman, cairo, flac, jpeg, speex, libshout, intltool, gsettings-desk
==> Installing mopidy/mopidy/mopidy dependency: homebrew/versions/gst-plugins-base010
==> Downloading http://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-0.10.36.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gst-plugins-base010-0.10.36.tar.bz2
Error: SHA256 mismatch
Expected: 2cd3b0fa8e9b595db8f514ef7c2bdbcd639a0d63d154c00f8c9b609321f49976
Actual: f88788fe8350ac07dfb4d49f51fffd8aca9f1d3285003df12edb6d2d90d50f5c
Archive: /Library/Caches/Homebrew/gst-plugins-base010-0.10.36.tar.bz2
To retry an incomplete download, remove the file above.
```

Slightly confused as this already exists on my system. I've deleted the download and retried a couple of times. What am I missing here?

**Comment by DomT4** [comment]
Can't repro here:

```
==> Fetching gst-plugins-base010 from homebrew/homebrew-versions
==> Downloading http://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-0.10.36.tar.bz2
######################################################################## 100.0%
Downloaded to: /usr/local/var/homebrew/cache/gst-plugins-base010-0.10.36.tar.bz2
SHA1: e675401b62a6bf2e5ea966e833afd005a585e978
SHA256: 2cd3b0fa8e9b595db8f514ef7c2bdbcd639a0d63d154c00f8c9b609321f49976
```

Any chance you have a `.curlrc` file present? `brew doctor` should warn if you do.

**Comment by scwood** [comment]
Nope. 
```
$ brew doctor
Your system is ready to brew.
```
`brew install homebrew/versions/gst-plugins-base010` installs just fine, could this be a mopidy issue?

**Comment by scwood** [comment]
```
$ brew fetch homebrew/versions/gst-plugins-base010
==> Fetching gst-plugins-base010 from homebrew/homebrew-versions
==> Downloading https://homebrew.bintray.com/bottles-versions/gst-plugins-base010-0.10.36.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/gst-plugins-base010-0.10.36.yosemite.bottle.tar.gz
SHA1: 4501a696173e650aac47ee91d91ab316df5d5f24
SHA256: a8b4f2d006de309842dba3547c64e0d8c815ab8d81786adae15e3f3c6325eab8
```

Why is my SHA256 different than yours, is my brew out of date or something? brew update returns already up-to-date

**Comment by DomT4** [comment]
> Why is my SHA256 different than yours, is my brew out of date or something? 

I'm not sure on the source download, to be honest. It could be network settings unique to your computer, It could be a temporary server or CDN glitch, it could be something local. The bottle download checksum is fine, that matches the expected checksum. Because the upstream formulae requires various non-default options you're having to build from source, which is where the checksum mismatch is occurring.

What happens if you skip the CLI completely and use your browser to do the download and then run something like `openssl dgst -sha256 /path/to/tarball`?

**Comment by scwood** [comment]
```
$ openssl dgst -sha256 /Users/spencer/Downloads/gst-plugins-base010-0.10.36.yosemite.bottle.tar
SHA256(/Users/spencer/Downloads/gst-plugins-base010-0.10.36.yosemite.bottle.tar)= 907ec7e4e28a4a99de5c419f67d6c53886995d7b1fbb3583be18d41c181d52da
```

**Comment by DomT4** [comment]
Sorry, I meant the http://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-0.10.36.tar.bz2 tarball rather than the bottle in this case. Although it'd odd that your bottle checksum came out different again there. I'd *guess* there's some network configuration issues impacting you locally. DNS seems possible.

Does `tar -tzf /path/to/tarball` reveal anything odd/unusual/unexpected about the contents? Maybe you're getting HTML files or empty tarballs for some reason.

**Comment by scwood** [comment]
d343d492a2077ddcc3b4c71f7f692103dadcfec0ee20c01a7696b3ff63697508

**Comment by scwood** [comment]
```
$ tar -tzf ~/Downloads/gst-plugins-base-0.10.36.tar.bz2
tar: Error opening archive: bzip decompression failed
```

Hmmm...

**Comment by DomT4** [comment]
I suspect you're getting empty tarballs from that and the consistently moving checksums. Is the issue still persisting now?

**Comment by scwood** [comment]
It's fixed itself, so I guess it was something weird with the network I was on. Thanks for your help!

**Comment by DomT4** [comment]
Great! No worries at all, Thanks for the report!

**Comment by micheleberg** [comment]
I'm having the same problem:

brew install glibc
==> Downloading http://ftpmirror.gnu.org/glibc/glibc-2.19.tar.bz2
==> Downloading from http://10.28.5.38:15871/cgi-bin/blockpage.cgi?ws-session=171734321
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: x
Actual: y

I've tried removing the file and executing "brew install glibc" several times, but the result is the same.  Like scwood above, my actual generated SHA256 hash is different each time.

When I ran the "file" command against the .cache/Homebrew/glibc-2.19.tar.bz2 file, the result was "HTML document text".  Is that expected on a failed attempt, or does that indicate a failed download?

brew doctor tells me that my version of Git is outdated, but glibc is a dependency for updating Git.

Could my server's firewall settings be preventing me from fetching the correct tarball?  If so, are there other sites I can try to fetch the tarball from?  If so, how do I tell linuxbrew to hit those sites instead?

**Comment by micheleberg** [comment]
I downloaded the glibc-2.19.tar.bz2 file from http://ftp.gnu.org/gnu/glibc/?O=D;C=M on another machine, then scp'd it to my server.  It's now installing without the SHA mismatch problem, so I believe that DomT4 was correct - something was preventing the successful download of the tarball.  Putting this here in case it helps someone else.

**Comment by mikemcquaid** [comment]
@micheleberg It looks a lot from http://10.28.5.38:15871/cgi-bin/blockpage.cgi?ws-session=171734321 that your ISP/employer is intentionally blocking that server.

**Comment by micheleberg** [comment]
Yeah, I (eventually) noticed that myself, which is why I tried fetching it manually and putting in my .cache to be run.  I guess they're blocking http://ftpmirror.gnu.org, but not http://ftp.gnu.org, which is where I was able to manually download it from.  Thanks @mikemcquaid.
