### ISSUE TITLE
cannot install gcc48  

### ISSUE THREAD

**Issue by baumeist** [Homebrew/homebrew-versions#857]
I'm having an issue installing gcc48.
Below is what I have tried.
Can someone please offer some help?
Thank you,
-M

$ brew install gcc48
==> Installing gcc48 from homebrew/homebrew-versions
==> Installing dependencies for homebrew/versions/gcc48: gmp4, mpfr2, libmpc08, isl011, cloog018
==> Installing homebrew/versions/gcc48 dependency: gmp4
==> Downloading https://homebrew.bintray.com/bottles-versions/gmp4-4.3.2.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gmp4-4.3.2.mavericks.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Conflicts with gmp in main repository.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/gmp4/lib
    CPPFLAGS: -I/usr/local/opt/gmp4/include

==> Summary
🍺  /usr/local/Cellar/gmp4/4.3.2: 15 files, 2.5M
==> Installing homebrew/versions/gcc48 dependency: mpfr2
==> Downloading https://homebrew.bintray.com/bottles-versions/mpfr2-2.4.2.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring mpfr2-2.4.2.mavericks.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Conflicts with mpfr in main repository.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/mpfr2/lib
    CPPFLAGS: -I/usr/local/opt/mpfr2/include

==> Summary
🍺  /usr/local/Cellar/mpfr2/2.4.2: 23 files, 2.8M
==> Installing homebrew/versions/gcc48 dependency: libmpc08
==> Downloading https://homebrew.bintray.com/bottles-versions/libmpc08-0.8.1.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libmpc08-0.8.1.mavericks.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Conflicts with libmpc in main repository.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/libmpc08/lib
    CPPFLAGS: -I/usr/local/opt/libmpc08/include

==> Summary
🍺  /usr/local/Cellar/libmpc08/0.8.1: 10 files, 304K
==> Installing homebrew/versions/gcc48 dependency: isl011
==> Downloading https://homebrew.bintray.com/bottles-versions/isl011-0.11.1.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring isl011-0.11.1.mavericks.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Conflicts with isl in main repository.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/isl011/lib
    CPPFLAGS: -I/usr/local/opt/isl011/include

==> Summary
🍺  /usr/local/Cellar/isl011/0.11.1: 52 files, 2.9M
==> Installing homebrew/versions/gcc48 dependency: cloog018
==> Downloading https://homebrew.bintray.com/bottles-versions/cloog018-0.18.0.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring cloog018-0.18.0.mavericks.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Conflicts with cloog in main repository.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/cloog018/lib
    CPPFLAGS: -I/usr/local/opt/cloog018/include

==> Summary
🍺  /usr/local/Cellar/cloog018/0.18.0: 31 files, 552K
==> Installing homebrew/versions/gcc48
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.8.4/gcc-4.8.4.tar.bz2
######################################################################## 100.0%
==> ../configure --build=x86_64-apple-darwin13.4.0 --prefix=/usr/local/Cellar/gcc48/4.8.4 --libdir=/usr/local/Cellar/gcc48/4.8.4/lib/gcc/4.8 --enable-languages=c,c++,objc,obj-c++ --progra
checking for version 0.10 of ISL... no
checking for version 0.11 of ISL... no
checking for version 0.12 of ISL... no
checking for version 0.14 of ISL... no
configure: error: Unable to find a usable ISL.  See config.log for details.
/usr/local/Library/Homebrew/build.rb:181:in `dump': can't dump anonymous class #<Module:0x007fab89bd65f0>::Gcc48 (TypeError)
	from /usr/local/Library/Homebrew/build.rb:181:in `rescue in <main>'
	from /usr/local/Library/Homebrew/build.rb:167:in `<main>'
Error: Suspicious failure

If I check to see if isl is installed: 

$ brew info isl
isl: stable 0.14.1 (bottled), HEAD
http://freecode.com/projects/isl
Not installed
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/isl.rb
==> Dependencies
Build: xz ✔
Required: gmp ✘

$ brew list
berkeley-db	cmake		gmp4		libmagic	libtasn1	ossp-uuid	rpm
cloog018	gettext		isl011		libmpc08	mpfr2		popt		xz

I ran 
brew update and 

$ brew reinstall isl011

==> Reinstalling homebrew/versions/isl011
==> Downloading https://homebrew.bintray.com/bottles-versions/isl011-0.11.1.mavericks.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/isl011-0.11.1.mavericks.bottle.tar.gz
==> Pouring isl011-0.11.1.mavericks.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Conflicts with isl in main repository.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/isl011/lib
    CPPFLAGS: -I/usr/local/opt/isl011/include

==> Summary
🍺  /usr/local/Cellar/isl011/0.11.1: 52 files, 2.9M

running brew doctor gave me:
 
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some directories in /usr/local/share/man aren't writable.
This can happen if you "sudo make install" software that isn't managed
by Homebrew. If a brew tries to add locale information to one of these
directories, then the install will fail during the link step.
You should probably `chown` them:

    /usr/local/share/man/mann

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:

  /Library/Frameworks/Python.framework/Versions/2.7/bin/python-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
  /opt/local/bin/curl-config
  /opt/local/bin/freetype-config
  /opt/local/bin/libpng-config
  /opt/local/bin/libpng15-config
  /opt/local/bin/nc-config
  /opt/local/bin/ncurses5-config
  /opt/local/bin/ncursesw5-config
  /opt/local/bin/pcre-config
  /opt/local/bin/ppl-config
  /opt/local/bin/python2-config
  /opt/local/bin/python2.7-config
  /opt/local/bin/xml2-config

Warning: Your XQuartz (2.7.4) is outdated
Please install XQuartz 2.7.7:
  https://xquartz.macosforge.org

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: You have MacPorts or Fink installed:
  /opt/local/bin/port

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libboost_atomic.dylib
    /usr/local/lib/libboost_chrono.dylib
    /usr/local/lib/libboost_context.dylib
    /usr/local/lib/libboost_date_time.dylib
    /usr/local/lib/libboost_filesystem.dylib
    /usr/local/lib/libboost_graph.dylib
    /usr/local/lib/libboost_iostreams.dylib
    /usr/local/lib/libboost_locale.dylib
    /usr/local/lib/libboost_math_c99.dylib
    /usr/local/lib/libboost_math_c99f.dylib
    /usr/local/lib/libboost_math_c99l.dylib
    /usr/local/lib/libboost_math_tr1.dylib
    /usr/local/lib/libboost_math_tr1f.dylib
    /usr/local/lib/libboost_math_tr1l.dylib
    /usr/local/lib/libboost_prg_exec_monitor.dylib
    /usr/local/lib/libboost_program_options.dylib
    /usr/local/lib/libboost_python.dylib
    /usr/local/lib/libboost_random.dylib
    /usr/local/lib/libboost_regex.dylib
    /usr/local/lib/libboost_serialization.dylib
    /usr/local/lib/libboost_signals.dylib
    /usr/local/lib/libboost_system.dylib
    /usr/local/lib/libboost_thread.dylib
    /usr/local/lib/libboost_timer.dylib
    /usr/local/lib/libboost_unit_test_framework.dylib
    /usr/local/lib/libboost_wave.dylib
    /usr/local/lib/libboost_wserialization.dylib
    /usr/local/lib/libgtextutils-0.6.0.dylib
    /usr/local/lib/libplinkseq.dylib
    /usr/local/lib/libpng.3.dylib
    /usr/local/lib/libpng12.0.dylib
    /usr/local/lib/libpng14.14.dylib
    /usr/local/lib/libpng15.15.dylib
    /usr/local/lib/libprotobuf.7.dylib
    /usr/local/lib/libtcl8.6.dylib
    /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/bam/bam.h
    /usr/local/include/bam/bam2bcf.h
    /usr/local/include/bam/bam_endian.h
    /usr/local/include/bam/bam_tview.h
    /usr/local/include/bam/bgzf.h
    /usr/local/include/bam/errmod.h
    /usr/local/include/bam/faidx.h
    /usr/local/include/bam/kaln.h
    /usr/local/include/bam/khash.h
    /usr/local/include/bam/klist.h
    /usr/local/include/bam/knetfile.h
    /usr/local/include/bam/kprobaln.h
    /usr/local/include/bam/kseq.h
    /usr/local/include/bam/ksort.h
    /usr/local/include/bam/kstring.h
    /usr/local/include/bam/razf.h
    /usr/local/include/bam/sam.h
    /usr/local/include/bam/sam_header.h
    /usr/local/include/bam/sample.h
    /usr/local/include/bam.h
    /usr/local/include/fakemysql.h
    /usr/local/include/fakepq.h
    /usr/local/include/fakesql.h
    /usr/local/include/gtextutils/gtextutils/container_join.h
    /usr/local/include/gtextutils/gtextutils/exit_manip.h
    /usr/local/include/gtextutils/gtextutils/natsort.h
    /usr/local/include/gtextutils/gtextutils/pipe_fitter.h
    /usr/local/include/gtextutils/gtextutils/stream_wrapper.h
    /usr/local/include/gtextutils/gtextutils/string_tokenize.h
    /usr/local/include/gtextutils/gtextutils/strnatcmp.h
    /usr/local/include/gtextutils/gtextutils/text_line_reader.h
    /usr/local/include/gtextutils/gtextutils/tuple_parser.h
    /usr/local/include/itcl.h
    /usr/local/include/itcl2TclOO.h
    /usr/local/include/itclDecls.h
    /usr/local/include/itclInt.h
    /usr/local/include/itclIntDecls.h
    /usr/local/include/itclMigrate2TclCore.h
    /usr/local/include/itclTclIntStubsFcn.h
    /usr/local/include/libpng12/png.h
    /usr/local/include/libpng12/pngconf.h
    /usr/local/include/libpng14/png.h
    /usr/local/include/libpng14/pngconf.h
    /usr/local/include/libpng15/png.h
    /usr/local/include/libpng15/pngconf.h
    /usr/local/include/libpng15/pnglibconf.h
    /usr/local/include/mysqlStubs.h
    /usr/local/include/odbcStubs.h
    /usr/local/include/pqStubs.h
    /usr/local/include/python2.7/abstract.h
    /usr/local/include/python2.7/asdl.h
    /usr/local/include/python2.7/ast.h
    /usr/local/include/python2.7/bitset.h
    /usr/local/include/python2.7/boolobject.h
    /usr/local/include/python2.7/bufferobject.h
    /usr/local/include/python2.7/bytearrayobject.h
    /usr/local/include/python2.7/bytes_methods.h
    /usr/local/include/python2.7/bytesobject.h
    /usr/local/include/python2.7/cellobject.h
    /usr/local/include/python2.7/ceval.h
    /usr/local/include/python2.7/classobject.h
    /usr/local/include/python2.7/cobject.h
    /usr/local/include/python2.7/code.h
    /usr/local/include/python2.7/codecs.h
    /usr/local/include/python2.7/compile.h
    /usr/local/include/python2.7/complexobject.h
    /usr/local/include/python2.7/cStringIO.h
    /usr/local/include/python2.7/datetime.h
    /usr/local/include/python2.7/descrobject.h
    /usr/local/include/python2.7/dictobject.h
    /usr/local/include/python2.7/dtoa.h
    /usr/local/include/python2.7/enumobject.h
    /usr/local/include/python2.7/errcode.h
    /usr/local/include/python2.7/eval.h
    /usr/local/include/python2.7/fileobject.h
    /usr/local/include/python2.7/floatobject.h
    /usr/local/include/python2.7/frameobject.h
    /usr/local/include/python2.7/funcobject.h
    /usr/local/include/python2.7/genobject.h
    /usr/local/include/python2.7/graminit.h
    /usr/local/include/python2.7/grammar.h
    /usr/local/include/python2.7/import.h
    /usr/local/include/python2.7/intobject.h
    /usr/local/include/python2.7/intrcheck.h
    /usr/local/include/python2.7/iterobject.h
    /usr/local/include/python2.7/listobject.h
    /usr/local/include/python2.7/longintrepr.h
    /usr/local/include/python2.7/longobject.h
    /usr/local/include/python2.7/marshal.h
    /usr/local/include/python2.7/memoryobject.h
    /usr/local/include/python2.7/metagrammar.h
    /usr/local/include/python2.7/methodobject.h
    /usr/local/include/python2.7/modsupport.h
    /usr/local/include/python2.7/moduleobject.h
    /usr/local/include/python2.7/node.h
    /usr/local/include/python2.7/object.h
    /usr/local/include/python2.7/objimpl.h
    /usr/local/include/python2.7/opcode.h
    /usr/local/include/python2.7/osdefs.h
    /usr/local/include/python2.7/parsetok.h
    /usr/local/include/python2.7/patchlevel.h
    /usr/local/include/python2.7/pgen.h
    /usr/local/include/python2.7/pgenheaders.h
    /usr/local/include/python2.7/py_curses.h
    /usr/local/include/python2.7/pyarena.h
    /usr/local/include/python2.7/pycapsule.h
    /usr/local/include/python2.7/pyconfig.h
    /usr/local/include/python2.7/pyctype.h
    /usr/local/include/python2.7/pydebug.h
    /usr/local/include/python2.7/pyerrors.h
    /usr/local/include/python2.7/pyexpat.h
    /usr/local/include/python2.7/pyfpe.h
    /usr/local/include/python2.7/pygetopt.h
    /usr/local/include/python2.7/pymacconfig.h
    /usr/local/include/python2.7/pymactoolbox.h
    /usr/local/include/python2.7/pymath.h
    /usr/local/include/python2.7/pymem.h
    /usr/local/include/python2.7/pyport.h
    /usr/local/include/python2.7/pystate.h
    /usr/local/include/python2.7/pystrcmp.h
    /usr/local/include/python2.7/pystrtod.h
    /usr/local/include/python2.7/Python-ast.h
    /usr/local/include/python2.7/Python.h
    /usr/local/include/python2.7/pythonrun.h
    /usr/local/include/python2.7/pythread.h
    /usr/local/include/python2.7/rangeobject.h
    /usr/local/include/python2.7/setobject.h
    /usr/local/include/python2.7/sliceobject.h
    /usr/local/include/python2.7/stringobject.h
    /usr/local/include/python2.7/structmember.h
    /usr/local/include/python2.7/structseq.h
    /usr/local/include/python2.7/symtable.h
    /usr/local/include/python2.7/sysmodule.h
    /usr/local/include/python2.7/timefuncs.h
    /usr/local/include/python2.7/token.h
    /usr/local/include/python2.7/traceback.h
    /usr/local/include/python2.7/tupleobject.h
    /usr/local/include/python2.7/ucnhash.h
    /usr/local/include/python2.7/unicodeobject.h
    /usr/local/include/python2.7/warnings.h
    /usr/local/include/python2.7/weakrefobject.h
    /usr/local/include/tcl.h
    /usr/local/include/tclDecls.h
    /usr/local/include/tclOO.h
    /usr/local/include/tclOODecls.h
    /usr/local/include/tclPlatDecls.h
    /usr/local/include/tclThread.h
    /usr/local/include/tclTomMath.h
    /usr/local/include/tclTomMathDecls.h
    /usr/local/include/tdbc.h
    /usr/local/include/tdbcDecls.h
    /usr/local/include/tdbcInt.h
    /usr/local/include/tk.h
    /usr/local/include/tkDecls.h
    /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libgtextutils.la
    /usr/local/lib/libpng12.la
    /usr/local/lib/libpng14.la
    /usr/local/lib/libpng15.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/gtextutils.pc
    /usr/local/lib/pkgconfig/libpng12.pc
    /usr/local/lib/pkgconfig/libpng14.pc
    /usr/local/lib/pkgconfig/libpng15.pc
    /usr/local/lib/pkgconfig/python-2.7.pc
    /usr/local/lib/pkgconfig/tcl.pc
    /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libbam.a
    /usr/local/lib/libboost_atomic.a
    /usr/local/lib/libboost_chrono.a
    /usr/local/lib/libboost_context.a
    /usr/local/lib/libboost_date_time.a
    /usr/local/lib/libboost_exception.a
    /usr/local/lib/libboost_filesystem.a
    /usr/local/lib/libboost_graph.a
    /usr/local/lib/libboost_iostreams.a
    /usr/local/lib/libboost_locale.a
    /usr/local/lib/libboost_math_c99.a
    /usr/local/lib/libboost_math_c99f.a
    /usr/local/lib/libboost_math_c99l.a
    /usr/local/lib/libboost_math_tr1.a
    /usr/local/lib/libboost_math_tr1f.a
    /usr/local/lib/libboost_math_tr1l.a
    /usr/local/lib/libboost_prg_exec_monitor.a
    /usr/local/lib/libboost_program_options.a
    /usr/local/lib/libboost_python.a
    /usr/local/lib/libboost_random.a
    /usr/local/lib/libboost_regex.a
    /usr/local/lib/libboost_serialization.a
    /usr/local/lib/libboost_signals.a
    /usr/local/lib/libboost_system.a
    /usr/local/lib/libboost_test_exec_monitor.a
    /usr/local/lib/libboost_thread.a
    /usr/local/lib/libboost_timer.a
    /usr/local/lib/libboost_unit_test_framework.a
    /usr/local/lib/libboost_wave.a
    /usr/local/lib/libboost_wserialization.a
    /usr/local/lib/libgtextutils.a
    /usr/local/lib/libpng12.a
    /usr/local/lib/libpng14.a
    /usr/local/lib/libpng15.a
    /usr/local/lib/libpython2.7.a
    /usr/local/lib/libtclstub8.6.a
    /usr/local/lib/libtkstub8.6.a

Warning: /usr/bin occurs before /usr/local/bin
This means that system-provided programs will be used instead of those
provided by Homebrew. The following tools exist at both paths:

    2to3
    db_archive
    db_checkpoint
    db_deadlock
    db_dump
    db_hotbackup
    db_load
    db_printlog
    db_recover
    db_stat
    db_upgrade
    db_verify
    fragPlotr.R
    idle
    pydoc
    Python-2.7.3.tgz
    python2.7
    python2.7-config
    smtpd.py
    wget

Consider setting your PATH so that /usr/local/bin
occurs before /usr/bin. Here is a one-liner:
    echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bash_profile

Warning: Your Xcode (4.6.1) is outdated
Please update to Xcode 6.2.
Xcode can be updated from the App Store.

**Comment by DomT4** [comment]
No problem here.

```
checking for version 0.10 of ISL... no
checking for version 0.11 of ISL... yes
```

Your Xcode is very outdated, I'd recommend bumping it and trying again.

**Comment by baumeist** [comment]
Thank you,
I installed a newer version of xcode (beta 6.2) and tried again but gettin the following issue.
It's the same issue I am having with configuring other software lately.
Any thoughts.
br,
-M

configure: error: C compiler cannot create executables

$ brew install gcc48
==> Installing gcc48 from homebrew/homebrew-versions
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.8.4/gcc-4.8.4.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gcc48-4.8.4.tar.bz2
==> ../configure --build=x86_64-apple-darwin14.3.0 --prefix=/usr/local/Cellar/gc
checking for gcc... clang
checking for C compiler default output file name... 
configure: error: in `/private/tmp/gcc4820150610-3846-jnc2y9/gcc-4.8.4/build':
configure: error: C compiler cannot create executables
See `config.log' for more details.
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-versions/issues

**Comment by mistydemeo** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Can you provide the requested, please? The config.log would be helpful to determine the cause of this. Thanks!

**Comment by baumeist** [comment]
Thank for your reply,
After I installed the xcode command line tools I was able to get "brew install gcc48" to install and build. 
==> Installing gcc48 from homebrew/homebrew-versions
==> Downloading https://homebrew.bintray.com/bottles-versions/gcc48-4.8.4.yosemi
######################################################################## 100.0%
==> Pouring gcc48-4.8.4.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/gcc48/4.8.4: 1028 files, 142M

I then tried to run ./configure for another application (bcl2fastq). 
An attempt was made to configure this app but stopped due to some errors with the c compiler.

$ ./configure
Decompressing /Applications/bcl2fastq/src/../redist/cmake-2.8.4.tar.gz
---------------------------------------------
CMake 2.8.4, Copyright 2000-2009 Kitware, Inc.
Found GNU toolchain
C compiler on this system is: gcc 
C++ compiler on this system is: g++ 
Makefile processor on this system is: make
g++ is GNU compiler
g++ has STL in std:: namespace
g++ has ANSI streams
g++ has streams in std:: namespace
g++ has sstream
g++ has operator!=(string, char*)
g++ has stl iterator_traits
g++ has standard template allocator
g++ has allocator<>::rebind<>
g++ does not have non-standard allocator<>::max_size argument
g++ has stl containers supporting allocator objects
g++ has header cstddef
g++ requires template friends to use <>
g++ supports member templates
g++ has standard template specialization syntax
g++ has argument dependent lookup
g++ does not have struct stat with st_mtim member
g++ has ios::binary openmode
g++ has ANSI for scoping
---------------------------------------------
g++  -I/Applications/bcl2fastq/src/bootstrap/build/cmake-2.8.4/Bootstrap.cmk -I/Applications/bcl2fastq/src/bootstrap/build/cmake-2.8.4/Source   -I/Applications/bcl2fastq/src/bootstrap/build/cmake-2.8.4/Bootstrap.cmk -c /Applications/bcl2fastq/src/bootstrap/build/cmake-2.8.4/Source/cmStandardIncludes.cxx -o cmStandardIncludes.o
couldn't understand kern.osversion `14.3.0'
g++  -I/Applications/bcl2fastq/src/bootstrap/build/cmake-2.8.4/Bootstrap.cmk -I/Applications/bcl2fastq/src/bootstrap/build/cmake-2.8.4/Source   -I/Applications/bcl2fastq/src/bootstrap/build/cmake-2.8.4/Bootstrap.cmk -c /Applications/bcl2fastq/src/bootstrap/build/cmake-2.8.4/Source/cmake.cxx -o cmake.o
couldn't understand kern.osversion `14.3.0'
/Applications/bcl2fastq/src/bootstrap/build/cmake-2.8.4/Source/cmake.cxx: In instantiation of ‘std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, const std::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char, _Traits = std::char_traits<char>, _Alloc = std::allocator<char>]’:
/Applications/bcl2fastq/src/bootstrap/build/cmake-2.8.4/Source/cmake.cxx:388:   instantiated from here
/Applications/bcl2fastq/src/bootstrap/build/cmake-2.8.4/Source/cmake.cxx:388: error: explicit instantiation of ‘std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, const std::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char, _Traits = std::char_traits<char>, _Alloc = std::allocator<char>]’ but no definition available
/Applications/bcl2fastq/src/bootstrap/build/cmake-2.8.4/Source/cmake.cxx: In instantiation of ‘std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, const std::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char, _Traits = std::char_traits<char>, _Alloc = std::allocator<char>]’:
/Applications/bcl2fastq/src/bootstrap/build/cmake-2.8.4/Source/cmake.cxx:388:   instantiated from here
/Applications/bcl2fastq/src/bootstrap/build/cmake-2.8.4/Source/cmake.cxx:388: error: explicit instantiation of ‘std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, const std::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char, _Traits = std::char_traits<char>, _Alloc = std::allocator<char>]’ but no definition available
/Applications/bcl2fastq/src/bootstrap/build/cmake-2.8.4/Source/cmake.cxx: In instantiation of ‘std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, const std::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char, _Traits = std::char_traits<char>, _Alloc = std::allocator<char>]’:
/Applications/bcl2fastq/src/bootstrap/build/cmake-2.8.4/Source/cmake.cxx:388:   instantiated from here
/Applications/bcl2fastq/src/bootstrap/build/cmake-2.8.4/Source/cmake.cxx:388: error: explicit instantiation of ‘std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, const std::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char, _Traits = std::char_traits<char>, _Alloc = std::allocator<char>]’ but no definition available
make: *** [cmake.o] Error 1
---------------------------------------------
Error when bootstrapping CMake:
Problem while running make
---------------------------------------------
Log of errors: /Applications/bcl2fastq/src/bootstrap/build/cmake-2.8.4/Bootstrap.cmk/cmake_bootstrap.log
---------------------------------------------
cmake: build failed: Terminating...
Failed to verify or install cmake


I then learned that the gcc it was using was not the newly installed gcc48:
$ which gcc
/usr/local/bin/gcc

$ gcc --version
couldn't understand kern.osversion `14.3.0'
i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)


So, I tried to symlink to gcc-4.8 
$ ln -s gcc-4.8 gcc


However, when I try to configure I get the old error with my c compiler, I get:

$ ./configure
Decompressing /Applications/bcl2fastq/src/../redist/cmake-2.8.4.tar.gz
---------------------------------------------
CMake 2.8.4, Copyright 2000-2009 Kitware, Inc.
---------------------------------------------
Error when bootstrapping CMake:
Cannot find appropriate C compiler on this system.
Please specify one using environment variable CC.
See cmake_bootstrap.log for compilers attempted.

---------------------------------------------
Log of errors: /Applications/bcl2fastq/src/bootstrap/build/cmake-2.8.4/Bootstrap.cmk/cmake_bootstrap.log
---------------------------------------------
cmake: build failed: Terminating...
Failed to verify or install cmake


This is the log file:

Checking for GNU toolchain
Try: gcc
Line: gcc  cmake_bootstrap_8080_test.c -o cmake_bootstrap_8080_test
----------  file   -----------------------
int main() { return 0; }
------------------------------------------
Undefined symbols for architecture x86_64:
  "start", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
Test failed to compile
Checking for Clang toolchain
Try: clang
Line: clang  cmake_bootstrap_8080_test.c -o cmake_bootstrap_8080_test
----------  file   -----------------------
int main() { return 0; }
------------------------------------------
Undefined symbols for architecture x86_64:
  "start", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Test failed to compile
Try: cc
Line: cc  cmake_bootstrap_8080_test.c -o cmake_bootstrap_8080_test
----------  file   -----------------------

#ifdef __cplusplus
# error "The CMAKE_C_COMPILER is set to a C++ compiler"
#endif

#include<stdio.h>

#if defined(__CLASSIC_C__)
int main(argc, argv)
  int argc;
  char* argv[];
#else
int main(int argc, char* argv[])
#endif
{
  printf("%d%c", (argv != 0), (char)0x0a);
  return argc-1;
}

------------------------------------------
Undefined symbols for architecture x86_64:
  "start", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Test failed to compile
Try: gcc
Line: gcc  cmake_bootstrap_8080_test.c -o cmake_bootstrap_8080_test
----------  file   -----------------------

#ifdef __cplusplus
# error "The CMAKE_C_COMPILER is set to a C++ compiler"
#endif

#include<stdio.h>

#if defined(__CLASSIC_C__)
int main(argc, argv)
  int argc;
  char* argv[];
#else
int main(int argc, char* argv[])
#endif
{
  printf("%d%c", (argv != 0), (char)0x0a);
  return argc-1;
}

------------------------------------------
Undefined symbols for architecture x86_64:
  "start", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
Test failed to compile
Try: xlc
Line: xlc  cmake_bootstrap_8080_test.c -o cmake_bootstrap_8080_test
----------  file   -----------------------

#ifdef __cplusplus
# error "The CMAKE_C_COMPILER is set to a C++ compiler"
#endif

#include<stdio.h>

#if defined(__CLASSIC_C__)
int main(argc, argv)
  int argc;
  char* argv[];
#else
int main(int argc, char* argv[])
#endif
{
  printf("%d%c", (argv != 0), (char)0x0a);
  return argc-1;
}

------------------------------------------
./bootstrap: line 476: xlc: command not found
Test failed to compile
Try: icc
Line: icc  cmake_bootstrap_8080_test.c -o cmake_bootstrap_8080_test
----------  file   -----------------------

#ifdef __cplusplus
# error "The CMAKE_C_COMPILER is set to a C++ compiler"
#endif

#include<stdio.h>

#if defined(__CLASSIC_C__)
int main(argc, argv)
  int argc;
  char* argv[];
#else
int main(int argc, char* argv[])
#endif
{
  printf("%d%c", (argv != 0), (char)0x0a);
  return argc-1;
}

------------------------------------------
./bootstrap: line 476: icc: command not found
Test failed to compile
Try: tcc
Line: tcc  cmake_bootstrap_8080_test.c -o cmake_bootstrap_8080_test
----------  file   -----------------------

#ifdef __cplusplus
# error "The CMAKE_C_COMPILER is set to a C++ compiler"
#endif

#include<stdio.h>

#if defined(__CLASSIC_C__)
int main(argc, argv)
  int argc;
  char* argv[];
#else
int main(int argc, char* argv[])
#endif
{
  printf("%d%c", (argv != 0), (char)0x0a);
  return argc-1;
}

------------------------------------------
./bootstrap: line 476: tcc: command not found
Test failed to compile

**Comment by jacknagel** [comment]
>C compiler on this system is: gcc 
C++ compiler on this system is: g++ 

Note the above in the output you posted. This is not using the gcc48 formula. Rather, it is using the OS X gcc shim which is actually clang. If you want to use gcc48, you need to do something more like `CC=gcc-4.8 ./configure`.

But regardless, since this build failure is not a formula problem, we can't really provide this level of support.
