### ISSUE TITLE
subversion16 failed to build

### ISSUE THREAD

**Issue by adamsteen** [Homebrew/homebrew-versions#895]
Attempted a brew install homebrew/versions/subversion16 on Ubuntu Trusty 64 and got the following

==> Installing subversion16 from homebrew/homebrew-versions
==> Downloading https://archive.apache.org/dist/subversion/subversion-1.6.23.tar.bz2
Already downloaded: /home/vagrant/.cache/Homebrew/subversion16-1.6.23.tar.bz2
==> Downloading https://trac.macports.org/export/73004/trunk/dports/devel/subversion-javahlbindings/files/patch-configure.diff
Already downloaded: /home/vagrant/.cache/Homebrew/subversion16--patch-2524f14483a2db859c0ae9da1edec49b5450d3ae0393b36f7a329ed66f596493.diff
==> Patching
patching file configure
Hunk #1 succeeded at 23390 with fuzz 1 (offset 8 lines).
Hunk #2 succeeded at 23540 with fuzz 1 (offset 32 lines).
Hunk #3 succeeded at 23693 with fuzz 1 (offset 56 lines).
Hunk #4 succeeded at 26271 (offset 67 lines).
==> Downloading http://webdav.org/neon/neon-0.28.3.tar.gz
Already downloaded: /home/vagrant/.cache/Homebrew/subversion16--neon-0.28.3.tar.gz
==> ./configure --prefix=/home/vagrant/.linuxbrew/Cellar/subversion16/1.6.23/libexec/neon --enable-shared --disable-static --disable-nls --with-ssl=openssl --with-libs=/usr/lib
==> make install
==> ./configure --prefix=/home/vagrant/.linuxbrew/Cellar/subversion16/1.6.23 --with-ssl --with-zlib=/usr --with-sqlite=/usr --disable-neon-version-check --disable-mod-activation --without
checking for egrep... /bin/grep -E
checking whether ln -s works... yes
checking for a BSD-compatible install... /usr/bin/install -c
configure: Apache Portable Runtime (APR) library configuration
checking for APR... configure: error: the --with-apr parameter is incorrect. It must specify an install prefix, a build directory, or an apr-config file.

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-versions/issues

**Comment by DomT4** [comment]
Theoretically [this block](https://github.com/Homebrew/homebrew-versions/blob/master/subversion16.rb#L157-L163) should be passing a correct `apr` to you. Can you `brew gist-logs subversion16`?

CC @sjackman

**Comment by adamsteen** [comment]
Done.

https://gist.github.com/7251591bdebe6a333ef6

**Comment by DomT4** [comment]
Yeah, it's [mis-detecting](https://gist.github.com/anonymous/7251591bdebe6a333ef6#file-03-configure-L14-L15) where it should be scooping up `apr` from.

It's possible the APR dependency resolution we have in place for Apr on OS X doesn't work on Linux, which would cause the failure. Will wait for @sjackman to review, but I'm not opposed to adding a Linux fix if there's an easy one available here.

**Comment by sjackman** [comment]
Hi, Dominyk. Here's the diff of `subversion` between `homebrew/master` and `linuxbrew/master`:

```sh
git diff homebrew/master...master -- Library/Formula/subversion.rb
```

```diff
diff --git a/Library/Formula/subversion.rb b/Library/Formula/subversion.rb
index 69a246d..e6a9a00 100644
--- a/Library/Formula/subversion.rb
+++ b/Library/Formula/subversion.rb
@@ -27,6 +27,7 @@ class Subversion < Formula
   option "with-perl", "Build Perl bindings"
   option "with-ruby", "Build Ruby bindings"
   option "with-gpg-agent", "Build with support for GPG Agent"
+  option "without-serf", "Build without the serf HTTP library"
 
   resource "serf" do
     url "https://serf.googlecode.com/svn/src_releases/serf-1.3.8.tar.bz2", :using => :curl
@@ -46,6 +47,10 @@ class Subversion < Formula
   # For Serf
   depends_on "scons" => :build
   depends_on "openssl"
+  unless OS.mac?
+    depends_on "apr"
+    depends_on "apr-util"
+  end
 
   # Other optional dependencies
   depends_on "gpg-agent" => :optional
@@ -85,7 +90,7 @@ class Subversion < Formula
       end
     end
 
-    serf_prefix = libexec+"serf"
+    serf_prefix = OS.mac? ? libexec+"serf" : prefix
 
     resource("serf").stage do
       # SConstruct merges in gssapi linkflags using scons's MergeFlags,
@@ -100,14 +105,14 @@ class Subversion < Formula
                 CFLAGS=#{ENV.cflags} LINKFLAGS=#{ENV.ldflags}
                 OPENSSL=#{Formula["openssl"].opt_prefix}]
 
-      unless MacOS::CLT.installed?
+      unless OS.mac? && MacOS::CLT.installed?
         args << "APR=#{Formula["apr"].opt_prefix}"
         args << "APU=#{Formula["apr-util"].opt_prefix}"
       end
 
       scons *args
       scons "install"
-    end
+    end if build.with? "serf"
 
     if build.include? "unicode-path"
       raise <<-EOS.undent
@@ -144,7 +149,7 @@ class Subversion < Formula
             "--prefix=#{prefix}",
             "--with-zlib=/usr",
             "--with-sqlite=#{Formula["sqlite"].opt_prefix}",
-            "--with-serf=#{serf_prefix}",
+            ("--with-serf=#{serf_prefix}" if build.with? "serf"),
             "--disable-mod-activation",
             "--disable-nls",
             "--without-apache-libexecdir",
@@ -153,7 +158,7 @@ class Subversion < Formula
     args << "--enable-javahl" << "--without-jikes" if build.with? "java"
     args << "--without-gpg-agent" if build.without? "gpg-agent"
 
-    if MacOS::CLT.installed?
+    if OS.mac? && MacOS::CLT.installed?
       args << "--with-apr=/usr"
       args << "--with-apr-util=/usr"
     else
```

**Comment by DomT4** [comment]
Thinking about it, there's no way to actually support this on Linux :disappointed:. For SSL support in SVN the internal `neon` requires the usage of an OpenSSL which has SSLv2 enabled, which doesn't apply to the Linux shipped OpenSSL or any Homebrew shipped OpenSSL. We're actually building these SVNs against the system OpenSSL on OS X at the moment, which I dislike.

**Comment by sjackman** [comment]
`subversion` builds just fine on Linux with the above patch. Is `subversion16` different than `subversion`?

**Comment by DomT4** [comment]
There's an internal `neon` to enable SSL support, and that internal `neon` requires SSLv2 support. The main Homebrew/homebrew Subversion has no requirement for `neon` to access SSL support.

**Comment by sjackman** [comment]
I'm okay with closing this issue as `wontfix`.

**Comment by DomT4** [comment]
Thanks Shaun. We may well end up killing both SVN16/17, they're becoming increasingly difficult to support and keep up with the features people expect from them :/.
