### ISSUE TITLE
mapserver failed to built on 10.10.4

### ISSUE THREAD

**Issue by mach2Toulon** [Homebrew/homebrew-versions#923]
Hi,

I've tried to put this on command line : 
$ brew install mapserver --with-php

Result : 
==> Downloading http://download.osgeo.org/mapserver/mapserver-6.2.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/mapserver-6.2.2.tar.gz
==> Patching
patching file mapscript/python/setup.py
Hunk #1 FAILED at 32.
Hunk #2 FAILED at 149.
2 out of 3 hunks FAILED -- saving rejects to file mapscript/python/setup.py.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1

Any idea ?

**Comment by mach2Toulon** [comment]
Resolved. I used the package from osgeo4mac tap.

**Comment by manishdas** [comment]
@mach2Toulon I'm getting this error even tapping osgeo4mac package. Any idea?

**Comment by tblanchard** [comment]
I'm stuck on this too - no idea where this file mapscript/python/setup.py is

**Comment by drtzack** [comment]
same here.
