### ISSUE TITLE
bash-completion2: broken brew symlink

### ISSUE THREAD

**Issue by carlosliu** [Homebrew/homebrew-versions#926]
Current "brew" symlink created in post_install is linked to the wrong location because "/usr/local/share/bash-completion" is also a symlink to a directory in the different depth. To understand this issue, cd into /usr/local/share/bash-completion/completions, then run "ls ../../.." and "cd ../../..". You will see the different result. "ls ../../.." will go three level above the realpath, and show you the content in /usr/local/Cellar/bash-completion2/2.1_2/. But result of "cd ../../.." is three level above PWD, which is /usr/local.

**Comment by DomT4** [comment]
Closed via https://github.com/Homebrew/homebrew-versions/commit/71845e3280e37bb999ae6672e032d06fda49019e.
