### ISSUE TITLE
issue while installing subversion17 on mac

### ISSUE THREAD

**Issue by nareshguggilla** [Homebrew/homebrew-versions#931]
Below is the error message I am got when i tried to install subversion17 using homebrew.

$ brew install --universal --with-java subversion17 --with-jdk=/usr/libexec/java_home
==> Installing subversion17 from homebrew/homebrew-versions
==> Downloading https://archive.apache.org/dist/subversion/subversion-1.7.14.tar.bz2
Already downloaded: /Library/Caches/Homebrew/subversion17-1.7.14.tar.bz2
==> Downloading http://webdav.org/neon/neon-0.29.6.tar.gz
Already downloaded: /Library/Caches/Homebrew/subversion17--neon-0.29.6.tar.gz
==> ./configure --prefix=/usr/local/Cellar/subversion17/1.7.14_1/libexec/neon --enable-shared --disable-static --disable-nls --with-ssl=openssl --with-libs=/usr/lib
==> make install
==> Downloading https://serf.googlecode.com/files/serf-1.3.3.tar.bz2
Already downloaded: /Library/Caches/Homebrew/subversion17--serf-1.3.3.tar.bz2
==> /usr/local/opt/scons/bin/scons PREFIX=/usr/local/Cellar/subversion17/1.7.14_1/libexec/serf GSSAPI=/usr CC=/usr/bin/clang CFLAGS=-I/usr/local/Cellar/subversion17
==> /usr/local/opt/scons/bin/scons install
==> ./configure --prefix=/usr/local/Cellar/subversion17/1.7.14_1 --with-zlib=/usr --with-sqlite=/usr/local/opt/sqlite --with-serf=/usr/local/Cellar/subversion17/1.7
checking for apr_int64_t Python/C API format string... l
checking perl version... 5018002
checking for ctypesgen.py... none
configure: error: Cannot compile JavaHL without a suitable JDK.
                  Please specify a suitable JDK using the --with-jdk option.

**Comment by DomT4** [comment]
Can you produce a full `brew gist-logs subversion17` please.

**Comment by DomT4** [comment]
Presuming dead. Feel free to let us know if we can help any further on this, Thanks!
