### ISSUE TITLE
No gcc5x versions

### ISSUE THREAD

**Issue by sambrightman** [Homebrew/homebrew-versions#954]
It looks like the gcc5 formula is not pinned, and will switch between releases unexpectedly as they are made. This makes it hard to depend on specific major versions, which used to be possible with e.g. gcc48/gcc49.

**Comment by mistydemeo** [comment]
The GCC versioning scheme changed as of GCC 5. The major version number (e.g. 5) is now equivalent of the series release number in previous versions of GCC. The difference between GCC 5.1 and 5.2 is the equivalent of the difference between GCC 4.9.1 and 4.9.2. For that reason, we're only planning to include formulae for each major version in this tap.

You can read about the changes to the versioning scheme [at the GCC site](https://gcc.gnu.org/develop.html#num_scheme).

**Comment by sambrightman** [comment]
Thanks, should have checked that first.
