### ISSUE TITLE
Issues with brew install gcc49 --with-fortran [libgcc_ext.10.4.dylib] Error 127

### ISSUE THREAD

**Issue by dunn** [Homebrew/homebrew-versions#957]
_From @amitvirat on September 3, 2015 6:54_

I am facing issues with brew install for gcc49 with fortran since R packages are failing. While doing install I am getting error messages as follows:

/bin/sh: lipo: command not found
make[3]: *** [libgcc_ext.10.4.dylib] Error 127
make[2]: *** [all-stage1-target-libgcc] Error 2
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2

Ran brew update: All good
Ran brew doctor: No issues

gist logs are available at: https://gist.github.com/4506b82cc0636b324aa2

Can someone please help?

_Copied from original issue: Homebrew/homebrew#43531_

**Comment by dunn** [comment]
_From @amitvirat on September 3, 2015 8:13_

Update: I tried it again after reinstalling Xcode 6.4 but still the same error

**Comment by mistydemeo** [comment]
```
/bin/sh: lipo: command not found
make[3]: *** [libgcc_s.1.dylib] Error 127
make[3]: *** Waiting for unfinished jobs....
/bin/sh: lipo: command not found
make[3]: *** [libgcc_ext.10.5.dylib] Error 127
```

It shouldn't be possible for this to be missing on OS X 10.10; do you have a `/usr/bin/lipo`?

**Comment by amitvirat** [comment]
Nope.. I tried "which lipo " and that came blank.

**Comment by mistydemeo** [comment]
I'm not sure how it could go missing; that file comes with the OS.

You'll need to restore it in order to fix this problem. A few options are:

* Reinstall OS X
* Restore the file from Time Machine
* Obtain a copy from a friend running the same version of OS X

Unfortunately, since the file comes with OS X, reinstalling Xcode or the CLT will not restore it for you. Once it's back, this build should work again.

**Comment by amitvirat** [comment]
ok.. i did a workaround.. copied lipo from Xcode toolchains 
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo
```
Hope that will not cause any issues..

but after that I am hitting my previous error i had when I last tried installing gcc49.
```
tail: ~/Library/Logs/Homebrew/gcc49/02.make: No such file or directory
```
Any idea how to fix that. If required I can close this issue chain and open a new one

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
