### ISSUE TITLE
ruby187 should not share its gems

### ISSUE THREAD

**Issue by jlecour** [Homebrew/homebrew-versions#962]
Hi,

If I understand correctly, this repository is intended to be a way to install a specific version of a package, even if it's not the latest.

Since it's so difficult to compile and install Ruby 1.8.7 on a recent OS X (I'm using 10.10) I was very glad to find this.

The thing is that many of its subdirectories are symlinked to a global Homebrew managed directory.

For example, in `/usr/local/Cellar/ruby187/1.8.7-p374/lib/ruby` there are 3 symlinks which point to a 2.2 install of Ruby. It *seems* completely wrong to share those directories since the content is mostly incompatible across versions.

I'm adding emphasis on *seems* because I'm no expert and I might be completely wrong, but in the end, I can't find a way to use Ruby 1.8.7 :(

Anyway, thanks a lot for maintaining this.

**Comment by UniqMartin** [comment]
This has recently changed with a complete revamp of the formula in #1026, which should make it a lot more useful and bring it closer to your expectations. Please give it a try with the usual `brew update` and `brew upgrade` and report back.
