### ISSUE TITLE
Failed to update tap: caskroom/versions

### ISSUE THREAD

**Issue by neverfox** [Homebrew/homebrew-versions#963]
Getting `Failed to update tap: caskroom/versions` on all my machines in the last few days. I retapped it but that didn't help.

**Comment by DomT4** [comment]
Wrong place I'm afraid. You want https://github.com/caskroom/homebrew-versions.

They called it the same thing, which is a little confusing, but the Caskroom & Homebrew have no direct control over each other; just part of the same family.
