### ISSUE TITLE
brew install gcc49 on mac 10.10 ( ISL not find error )

### ISSUE THREAD

**Issue by zhangjianxing** [Homebrew/homebrew-versions#973]
when I try to install gcc49, error arise :

 o-> $  brew install https://raw.githubusercontent.com/Homebrew/homebrew-versions/master/gcc49.rb
######################################################################## 100.0%
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.9.3/gcc-4.9.3.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gcc49-4.9.3.tar.bz2
==> ../configure --build=x86_64-apple-darwin14.5.0 --prefix=/usr/local/Cellar/gcc49/4.9.3 --libdir=/usr/local/Cellar/gcc49/4.9.3/lib/gcc/4.9 --enable-languages=c,c++,objc,obj-c++ --program-suffix=-4.9 --w
checking for version 0.10 of ISL... no
checking for version 0.11 of ISL... no
checking for version 0.12 of ISL... no
checking for version 0.14 of ISL... no
configure: error: Unable to find a usable ISL.  See config.log for details.
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

READ THIS: https://git.io/brew-troubleshooting

However, I do have ISL:

o-> $  brew info isl
isl: stable 0.14.1 (bottled), HEAD
Integer Set Library for the polyhedral model
http://freecode.com/projects/isl
/usr/local/Cellar/isl/0.14.1 (68 files, 3.2M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/isl.rb
==> Dependencies
Build: xz ✔
Required: gmp ✔

I do not know where is the config.log located.

Anyone can help, please

**Comment by DomT4** [comment]
It uses `isl011` as the dependency. Can you `brew info isl011`?

**Comment by zhangjianxing** [comment]
solved by "$ xcode-select --install"

**Comment by DomT4** [comment]
Great! Glad everything is working for you again. Let us know if we can help any other way.

**Comment by zhangjianxing** [comment]
Thanks for you patient reply!
