### ISSUE TITLE
brew install mysql55 <-- Doesn't link the file properly

### ISSUE THREAD

**Issue by luck02** [Homebrew/homebrew-versions#978]
After:
```
brew install mysql 
brew remove mysql
brew tap homebrew/versions
brew install mysql55
```
The package seems to install, but not found in the path:

```
mysql
>> mysql not found 

```

if I do:
```
brew link mysql55 -f
```

It seems to come to life, is this expected or abnormal operation?

**Comment by DomT4** [comment]
It's deliberate in [this case](https://github.com/Homebrew/homebrew-versions/blob/master/mysql55.rb#L31). `mysql55` is locked inside its keg as it conflicts with a whole bunch of other formulae.

My personal method for selectively circumventing `keg_only` status is to prepend my `$PATH` with `/usr/local/opt/mysql55/bin` (Presuming you've installed Homebrew into `/usr/local`). Force linking is a fairly blunt tool sadly.

**Comment by luck02** [comment]
Speaking from a position of little experience with homebrew (new shop is an osx shop, I'm from a split linux / windows background).  The documentation is lacking.

https://github.com/Homebrew/homebrew-versions/blob/master/mysql55.rb#L148

IF you look at the output from installing the package it does say: "Keg only" but without knowing what that means it looks like a general warning because it lists a bunch of conflicts.

The last thing shows how to run the package 'mysql.server start' but doesn't go on to say: "But you need to do the following first or run from installed path.

G

**Comment by DomT4** [comment]
We're aware the terminology is a little confusing to newcomers, so our apologies on that. We've been talking about how to improve that for a while now and generally working on making available API documentation rather than [this hoard](https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew) of documentation most people don't glance at.

> The last thing shows how to run the package 'mysql.server start' but doesn't go on to say: "But you need to do the following first or run from installed path.

I'll get this fixed.

**Comment by luck02** [comment]
Awesome, thanks allot :+1:

**Comment by DomT4** [comment]
Fixed the paths issue in https://github.com/Homebrew/homebrew-versions/commit/91bcebdeb6e78e7552672f52899f17fddc3a4091.
