### ISSUE TITLE
Mongo 2.6 incompatible with OSX 10.11 (El Capitan)

### ISSUE THREAD

**Issue by toddbluhm** [Homebrew/homebrew-versions#980]
When trying to install mongo 2.6 with osx 10.11 I am receiving this error. I believe it just needs to be updated to include 10.11, but I'm not super familiar with how brew does its formulae. Thanks!

Here is the terminal output log:
<img width="728" alt="screen shot 2015-10-01 at 4 51 41 pm" src="https://cloud.githubusercontent.com/assets/197282/10233606/840bf9f6-685d-11e5-84af-8a14bca21be4.png">

**Comment by roflomglol** [comment]
Have same problem. Would really appreciate at least some monkey patching tips. :) I tried to modify formula to use 10.10 version - it won't install anyway.  I guess I must find that SCons constructor file, but I have no clue where to find it yet. :)

**Comment by toddbluhm** [comment]
Looks like there is now an open PR to solve this issue: https://github.com/Homebrew/homebrew-versions/pull/985

Thanks @asmarques

**Comment by DomT4** [comment]
Meged the PR.
