### ISSUE TITLE
llvm34 fails to build under El Capitan

### ISSUE THREAD

**Issue by rzil** [Homebrew/homebrew-versions#981]
https://gist.github.com/dc7570d10700e69d78be

Here is the end of the log:

llvm[4]: ======= Finished Linking Release+Asserts Unit test Tooling (without symbols)
make: *** [all] Error 1

**Comment by dunn** [comment]
```
ScheduleOptimizer.cpp:399:13: error: use of undeclared identifier 'isl_band_member_is_zero_distance'
        if (isl_band_member_is_zero_distance(Band, j)) {
            ^
```
There have been some recent compatibility issues with isl and gcc, but I don't know what's going on here.

**Comment by fxfactorial** [comment]
I also get this: 
```shell
llvm[4]: ======= Finished Linking Release+Asserts Unit test Tooling (without symbols)
make: *** [all] Error 1
couldn't understand kern.osversion `15.0.0'
```

I take it there are no fixes for this?

**Comment by DomT4** [comment]
I'm not hugely surprised this broke. Your best bet is poking around upstream for fixes in either their bug tracker or head.

**Comment by camargo** [comment]
Has anyone tried this? https://gist.github.com/i-kiwamu/4833d8f22130ee179291#file-scheduleoptimizer_patch-diff

**Comment by dunn** [comment]
@camargo does LLVM 3.4 build with that patch, and has it been submitted upstream?

**Comment by camargo** [comment]
Not sure I have not tried it yet. Also not sure if it has been submitted upstream.

**Comment by eturk** [comment]
Is there any progress on this issue? I'm running into trouble building `llvm34` as well: https://gist.github.com/eturk/901b110e83e259e9d64770b978239cba

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
