### ISSUE TITLE
v8-315 SHA256 mismatch

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-versions#982]
_From @thehappycoder on October 1, 2015 14:53_

```
$ brew install homebrew/versions/v8-315
==> Installing v8-315 from homebrew/homebrew-versions
==> Downloading https://github.com/v8/v8-git-mirror/archive/3.15.11.18.tar.gz
Already downloaded: /Library/Caches/Homebrew/v8-315-3.15.11.18.tar.gz
Error: SHA256 mismatch
Expected: 389c03f67731874342486536bd231c43281fe43d05001664000abd3ac48fd9cf
Actual: 93a4945a550e5718d474113d9769a3c010ba21e3764df8f22932903cd106314d
Archive: /Library/Caches/Homebrew/v8-315-3.15.11.18.tar.gz
To retry an incomplete download, remove the file above.
```

_Copied from original issue: Homebrew/homebrew#44496_

**Comment by bfontaine** [comment]
I can reproduce:
```
$ curl -sL 'https://github.com/v8/v8-git-mirror/archive/3.15.11.18.tar.gz' | shasum -a 256
93a4945a550e5718d474113d9769a3c010ba21e3764df8f22932903cd106314d  -
```

**Comment by rsumilang** [comment]
I'm having the same issue.

**Comment by DomT4** [comment]
Upstream seem to have force synced the entire Github mirror; all the checksums have changed. Still waiting on anyone at V8/Google to confirm this was intentional and non-malicious though.

**Comment by aianus** [comment]
Any news? Is there a (safe) workaround?

I'm unable to install the Ethereum client because of this.

**Comment by DomT4** [comment]
None yet. I've asked 3 people at this point to ask upstream what happened to the Github mirror, whether it was force pushed over, resynced, etc but as far as I know nobody's reached out to upstream :cry:.

**Comment by Bunkydoo** [comment]
I'm having issues with installing cpp-ethereum thanks to this issue... On OS X 10.11 if that might have something to do with it - know this release might not be entirely supported yet or some bs

**Comment by juanpaucar** [comment]
I've had this issue for a while, could this be related to the use of `brew link --overwrite v8-315 --force`?

**Comment by DomT4** [comment]
> know this release might not be entirely supported yet or some bs

El Cap is supported. You'd get a warning otherwise.

> could this be related to the use of brew link --overwrite v8-315 --force?

No. It's purely an upstream thing where they've done something to the Github mirror that caused the checksums to universally break. I'll try and reach someone upstream.

**Comment by DomT4** [comment]
Closed via https://github.com/Homebrew/homebrew-versions/commit/f080318543de5007836184bbd294ce989629d3d3.
